# -*- coding: utf-8 -*-
####################################################
########## coding by RND youkyoung.kim #############
####################################################

import Qt
from Qt import QtGui
from Qt import QtWidgets as QtGui
from Qt import QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(700, 900)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.animation_ck = QtGui.QCheckBox(Form)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.animation_ck.setFont(font)
        self.animation_ck.setObjectName(_fromUtf8("animation_ck"))
        self.horizontalLayout.addWidget(self.animation_ck)
        self.label = QtGui.QLabel(Form)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.animation_selbtn = QtGui.QPushButton(Form)
        self.animation_selbtn.setMinimumSize(QtCore.QSize(150, 30))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.animation_selbtn.setFont(font)
        self.animation_selbtn.setObjectName(_fromUtf8("animation_selbtn"))
        self.horizontalLayout.addWidget(self.animation_selbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.animation_tree = QtGui.QTreeWidget(Form)
        self.animation_tree.setObjectName(_fromUtf8("animation_tree"))
        self.animation_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.animation_tree.headerItem().setFont(0, font)
        self.animation_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.animation_tree.headerItem().setFont(1, font)
        self.animation_tree.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.animation_tree.headerItem().setFont(2, font)
        self.animation_tree.headerItem().setTextAlignment(3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.animation_tree.headerItem().setFont(3, font)
        self.verticalLayout.addWidget(self.animation_tree)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.nonanimation_ck = QtGui.QCheckBox(Form)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nonanimation_ck.setFont(font)
        self.nonanimation_ck.setObjectName(_fromUtf8("nonanimation_ck"))
        self.horizontalLayout_5.addWidget(self.nonanimation_ck)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.nonanimation_selbtn = QtGui.QPushButton(Form)
        self.nonanimation_selbtn.setMinimumSize(QtCore.QSize(150, 30))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nonanimation_selbtn.setFont(font)
        self.nonanimation_selbtn.setObjectName(_fromUtf8("nonanimation_selbtn"))
        self.horizontalLayout_5.addWidget(self.nonanimation_selbtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        self.nonanimation_tree = QtGui.QTreeWidget(Form)
        self.nonanimation_tree.setObjectName(_fromUtf8("nonanimation_tree"))
        self.nonanimation_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.nonanimation_tree.headerItem().setFont(0, font)
        self.nonanimation_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.nonanimation_tree.headerItem().setFont(1, font)
        self.verticalLayout_5.addWidget(self.nonanimation_tree)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.camera_ck = QtGui.QCheckBox(Form)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camera_ck.setFont(font)
        self.camera_ck.setObjectName(_fromUtf8("camera_ck"))
        self.horizontalLayout_2.addWidget(self.camera_ck)
        self.shot_ck = QtGui.QCheckBox(Form)
        self.shot_ck.setObjectName(_fromUtf8("shot_ck"))
        self.horizontalLayout_2.addWidget(self.shot_ck)

        self.scale_ck = QtGui.QCheckBox(Form)
        self.scale_ck.setObjectName(_fromUtf8("scale_ck"))
        self.horizontalLayout_2.addWidget(self.scale_ck)

        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.camera_selbtn = QtGui.QPushButton(Form)
        self.camera_selbtn.setMinimumSize(QtCore.QSize(150, 30))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camera_selbtn.setFont(font)
        self.camera_selbtn.setObjectName(_fromUtf8("camera_selbtn"))
        self.horizontalLayout_2.addWidget(self.camera_selbtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.camera_tree = QtGui.QTreeWidget(Form)
        self.camera_tree.setMinimumSize(QtCore.QSize(0, 0))
        self.camera_tree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camera_tree.setObjectName(_fromUtf8("camera_tree"))
        self.camera_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.camera_tree.headerItem().setFont(0, font)
        self.camera_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.camera_tree.headerItem().setFont(1, font)
        self.camera_tree.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.camera_tree.headerItem().setFont(2, font)
        self.camera_tree.headerItem().setTextAlignment(3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.camera_tree.headerItem().setFont(3, font)
        self.verticalLayout_2.addWidget(self.camera_tree)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dir_txt = QtGui.QLineEdit(Form)
        self.dir_txt.setMinimumSize(QtCore.QSize(0, 30))
        self.dir_txt.setObjectName(_fromUtf8("dir_txt"))
        self.horizontalLayout_3.addWidget(self.dir_txt)
        self.open_btn = QtGui.QToolButton(Form)
        self.open_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.open_btn.setObjectName(_fromUtf8("open_btn"))
        self.horizontalLayout_3.addWidget(self.open_btn)
        self.fbx_btn = QtGui.QPushButton(Form)
        self.fbx_btn.setMinimumSize(QtCore.QSize(150, 30))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fbx_btn.setFont(font)
        self.fbx_btn.setObjectName(_fromUtf8("fbx_btn"))
        self.horizontalLayout_3.addWidget(self.fbx_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Unreal Fbx Export (Character, Camera)", None))
        self.animation_ck.setText(_translate("Form", "Animation", None))
        self.label.setText(_translate("Form", "[ model_GRP, skinJoint_GRP ]", None))
        self.animation_selbtn.setText(_translate("Form", "Select", None))
        self.animation_tree.headerItem().setText(0, _translate("Form", "Node Name", None))
        self.animation_tree.headerItem().setText(1, _translate("Form", "Start", None))
        self.animation_tree.headerItem().setText(2, _translate("Form", "End", None))
        self.animation_tree.headerItem().setText(3, _translate("Form", "Fbx File Name", None))
        self.nonanimation_ck.setText(_translate("Form", "NonAnimation", None))
        self.nonanimation_selbtn.setText(_translate("Form", "Select", None))
        self.nonanimation_tree.headerItem().setText(0, _translate("Form", "Node Name", None))
        self.nonanimation_tree.headerItem().setText(1, _translate("Form", "Fbx File Name", None))
        self.camera_ck.setText(_translate("Form", "Camera", None))
        self.shot_ck.setText(_translate("Form", "Shot", None))
        self.scale_ck.setText(_translate("Form", "10X", None))
        self.camera_selbtn.setText(_translate("Form", "Select", None))
        self.camera_tree.headerItem().setText(0, _translate("Form", "Camera Name", None))
        self.camera_tree.headerItem().setText(1, _translate("Form", "Start", None))
        self.camera_tree.headerItem().setText(2, _translate("Form", "End", None))
        self.camera_tree.headerItem().setText(3, _translate("Form", "Fbx File Name", None))
        self.fbx_btn.setText(_translate("Form", "FBX Export", None))

