from PySide2 import QtWidgets, QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_shotform(object):
    def setupUi(self, shotform):
        shotform.setObjectName(_fromUtf8("shotform"))
        shotform.setGeometry(QtCore.QRect(400, 200, 1200, 538))
        shotform.resize(1200, 538)
        self.gridLayout_2 = QtWidgets.QGridLayout(shotform)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.resetbtn = QtWidgets.QPushButton(shotform)
        self.resetbtn.setMinimumSize(QtCore.QSize(100, 30))
        self.resetbtn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resetbtn.setFont(font)
        self.resetbtn.setObjectName(_fromUtf8("resetbtn"))
        self.horizontalLayout_3.addWidget(self.resetbtn)
        self.endbtn = QtWidgets.QPushButton(shotform)
        self.endbtn.setMinimumSize(QtCore.QSize(100, 30))
        self.endbtn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.endbtn.setFont(font)
        self.endbtn.setObjectName(_fromUtf8("endbtn"))
        self.horizontalLayout_3.addWidget(self.endbtn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addshotbtn = QtWidgets.QPushButton(shotform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addshotbtn.sizePolicy().hasHeightForWidth())
        self.addshotbtn.setSizePolicy(sizePolicy)
        self.addshotbtn.setMinimumSize(QtCore.QSize(25, 25))
        self.addshotbtn.setMaximumSize(QtCore.QSize(25, 25))
        font =QtGui.QFont()
        font.setPointSize(12)
        self.addshotbtn.setFont(font)
        self.addshotbtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addshotbtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.addshotbtn.setObjectName(_fromUtf8("addshotbtn"))
        self.horizontalLayout.addWidget(self.addshotbtn)
        self.minusshotbtn = QtWidgets.QPushButton(shotform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minusshotbtn.sizePolicy().hasHeightForWidth())
        self.minusshotbtn.setSizePolicy(sizePolicy)
        self.minusshotbtn.setMinimumSize(QtCore.QSize(25, 25))
        self.minusshotbtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minusshotbtn.setFont(font)
        self.minusshotbtn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.minusshotbtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.minusshotbtn.setObjectName(_fromUtf8("minusshotbtn"))
        self.horizontalLayout.addWidget(self.minusshotbtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtWidgets.QLabel(shotform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(shotform)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.shotnum = QtWidgets.QLabel(shotform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shotnum.setFont(font)
        self.shotnum.setObjectName(_fromUtf8("shotnum"))
        self.horizontalLayout_2.addWidget(self.shotnum)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.shotmain = QtWidgets.QTreeWidget(shotform)
        self.shotmain.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)  #### #multi selection ctrl+
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shotmain.setFont(font)
        self.shotmain.setObjectName(_fromUtf8("shotmain"))
        self.shotmain.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(3, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(4, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(5, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.headerItem().setTextAlignment(6, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.shotmain.header().setHighlightSections(False)
        self.gridLayout.addWidget(self.shotmain, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(shotform)
        QtCore.QMetaObject.connectSlotsByName(shotform)

    def retranslateUi(self, shotform):
        shotform.setWindowTitle(_translate("shotform", "Shot Sequencer Editor by RND youkyoung.kim", None))
        self.resetbtn.setText(_translate("shotform", "ReLoad", None))
        self.endbtn.setText(_translate("shotform", "End", None))
        self.addshotbtn.setText(_translate("shotform", "+", None))
        self.minusshotbtn.setText(_translate("shotform", "-", None))
        self.label.setText(_translate("shotform", "Shot Number", None))
        self.shotnum.setText(_translate("shotform", "TextLabel", None))
        self.shotmain.headerItem().setText(0, _translate("shotform", "Shot", None))
        self.shotmain.headerItem().setText(1, _translate("shotform", "Camera", None))
        self.shotmain.headerItem().setText(2, _translate("shotform", "Shot Name", None))
        self.shotmain.headerItem().setText(3, _translate("shotform", "Start", None))
        self.shotmain.headerItem().setText(4, _translate("shotform", "End ", None))
        self.shotmain.headerItem().setText(5, _translate("shotform", "Track", None))
        self.shotmain.headerItem().setText(6, _translate("shotform", "Scale", None))
