# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxrunner.ui'
#
# Created: Tue Nov  3 15:45:22 2020
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import os

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

currentFile = os.path.dirname(__file__)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(767, 927)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.showEdit = QtGui.QLineEdit(Form)
        self.showEdit.setEnabled(False)
        self.showEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.showEdit.setObjectName(_fromUtf8("showEdit"))
        self.horizontalLayout.addWidget(self.showEdit)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.shotEdit = QtGui.QLineEdit(Form)
        self.shotEdit.setEnabled(False)
        self.shotEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.shotEdit.setObjectName(_fromUtf8("shotEdit"))
        self.horizontalLayout.addWidget(self.shotEdit)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.contextEdit = QtGui.QLineEdit(Form)
        self.contextEdit.setReadOnly(True)
        self.contextEdit.setObjectName(_fromUtf8("contextEdit"))
        self.horizontalLayout.addWidget(self.contextEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.previousBtn = QtGui.QPushButton(Form)
        self.previousBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.previousBtn.setObjectName(_fromUtf8("previousBtn"))
        self.horizontalLayout_2.addWidget(self.previousBtn)
        self.nextBtn = QtGui.QPushButton(Form)
        self.nextBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_2.addWidget(self.nextBtn)
        self.directoryEdit = QtGui.QLineEdit(Form)
        self.directoryEdit.setObjectName(_fromUtf8("directoryEdit"))
        self.horizontalLayout_2.addWidget(self.directoryEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.fileBrowserTreeWidget = QtGui.QTreeWidget(Form)
        self.fileBrowserTreeWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.fileBrowserTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileBrowserTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileBrowserTreeWidget.setRootIsDecorated(False)
        self.fileBrowserTreeWidget.setObjectName(_fromUtf8("fileBrowserTreeWidget"))
        self.fileBrowserTreeWidget.header().setDefaultSectionSize(50)
        self.fileBrowserTreeWidget.header().resizeSection(0, 430)
        self.verticalLayout_2.addWidget(self.fileBrowserTreeWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.devGroupBox = QtGui.QGroupBox(Form)
        self.devGroupBox.setTitle(_fromUtf8(""))
        self.devGroupBox.setObjectName(_fromUtf8("devGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.devGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.devGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.devFileMakeBtn = QtGui.QPushButton(self.devGroupBox)
        self.devFileMakeBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.devFileMakeBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.devFileMakeBtn.setObjectName(_fromUtf8("devFileMakeBtn"))
        self.gridLayout.addWidget(self.devFileMakeBtn, 0, 2, 1, 1)
        self.devOpenDirBtn = QtGui.QPushButton(self.devGroupBox)
        self.devOpenDirBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.devOpenDirBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.devOpenDirBtn.setIcon(QtGui.QIcon('%s/directory.png' % currentFile))
        self.devOpenDirBtn.setText(_fromUtf8(""))
        self.devOpenDirBtn.setObjectName(_fromUtf8("devOpenDirBtn"))
        self.gridLayout.addWidget(self.devOpenDirBtn, 0, 1, 1, 1)
        self.devTreeWidget = QtGui.QTreeWidget(self.devGroupBox)
        self.devTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.devTreeWidget.setObjectName(_fromUtf8("devTreeWidget"))
        self.devTreeWidget.header().setVisible(False)
        self.devTreeWidget.header().setDefaultSectionSize(50)
        self.devTreeWidget.header().resizeSection(0, 250)
        self.devTreeWidget.setRootIsDecorated(False)
        self.gridLayout.addWidget(self.devTreeWidget, 1, 0, 1, 3)
        self.horizontalLayout_3.addWidget(self.devGroupBox)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_3.addWidget(self.line_3)
        self.pubGroupBox = QtGui.QGroupBox(Form)
        self.pubGroupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.pubGroupBox.setTitle(_fromUtf8(""))
        self.pubGroupBox.setObjectName(_fromUtf8("pubGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pubGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pubFileMakeBtn = QtGui.QPushButton(self.pubGroupBox)
        self.pubFileMakeBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.pubFileMakeBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.pubFileMakeBtn.setObjectName(_fromUtf8("pubFileMakeBtn"))
        self.gridLayout_2.addWidget(self.pubFileMakeBtn, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.pubGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.pubOpenDirBtn = QtGui.QPushButton(self.pubGroupBox)
        self.pubOpenDirBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.pubOpenDirBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.pubOpenDirBtn.setIcon(QtGui.QIcon('%s/directory.png' % currentFile))
        self.pubOpenDirBtn.setText(_fromUtf8(""))
        self.pubOpenDirBtn.setObjectName(_fromUtf8("pubOpenDirBtn"))
        self.gridLayout_2.addWidget(self.pubOpenDirBtn, 0, 1, 1, 1)
        self.pubTreeWidget = QtGui.QTreeWidget(self.pubGroupBox)
        self.pubTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pubTreeWidget.setObjectName(_fromUtf8("pubTreeWidget"))
        self.pubTreeWidget.header().setVisible(False)
        self.pubTreeWidget.header().setDefaultSectionSize(50)
        self.pubTreeWidget.header().resizeSection(0, 250)
        self.pubTreeWidget.setRootIsDecorated(False)
        self.gridLayout_2.addWidget(self.pubTreeWidget, 1, 0, 1, 3)
        self.horizontalLayout_3.addWidget(self.pubGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.dccListWidget = QtGui.QListWidget(Form)
        self.dccListWidget.setIconSize(QtCore.QSize(48, 48))
        self.dccListWidget.setViewMode(QtGui.QListView.IconMode)
        self.dccListWidget.setObjectName(_fromUtf8("dccListWidget"))
        self.verticalLayout.addWidget(self.dccListWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Show", None))
        self.showEdit.setText(_translate("Form", "prat2", None))
        self.label_3.setText(_translate("Form", "Shot", None))
        self.shotEdit.setText(_translate("Form", "SEQ_0010", None))
        self.label_5.setText(_translate("Form", "Context", None))
        self.nextBtn.setText(_translate("Form", ">", None))
        self.previousBtn.setText(_translate("Form", "<", None))
        self.fileBrowserTreeWidget.headerItem().setText(0, _translate("Form", "Name", None))
        self.fileBrowserTreeWidget.headerItem().setText(1, _translate("Form", "Modified", None))
        self.fileBrowserTreeWidget.headerItem().setText(2, _translate("Form", "Type", None))
        self.fileBrowserTreeWidget.headerItem().setText(3, _translate("Form", "Size", None))
        self.label_2.setText(_translate("Form", "Dev", None))
        self.devFileMakeBtn.setText(_translate("Form", "+", None))
        self.devTreeWidget.headerItem().setText(0, _translate("Form", "1", None))
        self.devTreeWidget.headerItem().setText(1, _translate("Form", "New Column", None))
        self.pubFileMakeBtn.setText(_translate("Form", "+", None))
        self.label_4.setText(_translate("Form", "Pub", None))
        self.pubTreeWidget.headerItem().setText(0, _translate("Form", "1", None))
        self.pubTreeWidget.headerItem().setText(1, _translate("Form", "New Column", None))

