# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotkey.ui'
#
# Created: Thu Aug 23 14:37:16 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtWidgets, QtCore

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 529)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(650, 0))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_88 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_88.setGeometry(QtCore.QRect(440, 350, 50, 40))
        self.pushButton_88.setObjectName("pushButton_88")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_35.setGeometry(QtCore.QRect(320, 130, 40, 40))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_72 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_72.setGeometry(QtCore.QRect(420, 250, 40, 40))
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_45 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_45.setGeometry(QtCore.QRect(170, 170, 40, 40))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_28.setGeometry(QtCore.QRect(20, 130, 60, 40))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_73 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_73.setGeometry(QtCore.QRect(460, 250, 40, 40))
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_80 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_80.setGeometry(QtCore.QRect(500, 350, 40, 40))
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_51.setGeometry(QtCore.QRect(410, 170, 40, 40))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_40.setGeometry(QtCore.QRect(520, 130, 40, 40))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_85 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_85.setGeometry(QtCore.QRect(440, 310, 50, 40))
        self.pushButton_85.setObjectName("pushButton_85")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_27.setGeometry(QtCore.QRect(540, 90, 80, 40))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_57 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_57.setGeometry(QtCore.QRect(150, 210, 40, 40))
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_37.setGeometry(QtCore.QRect(400, 130, 40, 40))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_84 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_84.setGeometry(QtCore.QRect(390, 310, 50, 40))
        self.pushButton_84.setObjectName("pushButton_84")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setGeometry(QtCore.QRect(180, 90, 40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_36.setGeometry(QtCore.QRect(360, 130, 40, 40))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_46.setGeometry(QtCore.QRect(210, 170, 40, 40))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 30, 40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_41.setGeometry(QtCore.QRect(560, 130, 60, 40))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_29.setGeometry(QtCore.QRect(80, 130, 40, 40))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_67 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_67.setGeometry(QtCore.QRect(20, 250, 50, 40))
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(580, 30, 40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 30, 40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_74 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_74.setGeometry(QtCore.QRect(500, 250, 40, 40))
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_52 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_52.setGeometry(QtCore.QRect(450, 170, 40, 40))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_86 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_86.setGeometry(QtCore.QRect(340, 350, 50, 40))
        self.pushButton_86.setObjectName("pushButton_86")
        self.pushButton_64 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_64.setGeometry(QtCore.QRect(430, 210, 40, 40))
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_58 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_58.setGeometry(QtCore.QRect(190, 210, 40, 40))
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 30, 40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 90, 40, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_63 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_63.setGeometry(QtCore.QRect(390, 210, 40, 40))
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(60, 90, 40, 40))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_47.setGeometry(QtCore.QRect(250, 170, 40, 40))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_42.setGeometry(QtCore.QRect(20, 170, 70, 40))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(390, 30, 40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_23.setGeometry(QtCore.QRect(380, 90, 40, 40))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_83 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_83.setGeometry(QtCore.QRect(340, 310, 50, 40))
        self.pushButton_83.setObjectName("pushButton_83")
        self.pushButton_75 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_75.setGeometry(QtCore.QRect(540, 250, 40, 40))
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_53.setGeometry(QtCore.QRect(490, 170, 40, 40))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_32.setGeometry(QtCore.QRect(200, 130, 40, 40))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 30, 40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_59 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_59.setGeometry(QtCore.QRect(230, 210, 40, 40))
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 90, 40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_69 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_69.setGeometry(QtCore.QRect(120, 250, 50, 40))
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setGeometry(QtCore.QRect(260, 90, 40, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_48.setGeometry(QtCore.QRect(290, 170, 40, 40))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_79 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_79.setGeometry(QtCore.QRect(540, 310, 40, 40))
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(460, 30, 40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_24.setGeometry(QtCore.QRect(420, 90, 40, 40))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_31.setGeometry(QtCore.QRect(160, 130, 40, 40))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_76 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_76.setGeometry(QtCore.QRect(580, 250, 40, 40))
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_54.setGeometry(QtCore.QRect(530, 170, 91, 40))
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_33.setGeometry(QtCore.QRect(240, 130, 40, 40))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_60 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_60.setGeometry(QtCore.QRect(270, 210, 40, 40))
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_70 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_70.setGeometry(QtCore.QRect(170, 250, 50, 40))
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_66 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_66.setGeometry(QtCore.QRect(510, 210, 110, 40))
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_43.setGeometry(QtCore.QRect(90, 170, 40, 40))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_82 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_82.setGeometry(QtCore.QRect(580, 350, 40, 40))
        self.pushButton_82.setObjectName("pushButton_82")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setGeometry(QtCore.QRect(300, 90, 40, 40))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_68 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_68.setGeometry(QtCore.QRect(70, 250, 50, 40))
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_49.setGeometry(QtCore.QRect(330, 170, 40, 40))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_38.setGeometry(QtCore.QRect(440, 130, 40, 40))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_81 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_81.setGeometry(QtCore.QRect(540, 350, 40, 40))
        self.pushButton_81.setObjectName("pushButton_81")
        self.pushButton_65 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_65.setGeometry(QtCore.QRect(470, 210, 40, 40))
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(500, 30, 40, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_25.setGeometry(QtCore.QRect(460, 90, 40, 40))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setGeometry(QtCore.QRect(140, 90, 40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_55 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_55.setGeometry(QtCore.QRect(20, 210, 90, 40))
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_30.setGeometry(QtCore.QRect(120, 130, 40, 40))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 30, 40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_34.setGeometry(QtCore.QRect(280, 130, 40, 40))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_61 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_61.setGeometry(QtCore.QRect(310, 210, 40, 40))
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 30, 40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_71 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_71.setGeometry(QtCore.QRect(220, 250, 201, 40))
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_44.setGeometry(QtCore.QRect(130, 170, 40, 40))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(100, 90, 40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_22.setGeometry(QtCore.QRect(340, 90, 40, 40))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_87 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_87.setGeometry(QtCore.QRect(390, 350, 50, 40))
        self.pushButton_87.setObjectName("pushButton_87")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_50.setGeometry(QtCore.QRect(370, 170, 40, 40))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_39.setGeometry(QtCore.QRect(480, 130, 40, 40))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(540, 30, 40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_26.setGeometry(QtCore.QRect(500, 90, 40, 40))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_62 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_62.setGeometry(QtCore.QRect(350, 210, 40, 40))
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_56 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_56.setGeometry(QtCore.QRect(110, 210, 40, 40))
        self.pushButton_56.setObjectName("pushButton_56")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 310, 120, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(150, 310, 181, 80))
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 340, 91, 17))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 0, 2, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_6.addWidget(self.lineEdit_2, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 3, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 3)
        self.pushButton_77 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_77.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_77.setObjectName("pushButton_77")
        self.gridLayout_5.addWidget(self.pushButton_77, 1, 0, 1, 2)
        self.pushButton_78 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_78.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_78.setObjectName("pushButton_78")
        self.gridLayout_5.addWidget(self.pushButton_78, 1, 2, 1, 1)
        self.pushButton_89 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_89.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_89.setObjectName("pushButton_89")
        self.gridLayout_5.addWidget(self.pushButton_89, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.pushButton_90 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_90.setObjectName("pushButton_90")
        self.gridLayout_5.addWidget(self.pushButton_90, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(117, 299, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 4, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 4, 2, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget.setObjectName("treeWidget")
        #self.treeWidget.header().setDefaultSectionSize(300)
        self.gridLayout_6.addWidget(self.treeWidget, 1, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.treeWidget.header().resizeSection(0, 300)
        self.treeWidget.header().resizeSection(1, 200)

        self.pushButton_77.setCheckable(True)
        self.pushButton_78.setCheckable(True)
        self.pushButton_89.setCheckable(True)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        version = '0.10'
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Hotkey helper " + version + " By Tae Hyung Lee, Dexter Digital", None))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Main Focus", None))
        self.checkBox.setText(QtWidgets.QApplication.translate("Form", "Nuke", None))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("Form", "Nodes", None))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "Viewer Focus", None))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("Form", "Viewer", None))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Keyboard", None))
        self.pushButton_88.setText(QtWidgets.QApplication.translate("Form", "Page\n"
"Down", None))
        self.pushButton_35.setText(QtWidgets.QApplication.translate("Form", "U", None))
        self.pushButton_72.setText(QtWidgets.QApplication.translate("Form", "한/영", None))
        self.pushButton_45.setText(QtWidgets.QApplication.translate("Form", "D", None))
        self.pushButton_28.setText(QtWidgets.QApplication.translate("Form", "Tab", None))
        self.pushButton_73.setText(QtWidgets.QApplication.translate("Form", "Alt", None))
        self.pushButton_80.setText(QtWidgets.QApplication.translate("Form", "←", None))
        self.pushButton_51.setText(QtWidgets.QApplication.translate("Form", "L", None))
        self.pushButton_40.setText(QtWidgets.QApplication.translate("Form", "]", None))
        self.pushButton_85.setText(QtWidgets.QApplication.translate("Form", "Page\n"
"Up", None))
        self.pushButton_27.setText(QtWidgets.QApplication.translate("Form", "Backspace", None))
        self.pushButton_57.setText(QtWidgets.QApplication.translate("Form", "X", None))
        self.pushButton_37.setText(QtWidgets.QApplication.translate("Form", "O", None))
        self.pushButton_84.setText(QtWidgets.QApplication.translate("Form", "Home", None))
        self.pushButton_18.setText(QtWidgets.QApplication.translate("Form", "4", None))
        self.pushButton_36.setText(QtWidgets.QApplication.translate("Form", "I", None))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Form", "F2", None))
        self.pushButton_46.setText(QtWidgets.QApplication.translate("Form", "F", None))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Form", "F1", None))
        self.pushButton_41.setText(QtWidgets.QApplication.translate("Form", "\\", None))
        self.pushButton_29.setText(QtWidgets.QApplication.translate("Form", "Q", None))
        self.pushButton_67.setText(QtWidgets.QApplication.translate("Form", "Ctrl", None))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("Form", "F12", None))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("Form", "F7", None))
        self.pushButton_74.setText(QtWidgets.QApplication.translate("Form", "Win", None))
        self.pushButton_52.setText(QtWidgets.QApplication.translate("Form", ";", None))
        self.pushButton_86.setText(QtWidgets.QApplication.translate("Form", "Delete", None))
        self.pushButton_64.setText(QtWidgets.QApplication.translate("Form", ".", None))
        self.pushButton_58.setText(QtWidgets.QApplication.translate("Form", "C", None))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("Form", "F4", None))
        self.pushButton_19.setText(QtWidgets.QApplication.translate("Form", "5", None))
        self.pushButton_63.setText(QtWidgets.QApplication.translate("Form", ",", None))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("Form", "1", None))
        self.pushButton_47.setText(QtWidgets.QApplication.translate("Form", "G", None))
        self.pushButton_42.setText(QtWidgets.QApplication.translate("Form", "Caps\n"
"Lock", None))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("Form", "F8", None))
        self.pushButton_23.setText(QtWidgets.QApplication.translate("Form", "9", None))
        self.pushButton_83.setText(QtWidgets.QApplication.translate("Form", "Insert", None))
        self.pushButton_75.setText(QtWidgets.QApplication.translate("Form", "Win", None))
        self.pushButton_53.setText(QtWidgets.QApplication.translate("Form", "\'", None))
        self.pushButton_32.setText(QtWidgets.QApplication.translate("Form", "R", None))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("Form", "F6", None))
        self.pushButton_59.setText(QtWidgets.QApplication.translate("Form", "V", None))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("Form", "`", None))
        self.pushButton_69.setText(QtWidgets.QApplication.translate("Form", "Alt", None))
        self.pushButton_20.setText(QtWidgets.QApplication.translate("Form", "6", None))
        self.pushButton_48.setText(QtWidgets.QApplication.translate("Form", "H", None))
        self.pushButton_79.setText(QtWidgets.QApplication.translate("Form", "↑", None))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("Form", "F9", None))
        self.pushButton_24.setText(QtWidgets.QApplication.translate("Form", "0", None))
        self.pushButton_31.setText(QtWidgets.QApplication.translate("Form", "E", None))
        self.pushButton_76.setText(QtWidgets.QApplication.translate("Form", "Ctrl", None))
        self.pushButton_54.setText(QtWidgets.QApplication.translate("Form", "Enter", None))
        self.pushButton_33.setText(QtWidgets.QApplication.translate("Form", "T", None))
        self.pushButton_60.setText(QtWidgets.QApplication.translate("Form", "B", None))
        self.pushButton_70.setText(QtWidgets.QApplication.translate("Form", "한자", None))
        self.pushButton_66.setText(QtWidgets.QApplication.translate("Form", "Shift", None))
        self.pushButton_43.setText(QtWidgets.QApplication.translate("Form", "A", None))
        self.pushButton_82.setText(QtWidgets.QApplication.translate("Form", "→", None))
        self.pushButton_21.setText(QtWidgets.QApplication.translate("Form", "7", None))
        self.pushButton_68.setText(QtWidgets.QApplication.translate("Form", "Win", None))
        self.pushButton_49.setText(QtWidgets.QApplication.translate("Form", "J", None))
        self.pushButton_38.setText(QtWidgets.QApplication.translate("Form", "P", None))
        self.pushButton_81.setText(QtWidgets.QApplication.translate("Form", "↓", None))
        self.pushButton_65.setText(QtWidgets.QApplication.translate("Form", "/", None))
        self.pushButton_11.setText(QtWidgets.QApplication.translate("Form", "F10", None))
        self.pushButton_25.setText(QtWidgets.QApplication.translate("Form", "-", None))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("Form", "3", None))
        self.pushButton_55.setText(QtWidgets.QApplication.translate("Form", "Shift", None))
        self.pushButton_30.setText(QtWidgets.QApplication.translate("Form", "W", None))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("Form", "F5", None))
        self.pushButton_34.setText(QtWidgets.QApplication.translate("Form", "Y", None))
        self.pushButton_61.setText(QtWidgets.QApplication.translate("Form", "N", None))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Form", "F3", None))
        self.pushButton_71.setText(QtWidgets.QApplication.translate("Form", "Space", None))
        self.pushButton_44.setText(QtWidgets.QApplication.translate("Form", "S", None))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("Form", "2", None))
        self.pushButton_22.setText(QtWidgets.QApplication.translate("Form", "8", None))
        self.pushButton_87.setText(QtWidgets.QApplication.translate("Form", "End", None))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Esc", None))
        self.pushButton_50.setText(QtWidgets.QApplication.translate("Form", "K", None))
        self.pushButton_39.setText(QtWidgets.QApplication.translate("Form", "[", None))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("Form", "F11", None))
        self.pushButton_26.setText(QtWidgets.QApplication.translate("Form", "=", None))
        self.pushButton_62.setText(QtWidgets.QApplication.translate("Form", "M", None))
        self.pushButton_56.setText(QtWidgets.QApplication.translate("Form", "Z", None))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Search Here!!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Hot Key List", None))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Search", None))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("Form", "Assign Hotkey", None))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Command : ", None))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "", None))
        self.pushButton_77.setText(QtWidgets.QApplication.translate("Form", "Shift", None))
        self.pushButton_78.setText(QtWidgets.QApplication.translate("Form", "Ctrl", None))
        self.pushButton_89.setText(QtWidgets.QApplication.translate("Form", "Alt", None))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Key : ", None))
        self.pushButton_90.setText(QtWidgets.QApplication.translate("Form", "Save", None))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Form", "All hotkey item", None))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("Form", "Type", None))
        self.treeWidget.headerItem().setText(2, QtWidgets.QApplication.translate("Form", "Hotkey", None))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Name", None))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Hotkey", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Assign Hotkey", None))
