# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renderManRIS_option_v01.ui'
#
# Created: Fri Sep  8 21:57:45 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

import Qt
import Qt.QtWidgets as QtGui
import Qt.QtCore as QtCore

# from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(675, 237)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.renderOptMainFrame = QtGui.QFrame(Form)
        self.renderOptMainFrame.setEnabled(True)
        self.renderOptMainFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.renderOptMainFrame.setFrameShape(QtGui.QFrame.Box)
        self.renderOptMainFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.renderOptMainFrame.setObjectName(_fromUtf8("renderOptMainFrame"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.renderOptMainFrame)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.renderOptLayout = QtGui.QHBoxLayout()
        self.renderOptLayout.setSpacing(0)
        self.renderOptLayout.setObjectName(_fromUtf8("renderOptLayout"))
        self.renderOptOuterFrame = QtGui.QFrame(self.renderOptMainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderOptOuterFrame.sizePolicy().hasHeightForWidth())
        self.renderOptOuterFrame.setSizePolicy(sizePolicy)
        self.renderOptOuterFrame.setMinimumSize(QtCore.QSize(100, 48))
        self.renderOptOuterFrame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.renderOptOuterFrame.setAutoFillBackground(False)
        self.renderOptOuterFrame.setStyleSheet(_fromUtf8("QFrame { background-color:rgb(150,150,150); }"))
        self.renderOptOuterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderOptOuterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderOptOuterFrame.setObjectName(_fromUtf8("renderOptOuterFrame"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.renderOptOuterFrame)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.renderOptRenderManLabel = QtGui.QLabel(self.renderOptOuterFrame)
        self.renderOptRenderManLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.renderOptRenderManLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.renderOptRenderManLabel.setFont(font)
        self.renderOptRenderManLabel.setAcceptDrops(True)
        self.renderOptRenderManLabel.setAutoFillBackground(False)
        self.renderOptRenderManLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(96,96,96);                       color: rgb(222,222,222); }"))
        self.renderOptRenderManLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.renderOptRenderManLabel.setObjectName(_fromUtf8("renderOptRenderManLabel"))
        self.verticalLayout_12.addWidget(self.renderOptRenderManLabel)
        self.renderOptLabel = QtGui.QLabel(self.renderOptOuterFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderOptLabel.sizePolicy().hasHeightForWidth())
        self.renderOptLabel.setSizePolicy(sizePolicy)
        self.renderOptLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.renderOptLabel.setFont(font)
        self.renderOptLabel.setAcceptDrops(True)
        self.renderOptLabel.setAutoFillBackground(False)
        self.renderOptLabel.setStyleSheet(_fromUtf8("QLabel {      color: rgb(22,22,22); }"))
        self.renderOptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.renderOptLabel.setObjectName(_fromUtf8("renderOptLabel"))
        self.verticalLayout_12.addWidget(self.renderOptLabel)
        self.renderOptLayout.addWidget(self.renderOptOuterFrame)
        self.renderOptFrame = QtGui.QFrame(self.renderOptMainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderOptFrame.sizePolicy().hasHeightForWidth())
        self.renderOptFrame.setSizePolicy(sizePolicy)
        self.renderOptFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderOptFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.renderOptFrame.setObjectName(_fromUtf8("renderOptFrame"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.renderOptFrame)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setMargin(1)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.shutterAngle_label = QtGui.QLabel(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutterAngle_label.sizePolicy().hasHeightForWidth())
        self.shutterAngle_label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.shutterAngle_label.setFont(font)
        self.shutterAngle_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shutterAngle_label.setObjectName(_fromUtf8("shutterAngle_label"))
        self.gridLayout.addWidget(self.shutterAngle_label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.renderOptFrame)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.minSamples_spinBox = QtGui.QSpinBox(self.renderOptFrame)
        self.minSamples_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.minSamples_spinBox.setFont(font)
        self.minSamples_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.minSamples_spinBox.setMaximum(2048)
        self.minSamples_spinBox.setObjectName(_fromUtf8("minSamples_spinBox"))
        self.gridLayout.addWidget(self.minSamples_spinBox, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.minmaxSamples_label = QtGui.QLabel(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minmaxSamples_label.sizePolicy().hasHeightForWidth())
        self.minmaxSamples_label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.minmaxSamples_label.setFont(font)
        self.minmaxSamples_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minmaxSamples_label.setObjectName(_fromUtf8("minmaxSamples_label"))
        self.gridLayout.addWidget(self.minmaxSamples_label, 1, 0, 1, 1)
        self.ribgenLimit_label = QtGui.QLabel(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ribgenLimit_label.sizePolicy().hasHeightForWidth())
        self.ribgenLimit_label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.ribgenLimit_label.setFont(font)
        self.ribgenLimit_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ribgenLimit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ribgenLimit_label.setObjectName(_fromUtf8("ribgenLimit_label"))
        self.gridLayout.addWidget(self.ribgenLimit_label, 0, 0, 1, 1)
        self.denoise_label = QtGui.QLabel(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denoise_label.sizePolicy().hasHeightForWidth())
        self.denoise_label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.denoise_label.setFont(font)
        self.denoise_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.denoise_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.denoise_label.setObjectName(_fromUtf8("denoise_label"))
        self.gridLayout.addWidget(self.denoise_label, 5, 0, 1, 1)
        self.incremental_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incremental_checkBox.sizePolicy().hasHeightForWidth())
        self.incremental_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.incremental_checkBox.setFont(font)
        self.incremental_checkBox.setObjectName(_fromUtf8("incremental_checkBox"))
        self.gridLayout.addWidget(self.incremental_checkBox, 4, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.checkPoint_spinBox = QtGui.QSpinBox(self.renderOptFrame)
        self.checkPoint_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.checkPoint_spinBox.setFont(font)
        self.checkPoint_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.checkPoint_spinBox.setMaximum(120)
        self.checkPoint_spinBox.setObjectName(_fromUtf8("checkPoint_spinBox"))
        self.gridLayout.addWidget(self.checkPoint_spinBox, 4, 2, 1, 1)
        self.denoise_aov_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denoise_aov_checkBox.sizePolicy().hasHeightForWidth())
        self.denoise_aov_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.denoise_aov_checkBox.setFont(font)
        self.denoise_aov_checkBox.setObjectName(_fromUtf8("denoise_aov_checkBox"))
        self.gridLayout.addWidget(self.denoise_aov_checkBox, 5, 4, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.denoise_strength_label = QtGui.QLabel(self.renderOptFrame)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.denoise_strength_label.setFont(font)
        self.denoise_strength_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.denoise_strength_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.denoise_strength_label.setObjectName(_fromUtf8("denoise_strength_label"))
        self.horizontalLayout.addWidget(self.denoise_strength_label)
        self.denoise_strength = QtGui.QDoubleSpinBox(self.renderOptFrame)
        self.denoise_strength.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.denoise_strength.setDecimals(1)
        self.denoise_strength.setMinimum(0.1)
        self.denoise_strength.setMaximum(1.0)
        self.denoise_strength.setSingleStep(0.1)
        self.denoise_strength.setProperty("value", 0.2)
        self.denoise_strength.setObjectName(_fromUtf8("denoise_strength"))
        self.horizontalLayout.addWidget(self.denoise_strength)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 5, 1, 1)
        self.ribgenLimit_spinBox = QtGui.QSpinBox(self.renderOptFrame)
        self.ribgenLimit_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.ribgenLimit_spinBox.setFont(font)
        self.ribgenLimit_spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ribgenLimit_spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ribgenLimit_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.ribgenLimit_spinBox.setMinimum(1)
        self.ribgenLimit_spinBox.setMaximum(20)
        self.ribgenLimit_spinBox.setObjectName(_fromUtf8("ribgenLimit_spinBox"))
        self.gridLayout.addWidget(self.ribgenLimit_spinBox, 0, 2, 1, 1)
        self.denoise_comboBox = QtGui.QComboBox(self.renderOptFrame)
        self.denoise_comboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.denoise_comboBox.setFont(font)
        self.denoise_comboBox.setObjectName(_fromUtf8("denoise_comboBox"))
        self.denoise_comboBox.addItem(_fromUtf8(""))
        self.denoise_comboBox.addItem(_fromUtf8(""))
        self.denoise_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.denoise_comboBox, 5, 2, 1, 1)
        self.maxSamples_spinBox = QtGui.QSpinBox(self.renderOptFrame)
        self.maxSamples_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.maxSamples_spinBox.setFont(font)
        self.maxSamples_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.maxSamples_spinBox.setMaximum(2048)
        self.maxSamples_spinBox.setObjectName(_fromUtf8("maxSamples_spinBox"))
        self.gridLayout.addWidget(self.maxSamples_spinBox, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.shutterAngle_spinBox = QtGui.QSpinBox(self.renderOptFrame)
        self.shutterAngle_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.shutterAngle_spinBox.setFont(font)
        self.shutterAngle_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.shutterAngle_spinBox.setMaximum(360)
        self.shutterAngle_spinBox.setSingleStep(10)
        self.shutterAngle_spinBox.setObjectName(_fromUtf8("shutterAngle_spinBox"))
        self.gridLayout.addWidget(self.shutterAngle_spinBox, 2, 2, 1, 1)
        self.motionBlur_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motionBlur_checkBox.sizePolicy().hasHeightForWidth())
        self.motionBlur_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.motionBlur_checkBox.setFont(font)
        self.motionBlur_checkBox.setObjectName(_fromUtf8("motionBlur_checkBox"))
        self.gridLayout.addWidget(self.motionBlur_checkBox, 3, 2, 1, 1)
        self.cameraBlur_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraBlur_checkBox.sizePolicy().hasHeightForWidth())
        self.cameraBlur_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.cameraBlur_checkBox.setFont(font)
        self.cameraBlur_checkBox.setObjectName(_fromUtf8("cameraBlur_checkBox"))
        self.gridLayout.addWidget(self.cameraBlur_checkBox, 3, 4, 1, 1)
        self.tracedBlur_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tracedBlur_checkBox.sizePolicy().hasHeightForWidth())
        self.tracedBlur_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.tracedBlur_checkBox.setFont(font)
        self.tracedBlur_checkBox.setObjectName(_fromUtf8("tracedBlur_checkBox"))
        self.gridLayout.addWidget(self.tracedBlur_checkBox, 3, 5, 1, 1)
        self.ribgenOnly_checkBox = QtGui.QCheckBox(self.renderOptFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ribgenOnly_checkBox.sizePolicy().hasHeightForWidth())
        self.ribgenOnly_checkBox.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.ribgenOnly_checkBox.setFont(font)
        self.ribgenOnly_checkBox.setObjectName(_fromUtf8("ribgenOnly_checkBox"))
        self.gridLayout.addWidget(self.ribgenOnly_checkBox, 0, 5, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout)
        self.renderOptLayout.addWidget(self.renderOptFrame)
        self.horizontalLayout_28.addLayout(self.renderOptLayout)
        self.verticalLayout.addWidget(self.renderOptMainFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.renderOptRenderManLabel.setText(_translate("Form", "Options", None))
        self.renderOptLabel.setText(_translate("Form", "renderManRIS", None))
        self.shutterAngle_label.setText(_translate("Form", "ShutterAngle ", None))
        self.label_2.setText(_translate("Form", "/", None))
        self.label.setText(_translate("Form", "CheckPoint ", None))
        self.minmaxSamples_label.setText(_translate("Form", "min/maxSamples ", None))
        self.ribgenLimit_label.setText(_translate("Form", "RibGenLimit ", None))
        self.denoise_label.setText(_translate("Form", "Denoise ", None))
        self.incremental_checkBox.setText(_translate("Form", "Incremental", None))
        self.denoise_aov_checkBox.setText(_translate("Form", "AOV Denoise", None))
        self.denoise_strength_label.setText(_translate("Form", "Strength ", None))
        self.denoise_comboBox.setItemText(0, _translate("Form", "off", None))
        self.denoise_comboBox.setItemText(1, _translate("Form", "Frame", None))
        self.denoise_comboBox.setItemText(2, _translate("Form", "Cross-frame", None))
        self.motionBlur_checkBox.setText(_translate("Form", "MotionBlur", None))
        self.cameraBlur_checkBox.setText(_translate("Form", "CameraBlur", None))
        self.tracedBlur_checkBox.setText(_translate("Form", "RayTracedMB", None))
        self.ribgenOnly_checkBox.setText(_translate("Form", "RibGenOnly", None))
