# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spooltool_v04.ui'
#
# Created: Fri Feb  2 10:56:54 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

import Qt
import Qt.QtWidgets as QtGui
import Qt.QtCore as QtCore

# from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobScriptMainWindow(object):
    def setupUi(self, JobScriptMainWindow):
        JobScriptMainWindow.setObjectName(_fromUtf8("JobScriptMainWindow"))
        JobScriptMainWindow.resize(583, 595)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JobScriptMainWindow.sizePolicy().hasHeightForWidth())
        JobScriptMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(JobScriptMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.engineMenuFrame = QtGui.QFrame(self.centralwidget)
        self.engineMenuFrame.setEnabled(True)
        self.engineMenuFrame.setMinimumSize(QtCore.QSize(0, 48))
        self.engineMenuFrame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.engineMenuFrame.setBaseSize(QtCore.QSize(0, 0))
        self.engineMenuFrame.setFrameShape(QtGui.QFrame.Box)
        self.engineMenuFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.engineMenuFrame.setObjectName(_fromUtf8("engineMenuFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.engineMenuFrame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.engineMenuColumn = QtGui.QHBoxLayout()
        self.engineMenuColumn.setSpacing(0)
        self.engineMenuColumn.setObjectName(_fromUtf8("engineMenuColumn"))
        self.tractorEngineColumn = QtGui.QHBoxLayout()
        self.tractorEngineColumn.setSpacing(0)
        self.tractorEngineColumn.setObjectName(_fromUtf8("tractorEngineColumn"))
        self.tractorEngine_label = QtGui.QLabel(self.engineMenuFrame)
        self.tractorEngine_label.setMinimumSize(QtCore.QSize(100, 0))
        self.tractorEngine_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tractorEngine_label.setFont(font)
        self.tractorEngine_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tractorEngine_label.setObjectName(_fromUtf8("tractorEngine_label"))
        self.tractorEngineColumn.addWidget(self.tractorEngine_label)
        self.tractorEngine_comboBox = QtGui.QComboBox(self.engineMenuFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tractorEngine_comboBox.sizePolicy().hasHeightForWidth())
        self.tractorEngine_comboBox.setSizePolicy(sizePolicy)
        self.tractorEngine_comboBox.setMinimumSize(QtCore.QSize(120, 28))
        self.tractorEngine_comboBox.setMaximumSize(QtCore.QSize(120, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.tractorEngine_comboBox.setFont(font)
        self.tractorEngine_comboBox.setIconSize(QtCore.QSize(16, 16))
        self.tractorEngine_comboBox.setObjectName(_fromUtf8("tractorEngine_comboBox"))
        self.tractorEngineColumn.addWidget(self.tractorEngine_comboBox)
        self.engineMenuColumn.addLayout(self.tractorEngineColumn)
        self.userColumn = QtGui.QHBoxLayout()
        self.userColumn.setSpacing(0)
        self.userColumn.setObjectName(_fromUtf8("userColumn"))
        self.currentRenderer_label = QtGui.QLabel(self.engineMenuFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentRenderer_label.sizePolicy().hasHeightForWidth())
        self.currentRenderer_label.setSizePolicy(sizePolicy)
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentRenderer_label.setFont(font)
        self.currentRenderer_label.setText(_fromUtf8(""))
        self.currentRenderer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentRenderer_label.setObjectName(_fromUtf8("currentRenderer_label"))
        self.userColumn.addWidget(self.currentRenderer_label)
        self.UserLabel = QtGui.QLabel(self.engineMenuFrame)
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserLabel.setFont(font)
        self.UserLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UserLabel.setObjectName(_fromUtf8("UserLabel"))
        self.userColumn.addWidget(self.UserLabel)
        self.userLineEdit = QtGui.QLineEdit(self.engineMenuFrame)
        self.userLineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.userLineEdit.setMaximumSize(QtCore.QSize(96, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.userLineEdit.setFont(font)
        self.userLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userLineEdit.setText(_fromUtf8(""))
        self.userLineEdit.setDragEnabled(False)
        self.userLineEdit.setReadOnly(True)
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.userColumn.addWidget(self.userLineEdit)
        self.engineMenuColumn.addLayout(self.userColumn)
        self.verticalLayout_2.addLayout(self.engineMenuColumn)
        self.verticalLayout.addWidget(self.engineMenuFrame)
        self.infoFrame = QtGui.QFrame(self.centralwidget)
        self.infoFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.infoFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.infoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.infoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.infoFrame.setObjectName(_fromUtf8("infoFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.infoFrame)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.workspaceLabel = QtGui.QLabel(self.infoFrame)
        self.workspaceLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.workspaceLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.workspaceLabel.setFont(font)
        self.workspaceLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(77,129,200); color: rgb(22,22,22); }"))
        self.workspaceLabel.setTextFormat(QtCore.Qt.PlainText)
        self.workspaceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.workspaceLabel.setObjectName(_fromUtf8("workspaceLabel"))
        self.horizontalLayout_11.addWidget(self.workspaceLabel)
        self.workspace_lineEdit = QtGui.QLineEdit(self.infoFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workspace_lineEdit.sizePolicy().hasHeightForWidth())
        self.workspace_lineEdit.setSizePolicy(sizePolicy)
        self.workspace_lineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.workspace_lineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.workspace_lineEdit.setFont(font)
        self.workspace_lineEdit.setReadOnly(False)
        self.workspace_lineEdit.setObjectName(_fromUtf8("workspace_lineEdit"))
        self.horizontalLayout_11.addWidget(self.workspace_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sceneFileLabel = QtGui.QLabel(self.infoFrame)
        self.sceneFileLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.sceneFileLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sceneFileLabel.setFont(font)
        self.sceneFileLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(77,129,200); color: rgb(22,22,22); }"))
        self.sceneFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sceneFileLabel.setObjectName(_fromUtf8("sceneFileLabel"))
        self.horizontalLayout.addWidget(self.sceneFileLabel)
        self.sceneFile_lineEdit = QtGui.QLineEdit(self.infoFrame)
        self.sceneFile_lineEdit.setMinimumSize(QtCore.QSize(0, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.sceneFile_lineEdit.setFont(font)
        self.sceneFile_lineEdit.setText(_fromUtf8(""))
        self.sceneFile_lineEdit.setReadOnly(True)
        self.sceneFile_lineEdit.setObjectName(_fromUtf8("sceneFile_lineEdit"))
        self.horizontalLayout.addWidget(self.sceneFile_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(4)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.outputVersionLabel = QtGui.QLabel(self.infoFrame)
        self.outputVersionLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.outputVersionLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.outputVersionLabel.setFont(font)
        self.outputVersionLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(77,129,200); color: rgb(22,22,22); }"))
        self.outputVersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputVersionLabel.setObjectName(_fromUtf8("outputVersionLabel"))
        self.horizontalLayout_15.addWidget(self.outputVersionLabel)
        self.outputVersion_lineEdit = QtGui.QLineEdit(self.infoFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputVersion_lineEdit.sizePolicy().hasHeightForWidth())
        self.outputVersion_lineEdit.setSizePolicy(sizePolicy)
        self.outputVersion_lineEdit.setMinimumSize(QtCore.QSize(0, 36))
        self.outputVersion_lineEdit.setMaximumSize(QtCore.QSize(16777215, 36))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.outputVersion_lineEdit.setFont(font)
        self.outputVersion_lineEdit.setObjectName(_fromUtf8("outputVersion_lineEdit"))
        self.horizontalLayout_15.addWidget(self.outputVersion_lineEdit)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.infoFrame)
        self.jobParametersFrame = QtGui.QFrame(self.centralwidget)
        self.jobParametersFrame.setMaximumSize(QtCore.QSize(16777215, 52))
        self.jobParametersFrame.setFrameShape(QtGui.QFrame.Box)
        self.jobParametersFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.jobParametersFrame.setObjectName(_fromUtf8("jobParametersFrame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.jobParametersFrame)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.priorityLayout = QtGui.QVBoxLayout()
        self.priorityLayout.setSpacing(0)
        self.priorityLayout.setObjectName(_fromUtf8("priorityLayout"))
        self.priorityLabel = QtGui.QLabel(self.jobParametersFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priorityLabel.sizePolicy().hasHeightForWidth())
        self.priorityLabel.setSizePolicy(sizePolicy)
        self.priorityLabel.setMinimumSize(QtCore.QSize(100, 24))
        self.priorityLabel.setMaximumSize(QtCore.QSize(100, 24))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.priorityLabel.setFont(font)
        self.priorityLabel.setAcceptDrops(True)
        self.priorityLabel.setAutoFillBackground(False)
        self.priorityLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(170,170,170);\n"
"                       color: rgb(22,22,22); }"))
        self.priorityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.priorityLabel.setObjectName(_fromUtf8("priorityLabel"))
        self.priorityLayout.addWidget(self.priorityLabel)
        self.priority_spinBox = QtGui.QSpinBox(self.jobParametersFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priority_spinBox.sizePolicy().hasHeightForWidth())
        self.priority_spinBox.setSizePolicy(sizePolicy)
        self.priority_spinBox.setMinimumSize(QtCore.QSize(100, 28))
        self.priority_spinBox.setMaximumSize(QtCore.QSize(100, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.priority_spinBox.setFont(font)
        self.priority_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.priority_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.priority_spinBox.setMaximum(10000)
        self.priority_spinBox.setProperty("value", 100)
        self.priority_spinBox.setObjectName(_fromUtf8("priority_spinBox"))
        self.priorityLayout.addWidget(self.priority_spinBox)
        self.horizontalLayout_9.addLayout(self.priorityLayout)
        self.environmentKeyLayout = QtGui.QVBoxLayout()
        self.environmentKeyLayout.setSpacing(0)
        self.environmentKeyLayout.setObjectName(_fromUtf8("environmentKeyLayout"))
        self.environmentKeyLabel = QtGui.QLabel(self.jobParametersFrame)
        self.environmentKeyLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.environmentKeyLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        font = Qt.QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.environmentKeyLabel.setFont(font)
        self.environmentKeyLabel.setAutoFillBackground(False)
        self.environmentKeyLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(140,140,140);\n"
"                       color: rgb(22,22,22); }"))
        self.environmentKeyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.environmentKeyLabel.setObjectName(_fromUtf8("environmentKeyLabel"))
        self.environmentKeyLayout.addWidget(self.environmentKeyLabel)
        self.environmentKey_lineEdit = QtGui.QLineEdit(self.jobParametersFrame)
        self.environmentKey_lineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.environmentKey_lineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.environmentKey_lineEdit.setFont(font)
        self.environmentKey_lineEdit.setFrame(True)
        self.environmentKey_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.environmentKey_lineEdit.setReadOnly(False)
        self.environmentKey_lineEdit.setObjectName(_fromUtf8("environmentKey_lineEdit"))
        self.environmentKeyLayout.addWidget(self.environmentKey_lineEdit)
        self.horizontalLayout_9.addLayout(self.environmentKeyLayout)
        self.serviceKeyLayout = QtGui.QVBoxLayout()
        self.serviceKeyLayout.setSpacing(0)
        self.serviceKeyLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.serviceKeyLayout.setObjectName(_fromUtf8("serviceKeyLayout"))
        self.project_Label = QtGui.QLabel(self.jobParametersFrame)
        self.project_Label.setMinimumSize(QtCore.QSize(100, 24))
        self.project_Label.setMaximumSize(QtCore.QSize(16777215, 24))
        font = Qt.QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.project_Label.setFont(font)
        self.project_Label.setAutoFillBackground(False)
        self.project_Label.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(170,170,170);\n"
"                       color: rgb(22,22,22); }"))
        self.project_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_Label.setObjectName(_fromUtf8("project_Label"))
        self.serviceKeyLayout.addWidget(self.project_Label)
        self.project_lineEdit = QtGui.QLineEdit(self.jobParametersFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_lineEdit.sizePolicy().hasHeightForWidth())
        self.project_lineEdit.setSizePolicy(sizePolicy)
        self.project_lineEdit.setMaximumSize(QtCore.QSize(100, 28))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.project_lineEdit.setFont(font)
        self.project_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.project_lineEdit.setObjectName(_fromUtf8("project_lineEdit"))
        self.serviceKeyLayout.addWidget(self.project_lineEdit)
        self.horizontalLayout_9.addLayout(self.serviceKeyLayout)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.jobParametersFrame)
        self.StereoLayout = QtGui.QVBoxLayout()
        self.StereoLayout.setSpacing(0)
        self.StereoLayout.setObjectName(_fromUtf8("StereoLayout"))
        self.verticalLayout.addLayout(self.StereoLayout)
        self.frameRangeFrame = QtGui.QFrame(self.centralwidget)
        self.frameRangeFrame.setMinimumSize(QtCore.QSize(0, 64))
        self.frameRangeFrame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frameRangeFrame.setFrameShape(QtGui.QFrame.Box)
        self.frameRangeFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameRangeFrame.setObjectName(_fromUtf8("frameRangeFrame"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frameRangeFrame)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(4)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.frameRangeOuterFrame = QtGui.QFrame(self.frameRangeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRangeOuterFrame.sizePolicy().hasHeightForWidth())
        self.frameRangeOuterFrame.setSizePolicy(sizePolicy)
        self.frameRangeOuterFrame.setMinimumSize(QtCore.QSize(100, 48))
        self.frameRangeOuterFrame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frameRangeOuterFrame.setAutoFillBackground(False)
        self.frameRangeOuterFrame.setStyleSheet(_fromUtf8(""))
        self.frameRangeOuterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRangeOuterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRangeOuterFrame.setObjectName(_fromUtf8("frameRangeOuterFrame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frameRangeOuterFrame)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frameRangeLabel = QtGui.QLabel(self.frameRangeOuterFrame)
        self.frameRangeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.frameRangeLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frameRangeLabel.setFont(font)
        self.frameRangeLabel.setAcceptDrops(True)
        self.frameRangeLabel.setAutoFillBackground(False)
        self.frameRangeLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(150,150,150);                       color: rgb(22,22,22); }"))
        self.frameRangeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRangeLabel.setObjectName(_fromUtf8("frameRangeLabel"))
        self.verticalLayout_8.addWidget(self.frameRangeLabel)
        self.horizontalLayout_22.addWidget(self.frameRangeOuterFrame)
        self.frameRangeFieldFrame = QtGui.QFrame(self.frameRangeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRangeFieldFrame.sizePolicy().hasHeightForWidth())
        self.frameRangeFieldFrame.setSizePolicy(sizePolicy)
        self.frameRangeFieldFrame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frameRangeFieldFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRangeFieldFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRangeFieldFrame.setObjectName(_fromUtf8("frameRangeFieldFrame"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.frameRangeFieldFrame)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setMargin(2)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.frameRange_lineEdit = QtGui.QLineEdit(self.frameRangeFieldFrame)
        self.frameRange_lineEdit.setMinimumSize(QtCore.QSize(0, 36))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.frameRange_lineEdit.setFont(font)
        self.frameRange_lineEdit.setObjectName(_fromUtf8("frameRange_lineEdit"))
        self.horizontalLayout_24.addWidget(self.frameRange_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.bylabel = QtGui.QLabel(self.frameRangeFieldFrame)
        self.bylabel.setObjectName(_fromUtf8("bylabel"))
        self.horizontalLayout_24.addWidget(self.bylabel)
        self.frameRangeBy_spinBox = QtGui.QSpinBox(self.frameRangeFieldFrame)
        self.frameRangeBy_spinBox.setMinimumSize(QtCore.QSize(0, 36))
        self.frameRangeBy_spinBox.setMaximumSize(QtCore.QSize(48, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(11)
        self.frameRangeBy_spinBox.setFont(font)
        self.frameRangeBy_spinBox.setMinimum(1)
        self.frameRangeBy_spinBox.setObjectName(_fromUtf8("frameRangeBy_spinBox"))
        self.horizontalLayout_24.addWidget(self.frameRangeBy_spinBox)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.tacticInfoSpace = QtGui.QLabel(self.frameRangeFieldFrame)
        self.tacticInfoSpace.setMinimumSize(QtCore.QSize(5, 0))
        self.tacticInfoSpace.setText(_fromUtf8(""))
        self.tacticInfoSpace.setObjectName(_fromUtf8("tacticInfoSpace"))
        self.horizontalLayout_23.addWidget(self.tacticInfoSpace)
        self.horizontalLayout_22.addWidget(self.frameRangeFieldFrame)
        self.tacticInfoFrame = QtGui.QFrame(self.frameRangeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tacticInfoFrame.sizePolicy().hasHeightForWidth())
        self.tacticInfoFrame.setSizePolicy(sizePolicy)
        self.tacticInfoFrame.setMinimumSize(QtCore.QSize(150, 0))
        self.tacticInfoFrame.setMaximumSize(QtCore.QSize(136, 16777215))
        self.tacticInfoFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tacticInfoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tacticInfoFrame.setObjectName(_fromUtf8("tacticInfoFrame"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.tacticInfoFrame)
        self.horizontalLayout_25.setMargin(4)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.getTacticFrameButton = QtGui.QToolButton(self.tacticInfoFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getTacticFrameButton.sizePolicy().hasHeightForWidth())
        self.getTacticFrameButton.setSizePolicy(sizePolicy)
        self.getTacticFrameButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.getTacticFrameButton.setStyleSheet(_fromUtf8("QToolButton { border-style: none; } \n"
"\n"
"QToolButton:hover {background-color: rgb(86,86,86);\n"
"                                   border-radius:8px;\n"
"}    \n"
"\n"
"\n"
"\n"
"\n"
"QToolButton:pressed {background-color: rgb(128, 128, 128);\n"
"                                 border-style: inset;\n"
"                                border-width: 1px; \n"
"                                   border-radius: 8px; \n"
"                                border-color:rgb(128,128,128);\n"
"}\n"
"\n"
""))
        self.getTacticFrameButton.setObjectName(_fromUtf8("getTacticFrameButton"))
        self.horizontalLayout_25.addWidget(self.getTacticFrameButton)
        self.tacticFrameInfoLabel = QtGui.QLabel(self.tacticInfoFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tacticFrameInfoLabel.sizePolicy().hasHeightForWidth())
        self.tacticFrameInfoLabel.setSizePolicy(sizePolicy)
        self.tacticFrameInfoLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.tacticFrameInfoLabel.setObjectName(_fromUtf8("tacticFrameInfoLabel"))
        self.horizontalLayout_25.addWidget(self.tacticFrameInfoLabel)
        self.setFrameFromTactic = QtGui.QToolButton(self.tacticInfoFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setFrameFromTactic.sizePolicy().hasHeightForWidth())
        self.setFrameFromTactic.setSizePolicy(sizePolicy)
        self.setFrameFromTactic.setStyleSheet(_fromUtf8("QToolButton { border-style: none; } \n"
"\n"
"QToolButton:hover {background-color: rgb(86,86,86);\n"
"                                   border-radius:8px;\n"
"}    \n"
""))
        self.setFrameFromTactic.setArrowType(QtCore.Qt.NoArrow)
        self.setFrameFromTactic.setObjectName(_fromUtf8("setFrameFromTactic"))
        self.horizontalLayout_25.addWidget(self.setFrameFromTactic)
        self.horizontalLayout_22.addWidget(self.tacticInfoFrame)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.verticalLayout.addWidget(self.frameRangeFrame)
        self.resolutionFrame = QtGui.QFrame(self.centralwidget)
        self.resolutionFrame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.resolutionFrame.setFrameShape(QtGui.QFrame.Box)
        self.resolutionFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.resolutionFrame.setObjectName(_fromUtf8("resolutionFrame"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.resolutionFrame)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(4)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.resolutionOuterFrame = QtGui.QFrame(self.resolutionFrame)
        self.resolutionOuterFrame.setMinimumSize(QtCore.QSize(100, 48))
        self.resolutionOuterFrame.setMaximumSize(QtCore.QSize(100, 64))
        self.resolutionOuterFrame.setAutoFillBackground(False)
        self.resolutionOuterFrame.setStyleSheet(_fromUtf8(""))
        self.resolutionOuterFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.resolutionOuterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.resolutionOuterFrame.setObjectName(_fromUtf8("resolutionOuterFrame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.resolutionOuterFrame)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.resolutionLabel = QtGui.QLabel(self.resolutionOuterFrame)
        self.resolutionLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.resolutionLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resolutionLabel.setFont(font)
        self.resolutionLabel.setAcceptDrops(True)
        self.resolutionLabel.setAutoFillBackground(False)
        self.resolutionLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(150,150,150);                       color: rgb(22,22,22); }"))
        self.resolutionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resolutionLabel.setObjectName(_fromUtf8("resolutionLabel"))
        self.verticalLayout_7.addWidget(self.resolutionLabel)
        self.horizontalLayout_16.addWidget(self.resolutionOuterFrame)
        self.resolutionPresetFrame = QtGui.QFrame(self.resolutionFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionPresetFrame.sizePolicy().hasHeightForWidth())
        self.resolutionPresetFrame.setSizePolicy(sizePolicy)
        self.resolutionPresetFrame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.resolutionPresetFrame.setFrameShape(QtGui.QFrame.Box)
        self.resolutionPresetFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.resolutionPresetFrame.setObjectName(_fromUtf8("resolutionPresetFrame"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.resolutionPresetFrame)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.resolutionMenuSetLayout = QtGui.QHBoxLayout()
        self.resolutionMenuSetLayout.setSpacing(0)
        self.resolutionMenuSetLayout.setObjectName(_fromUtf8("resolutionMenuSetLayout"))
        self.resolutionFull = QtGui.QToolButton(self.resolutionPresetFrame)
        self.resolutionFull.setMinimumSize(QtCore.QSize(52, 28))
        self.resolutionFull.setStyleSheet(_fromUtf8("QToolButton {     color: rgb(215,215,215); \n"
"                       border-style: none; }\n"
"\n"
"QToolButton:hover {color:rgb(244,244,244);}\n"
"\n"
"QToolButton:pressed {background-color: rgb(86,86,86);\n"
"                                 border-style: outset;\n"
"                                border-color: rgb(52,52,52);\n"
"                                   border-radius:3px;\n"
"\n"
"}    \n"
"QToolButton:checked {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(86, 86, 86, 255), stop:1 rgba(128,128, 128, 128));\n"
"                                border-color: black;\n"
"                                border-width: 1px;\n"
"                                   border-radius:3px;\n"
"                                 border-style: inset;}\n"
"\n"
"QToolButton:flat { border: none; } \n"
""))
        self.resolutionFull.setCheckable(True)
        self.resolutionFull.setChecked(False)
        self.resolutionFull.setAutoExclusive(True)
        self.resolutionFull.setAutoRaise(True)
        self.resolutionFull.setObjectName(_fromUtf8("resolutionFull"))
        self.resolutionMenuSetLayout.addWidget(self.resolutionFull)
        self.resolutionProxy = QtGui.QToolButton(self.resolutionPresetFrame)
        self.resolutionProxy.setMinimumSize(QtCore.QSize(52, 28))
        self.resolutionProxy.setStyleSheet(_fromUtf8("QToolButton {     color: rgb(215,215,215); \n"
"                       border-style: none; }\n"
"\n"
"QToolButton:hover {color:rgb(244,244,244);}\n"
"\n"
"QToolButton:pressed {background-color: rgb(86,86,86);\n"
"                                 border-style: outset;\n"
"                                border-color: rgb(52,52,52);\n"
"                                   border-radius:3px;\n"
"\n"
"}    \n"
"QToolButton:checked {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(86, 86, 86, 255), stop:1 rgba(128,128, 128, 128));\n"
"                                border-color: black;\n"
"                                border-width: 1px;\n"
"                                   border-radius:3px;\n"
"                                 border-style: inset;}\n"
"\n"
"QToolButton:flat { border: none; } \n"
""))
        self.resolutionProxy.setCheckable(True)
        self.resolutionProxy.setChecked(False)
        self.resolutionProxy.setAutoExclusive(True)
        self.resolutionProxy.setAutoRaise(True)
        self.resolutionProxy.setObjectName(_fromUtf8("resolutionProxy"))
        self.resolutionMenuSetLayout.addWidget(self.resolutionProxy)
        self.resolutionMenuSetLayout.setStretch(0, 1)
        self.resolutionMenuSetLayout.setStretch(1, 1)
        self.horizontalLayout_19.addLayout(self.resolutionMenuSetLayout)
        self.horizontalLayout_16.addWidget(self.resolutionPresetFrame)
        self.widthHeightFrame = QtGui.QFrame(self.resolutionFrame)
        self.widthHeightFrame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.widthHeightFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.widthHeightFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.widthHeightFrame.setObjectName(_fromUtf8("widthHeightFrame"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widthHeightFrame)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.widthValueColumn = QtGui.QVBoxLayout()
        self.widthValueColumn.setSpacing(0)
        self.widthValueColumn.setObjectName(_fromUtf8("widthValueColumn"))
        self.width = QtGui.QLabel(self.widthHeightFrame)
        self.width.setMinimumSize(QtCore.QSize(0, 14))
        self.width.setMaximumSize(QtCore.QSize(16777215, 18))
        self.width.setAutoFillBackground(False)
        self.width.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(170,170,170);\n"
"                       color: rgb(22,22,22); }"))
        self.width.setAlignment(QtCore.Qt.AlignCenter)
        self.width.setObjectName(_fromUtf8("width"))
        self.widthValueColumn.addWidget(self.width)
        self.width_spinBox = QtGui.QSpinBox(self.widthHeightFrame)
        self.width_spinBox.setMinimumSize(QtCore.QSize(80, 0))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.width_spinBox.setFont(font)
        self.width_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.width_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.width_spinBox.setMaximum(65535)
        self.width_spinBox.setObjectName(_fromUtf8("width_spinBox"))
        self.widthValueColumn.addWidget(self.width_spinBox)
        self.horizontalLayout_20.addLayout(self.widthValueColumn)
        self.label_8 = QtGui.QLabel(self.widthHeightFrame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_20.addWidget(self.label_8)
        self.heightValueColumn = QtGui.QVBoxLayout()
        self.heightValueColumn.setSpacing(0)
        self.heightValueColumn.setObjectName(_fromUtf8("heightValueColumn"))
        self.height = QtGui.QLabel(self.widthHeightFrame)
        self.height.setMinimumSize(QtCore.QSize(0, 14))
        self.height.setMaximumSize(QtCore.QSize(16777215, 18))
        self.height.setAutoFillBackground(False)
        self.height.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(170,170,170);\n"
"                       color: rgb(22,22,22); }"))
        self.height.setAlignment(QtCore.Qt.AlignCenter)
        self.height.setObjectName(_fromUtf8("height"))
        self.heightValueColumn.addWidget(self.height)
        self.height_spinBox = QtGui.QSpinBox(self.widthHeightFrame)
        self.height_spinBox.setMinimumSize(QtCore.QSize(80, 0))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        self.height_spinBox.setFont(font)
        self.height_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.height_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.height_spinBox.setMaximum(65535)
        self.height_spinBox.setObjectName(_fromUtf8("height_spinBox"))
        self.heightValueColumn.addWidget(self.height_spinBox)
        self.horizontalLayout_20.addLayout(self.heightValueColumn)
        self.horizontalLayout_16.addWidget(self.widthHeightFrame)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 3)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addWidget(self.resolutionFrame)
        self.OptionLayout = QtGui.QVBoxLayout()
        self.OptionLayout.setSpacing(0)
        self.OptionLayout.setObjectName(_fromUtf8("OptionLayout"))
        self.verticalLayout.addLayout(self.OptionLayout)
        self.preCompFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preCompFrame.sizePolicy().hasHeightForWidth())
        self.preCompFrame.setSizePolicy(sizePolicy)
        self.preCompFrame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.preCompFrame.setFrameShape(QtGui.QFrame.Box)
        self.preCompFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.preCompFrame.setObjectName(_fromUtf8("preCompFrame"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.preCompFrame)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(4)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.postRenderOuterFrame_3 = QtGui.QFrame(self.preCompFrame)
        self.postRenderOuterFrame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.postRenderOuterFrame_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.postRenderOuterFrame_3.setAutoFillBackground(False)
        self.postRenderOuterFrame_3.setStyleSheet(_fromUtf8("QFrame { background-color:rgb(150,150,150); }"))
        self.postRenderOuterFrame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.postRenderOuterFrame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.postRenderOuterFrame_3.setObjectName(_fromUtf8("postRenderOuterFrame_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.postRenderOuterFrame_3)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.postRenderLabel_3 = QtGui.QLabel(self.postRenderOuterFrame_3)
        self.postRenderLabel_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.postRenderLabel_3.setFont(font)
        self.postRenderLabel_3.setAcceptDrops(True)
        self.postRenderLabel_3.setAutoFillBackground(False)
        self.postRenderLabel_3.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(150,150,150);                       color: rgb(22,22,22); }"))
        self.postRenderLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.postRenderLabel_3.setObjectName(_fromUtf8("postRenderLabel_3"))
        self.verticalLayout_12.addWidget(self.postRenderLabel_3)
        self.horizontalLayout_31.addWidget(self.postRenderOuterFrame_3)
        self.frame_7 = QtGui.QFrame(self.preCompFrame)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.renderOptRenderManItemsFrame_4 = QtGui.QFrame(self.frame_7)
        self.renderOptRenderManItemsFrame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.renderOptRenderManItemsFrame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.renderOptRenderManItemsFrame_4.setObjectName(_fromUtf8("renderOptRenderManItemsFrame_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.renderOptRenderManItemsFrame_4)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.browsePreCompFile = QtGui.QToolButton(self.renderOptRenderManItemsFrame_4)
        self.browsePreCompFile.setStyleSheet(_fromUtf8("QToolButton { border-style: none; } \n"
"\n"
"QToolButton:hover {background-color: rgb(86,86,86);\n"
"                                   border-radius:8px;\n"
"}    \n"
""))
        self.browsePreCompFile.setObjectName(_fromUtf8("browsePreCompFile"))
        self.gridLayout_3.addWidget(self.browsePreCompFile, 0, 2, 1, 1)
        self.precomp_lineEdit = QtGui.QLineEdit(self.renderOptRenderManItemsFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precomp_lineEdit.sizePolicy().hasHeightForWidth())
        self.precomp_lineEdit.setSizePolicy(sizePolicy)
        self.precomp_lineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.precomp_lineEdit.setObjectName(_fromUtf8("precomp_lineEdit"))
        self.gridLayout_3.addWidget(self.precomp_lineEdit, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.renderOptRenderManItemsFrame_4)
        self.horizontalLayout_31.addWidget(self.frame_7)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_31)
        self.verticalLayout.addWidget(self.preCompFrame)
        self.sendJobButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendJobButton.sizePolicy().hasHeightForWidth())
        self.sendJobButton.setSizePolicy(sizePolicy)
        self.sendJobButton.setMinimumSize(QtCore.QSize(0, 40))
        self.sendJobButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.sendJobButton.setFont(font)
        self.sendJobButton.setAutoFillBackground(False)
        self.sendJobButton.setStyleSheet(_fromUtf8("\n"
"QPushButton { background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(77, 102, 128, 255), stop:1 rgba(77, 102, 128, 128))\n"
";\n"
"                       color: white;\n"
"                       border-style: outset;\n"
"                       border-width: 1px;\n"
"                       border-radius: 2px;\n"
"                       border-color: grey;}\n"
"\n"
"QPushButton:hover { border-color:rgb(100, 140, 150);\n"
"                                    border-width:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {background-color: rgb(108, 145, 200);\n"
"                                 border-style: inset;}\n"
"QPushButton:flat {border: none;}\n"
"QPushButton:default {border-color: beige;}\n"
""))
        self.sendJobButton.setObjectName(_fromUtf8("sendJobButton"))
        self.verticalLayout.addWidget(self.sendJobButton)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.recoveryVersionLabel = QtGui.QLabel(self.centralwidget)
        self.recoveryVersionLabel.setMinimumSize(QtCore.QSize(120, 34))
        font = Qt.QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.recoveryVersionLabel.setFont(font)
        self.recoveryVersionLabel.setStyleSheet(_fromUtf8("QLabel { background-color:rgb(117,183,205); color: rgb(22,22,22); }"))
        self.recoveryVersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recoveryVersionLabel.setObjectName(_fromUtf8("recoveryVersionLabel"))
        self.horizontalLayout_2.addWidget(self.recoveryVersionLabel)
        self.recoveryVersionCbox = QtGui.QComboBox(self.centralwidget)
        self.recoveryVersionCbox.setMinimumSize(QtCore.QSize(0, 34))
        font = Qt.QtGui.QFont()
        font.setPointSize(12)
        self.recoveryVersionCbox.setFont(font)
        self.recoveryVersionCbox.setObjectName(_fromUtf8("recoveryVersionCbox"))
        self.horizontalLayout_2.addWidget(self.recoveryVersionCbox)
        self.recoveryButton = QtGui.QPushButton(self.centralwidget)
        self.recoveryButton.setMinimumSize(QtCore.QSize(0, 34))
        self.recoveryButton.setStyleSheet(_fromUtf8("\n"
"QPushButton { background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(117, 183, 205, 255), stop:1 rgba(77, 102, 128, 128))\n"
";\n"
"                       color: white;\n"
"                       border-style: outset;\n"
"                       border-width: 1px;\n"
"                       border-radius: 2px;\n"
"                       border-color: grey;}\n"
"\n"
"QPushButton:hover { border-color:rgb(100, 140, 150);\n"
"                                    border-width:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {background-color: rgb(108, 145, 200);\n"
"                                 border-style: inset;}\n"
"QPushButton:flat {border: none;}\n"
"QPushButton:default {border-color: beige;}\n"
""))
        self.recoveryButton.setObjectName(_fromUtf8("recoveryButton"))
        self.horizontalLayout_2.addWidget(self.recoveryButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 0))
        self.closeButton.setMaximumSize(QtCore.QSize(16777215, 24))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.verticalLayout.addWidget(self.closeButton)
        JobScriptMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(JobScriptMainWindow)
        QtCore.QMetaObject.connectSlotsByName(JobScriptMainWindow)

    def retranslateUi(self, JobScriptMainWindow):
        JobScriptMainWindow.setWindowTitle(_translate("JobScriptMainWindow", "MainWindow", None))
        self.tractorEngine_label.setText(_translate("JobScriptMainWindow", "Engine ", None))
        self.UserLabel.setText(_translate("JobScriptMainWindow", "User : ", None))
        self.workspaceLabel.setText(_translate("JobScriptMainWindow", "Workspace", None))
        self.sceneFileLabel.setText(_translate("JobScriptMainWindow", "Scene file", None))
        self.outputVersionLabel.setText(_translate("JobScriptMainWindow", "Out Version", None))
        self.priorityLabel.setText(_translate("JobScriptMainWindow", "Priority", None))
        self.environmentKeyLabel.setText(_translate("JobScriptMainWindow", "Environment Key", None))
        self.project_Label.setText(_translate("JobScriptMainWindow", "Project", None))
        self.frameRangeLabel.setText(_translate("JobScriptMainWindow", "Frame Range", None))
        self.bylabel.setText(_translate("JobScriptMainWindow", "By", None))
        self.getTacticFrameButton.setText(_translate("JobScriptMainWindow", "...", None))
        self.tacticFrameInfoLabel.setText(_translate("JobScriptMainWindow", "Tactic : ####-####", None))
        self.setFrameFromTactic.setText(_translate("JobScriptMainWindow", "...", None))
        self.resolutionLabel.setText(_translate("JobScriptMainWindow", "Resolution", None))
        self.resolutionFull.setText(_translate("JobScriptMainWindow", "Full", None))
        self.resolutionProxy.setText(_translate("JobScriptMainWindow", "Proxy", None))
        self.width.setText(_translate("JobScriptMainWindow", "Width", None))
        self.label_8.setText(_translate("JobScriptMainWindow", "  X  ", None))
        self.height.setText(_translate("JobScriptMainWindow", "Height", None))
        self.postRenderLabel_3.setText(_translate("JobScriptMainWindow", "Pre Comp", None))
        self.browsePreCompFile.setText(_translate("JobScriptMainWindow", "...", None))
        self.sendJobButton.setText(_translate("JobScriptMainWindow", "Send Job to Tractor", None))
        self.recoveryVersionLabel.setText(_translate("JobScriptMainWindow", "Recovery Version", None))
        self.recoveryButton.setText(_translate("JobScriptMainWindow", "Recovery Job to Tractor", None))
        self.closeButton.setText(_translate("JobScriptMainWindow", "CLOSE", None))

