# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadActions.ui'
#
# Created: Thu Mar  8 11:21:41 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(350, 640)
        Form.setAcceptDrops(True)
        self.allAct = QtGui.QListWidget(Form)
        self.allAct.setGeometry(QtCore.QRect(6, 9, 265, 170))
        self.allAct.setMinimumSize(QtCore.QSize(265, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.allAct.setFont(font)
        self.allAct.setAcceptDrops(True)
        self.allAct.setDragEnabled(False)
        self.allAct.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.allAct.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.allAct.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.allAct.setObjectName(_fromUtf8("allAct"))
        self.taCombo = QtGui.QComboBox(Form)
        self.taCombo.setGeometry(QtCore.QRect(148, 236, 197, 29))
        self.taCombo.setAcceptDrops(False)
        self.taCombo.setObjectName(_fromUtf8("taCombo"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 239, 98, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.agAct = QtGui.QListWidget(Form)
        self.agAct.setGeometry(QtCore.QRect(6, 282, 265, 150))
        self.agAct.setMinimumSize(QtCore.QSize(265, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.agAct.setFont(font)
        self.agAct.setObjectName(_fromUtf8("agAct"))
        self.dropBtn = QtGui.QPushButton(Form)
        self.dropBtn.setGeometry(QtCore.QRect(7, 190, 338, 36))
        self.dropBtn.setObjectName(_fromUtf8("dropBtn"))
        self.loadBtn = QtGui.QPushButton(Form)
        self.loadBtn.setGeometry(QtCore.QRect(7, 440, 338, 36))
        self.loadBtn.setObjectName(_fromUtf8("loadBtn"))
        self.refBtn = QtGui.QPushButton(Form)
        self.refBtn.setGeometry(QtCore.QRect(114, 236, 29, 29))
        self.refBtn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../opt/Basefount/Miarmy/maya/icons/ref.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refBtn.setIcon(icon)
        self.refBtn.setObjectName(_fromUtf8("refBtn"))
        self.impBtn = QtGui.QPushButton(Form)
        self.impBtn.setGeometry(QtCore.QRect(278, 10, 67, 83))
        self.impBtn.setObjectName(_fromUtf8("impBtn"))
        self.delBtn = QtGui.QPushButton(Form)
        self.delBtn.setGeometry(QtCore.QRect(278, 99, 67, 82))
        self.delBtn.setObjectName(_fromUtf8("delBtn"))
        self.delAgBtn = QtGui.QPushButton(Form)
        self.delAgBtn.setGeometry(QtCore.QRect(278, 280, 67, 153))
        self.delAgBtn.setObjectName(_fromUtf8("delAgBtn"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 549, 179, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(211, 550, 131, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 550, 15, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(18, 576, 322, 57))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.acChk = QtGui.QCheckBox(self.layoutWidget)
        self.acChk.setMinimumSize(QtCore.QSize(80, 0))
        self.acChk.setMaximumSize(QtCore.QSize(90, 16777215))
        self.acChk.setObjectName(_fromUtf8("acChk"))
        self.verticalLayout.addWidget(self.acChk)
        self.trChk = QtGui.QCheckBox(self.layoutWidget)
        self.trChk.setMinimumSize(QtCore.QSize(80, 0))
        self.trChk.setMaximumSize(QtCore.QSize(90, 16777215))
        self.trChk.setObjectName(_fromUtf8("trChk"))
        self.verticalLayout.addWidget(self.trChk)
        self.deChk = QtGui.QCheckBox(self.layoutWidget)
        self.deChk.setMinimumSize(QtCore.QSize(80, 0))
        self.deChk.setMaximumSize(QtCore.QSize(90, 16777215))
        self.deChk.setObjectName(_fromUtf8("deChk"))
        self.verticalLayout.addWidget(self.deChk)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pickBtn = QtGui.QPushButton(self.layoutWidget)
        self.pickBtn.setMinimumSize(QtCore.QSize(92, 45))
        self.pickBtn.setMaximumSize(QtCore.QSize(92, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pickBtn.setFont(font)
        self.pickBtn.setObjectName(_fromUtf8("pickBtn"))
        self.horizontalLayout.addWidget(self.pickBtn)
        self.assignBtn = QtGui.QPushButton(self.layoutWidget)
        self.assignBtn.setMinimumSize(QtCore.QSize(92, 45))
        self.assignBtn.setMaximumSize(QtCore.QSize(92, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.assignBtn.setFont(font)
        self.assignBtn.setObjectName(_fromUtf8("assignBtn"))
        self.horizontalLayout.addWidget(self.assignBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(253, 485, 89, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 485, 15, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 484, 222, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(33, 510, 300, 33))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.nodeCmb = QtGui.QComboBox(self.widget)
        self.nodeCmb.setMinimumSize(QtCore.QSize(120, 0))
        self.nodeCmb.setMaximumSize(QtCore.QSize(120, 24))
        self.nodeCmb.setObjectName(_fromUtf8("nodeCmb"))
        self.horizontalLayout_3.addWidget(self.nodeCmb)
        self.refrBtn = QtGui.QPushButton(self.widget)
        self.refrBtn.setMaximumSize(QtCore.QSize(26, 24))
        self.refrBtn.setText(_fromUtf8(""))
        self.refrBtn.setIcon(icon)
        self.refrBtn.setObjectName(_fromUtf8("refrBtn"))
        self.horizontalLayout_3.addWidget(self.refrBtn)
        self.raBtn = QtGui.QPushButton(self.widget)
        self.raBtn.setMinimumSize(QtCore.QSize(140, 0))
        self.raBtn.setMaximumSize(QtCore.QSize(140, 24))
        self.raBtn.setObjectName(_fromUtf8("raBtn"))
        self.horizontalLayout_3.addWidget(self.raBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Load Actions", None))
        self.label.setText(_translate("Form", "Target Agent :", None))
        self.dropBtn.setText(_translate("Form", "Drop", None))
        self.loadBtn.setText(_translate("Form", "Load Actions", None))
        self.impBtn.setText(_translate("Form", "Import", None))
        self.delBtn.setText(_translate("Form", "Delete", None))
        self.delAgBtn.setText(_translate("Form", "Delete", None))
        self.label_2.setText(_translate("Form", "Miarmy Contents Copy", None))
        self.acChk.setText(_translate("Form", "Action", None))
        self.trChk.setText(_translate("Form", "Transition", None))
        self.deChk.setText(_translate("Form", "Decision", None))
        self.pickBtn.setText(_translate("Form", "Pick", None))
        self.assignBtn.setText(_translate("Form", "Assign", None))
        self.label_3.setText(_translate("Form", "Action register to stateNode", None))
        self.raBtn.setText(_translate("Form", "Register Actions", None))

