# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_dxTacticReview.ui',
# licensing of './ui_dxTacticReview.ui' applies.
#
# Created: Thu Jan 28 15:43:24 2021
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 700)
        Form.setMinimumSize(QtCore.QSize(600, 700))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_main = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_main.sizePolicy().hasHeightForWidth())
        self.tabWidget_main.setSizePolicy(sizePolicy)
        self.tabWidget_main.setMinimumSize(QtCore.QSize(480, 680))
        self.tabWidget_main.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_snapShot = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_snapShot.sizePolicy().hasHeightForWidth())
        self.tab_snapShot.setSizePolicy(sizePolicy)
        self.tab_snapShot.setObjectName("tab_snapShot")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_snapShot)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_snap = QtWidgets.QGridLayout()
        self.gridLayout_snap.setObjectName("gridLayout_snap")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_snapShow = QtWidgets.QLabel(self.tab_snapShot)
        self.label_snapShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_snapShow.setObjectName("label_snapShow")
        self.horizontalLayout.addWidget(self.label_snapShow)
        self.comboBox_snapShow = QtWidgets.QComboBox(self.tab_snapShot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_snapShow.sizePolicy().hasHeightForWidth())
        self.comboBox_snapShow.setSizePolicy(sizePolicy)
        self.comboBox_snapShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_snapShow.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_snapShow.setObjectName("comboBox_snapShow")
        self.horizontalLayout.addWidget(self.comboBox_snapShow)
        self.label_snapSeq = QtWidgets.QLabel(self.tab_snapShot)
        self.label_snapSeq.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_snapSeq.setObjectName("label_snapSeq")
        self.horizontalLayout.addWidget(self.label_snapSeq)
        self.comboBox_snapSeq = QtWidgets.QComboBox(self.tab_snapShot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_snapSeq.sizePolicy().hasHeightForWidth())
        self.comboBox_snapSeq.setSizePolicy(sizePolicy)
        self.comboBox_snapSeq.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_snapSeq.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_snapSeq.setObjectName("comboBox_snapSeq")
        self.horizontalLayout.addWidget(self.comboBox_snapSeq)
        self.label_snapShot = QtWidgets.QLabel(self.tab_snapShot)
        self.label_snapShot.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_snapShot.setObjectName("label_snapShot")
        self.horizontalLayout.addWidget(self.label_snapShot)
        self.lineEdit_snapShot = QtWidgets.QLineEdit(self.tab_snapShot)
        self.lineEdit_snapShot.setObjectName("lineEdit_snapShot")
        self.horizontalLayout.addWidget(self.lineEdit_snapShot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_snapSearch = QtWidgets.QPushButton(self.tab_snapShot)
        self.pushButton_snapSearch.setObjectName("pushButton_snapSearch")
        self.horizontalLayout.addWidget(self.pushButton_snapSearch)
        self.gridLayout_snap.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_snap, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_snapShot, "")
        self.tab_reviewSup = QtWidgets.QWidget()
        self.tab_reviewSup.setObjectName("tab_reviewSup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_reviewSup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_reSup = QtWidgets.QGridLayout()
        self.gridLayout_reSup.setObjectName("gridLayout_reSup")
        self.horizontalLayout_reSup = QtWidgets.QHBoxLayout()
        self.horizontalLayout_reSup.setSpacing(7)
        self.horizontalLayout_reSup.setObjectName("horizontalLayout_reSup")
        self.label_reSupShow = QtWidgets.QLabel(self.tab_reviewSup)
        self.label_reSupShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_reSupShow.setObjectName("label_reSupShow")
        self.horizontalLayout_reSup.addWidget(self.label_reSupShow)
        self.comboBox_reSupShow = QtWidgets.QComboBox(self.tab_reviewSup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_reSupShow.sizePolicy().hasHeightForWidth())
        self.comboBox_reSupShow.setSizePolicy(sizePolicy)
        self.comboBox_reSupShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_reSupShow.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_reSupShow.setObjectName("comboBox_reSupShow")
        self.horizontalLayout_reSup.addWidget(self.comboBox_reSupShow)
        self.label_reSupSeq = QtWidgets.QLabel(self.tab_reviewSup)
        self.label_reSupSeq.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_reSupSeq.setObjectName("label_reSupSeq")
        self.horizontalLayout_reSup.addWidget(self.label_reSupSeq)
        self.comboBox_reviewSup = QtWidgets.QComboBox(self.tab_reviewSup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_reviewSup.sizePolicy().hasHeightForWidth())
        self.comboBox_reviewSup.setSizePolicy(sizePolicy)
        self.comboBox_reviewSup.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_reviewSup.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_reviewSup.setObjectName("comboBox_reviewSup")
        self.horizontalLayout_reSup.addWidget(self.comboBox_reviewSup)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_reSup.addItem(spacerItem1)
        self.pushButton_resupSearch = QtWidgets.QPushButton(self.tab_reviewSup)
        self.pushButton_resupSearch.setObjectName("pushButton_resupSearch")
        self.horizontalLayout_reSup.addWidget(self.pushButton_resupSearch)
        self.gridLayout_reSup.addLayout(self.horizontalLayout_reSup, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_reSup, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_reviewSup, "")
        self.tab_milestone = QtWidgets.QWidget()
        self.tab_milestone.setObjectName("tab_milestone")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_milestone)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_mile = QtWidgets.QGridLayout()
        self.gridLayout_mile.setObjectName("gridLayout_mile")
        self.horizontalLayout_mile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_mile.setSpacing(8)
        self.horizontalLayout_mile.setObjectName("horizontalLayout_mile")
        self.label_mileShow = QtWidgets.QLabel(self.tab_milestone)
        self.label_mileShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_mileShow.setObjectName("label_mileShow")
        self.horizontalLayout_mile.addWidget(self.label_mileShow)
        self.comboBox_mileShow = QtWidgets.QComboBox(self.tab_milestone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mileShow.sizePolicy().hasHeightForWidth())
        self.comboBox_mileShow.setSizePolicy(sizePolicy)
        self.comboBox_mileShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_mileShow.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_mileShow.setObjectName("comboBox_mileShow")
        self.horizontalLayout_mile.addWidget(self.comboBox_mileShow)
        self.label_milestone = QtWidgets.QLabel(self.tab_milestone)
        self.label_milestone.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_milestone.setObjectName("label_milestone")
        self.horizontalLayout_mile.addWidget(self.label_milestone)
        self.comboBox_milestone = QtWidgets.QComboBox(self.tab_milestone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_milestone.sizePolicy().hasHeightForWidth())
        self.comboBox_milestone.setSizePolicy(sizePolicy)
        self.comboBox_milestone.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_milestone.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_milestone.setObjectName("comboBox_milestone")
        self.horizontalLayout_mile.addWidget(self.comboBox_milestone)
        self.checkBox_mileAll = QtWidgets.QCheckBox(self.tab_milestone)
        self.checkBox_mileAll.setObjectName("checkBox_mileAll")
        self.horizontalLayout_mile.addWidget(self.checkBox_mileAll)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_mile.addItem(spacerItem2)
        self.pushButton_mileSearch = QtWidgets.QPushButton(self.tab_milestone)
        self.pushButton_mileSearch.setObjectName("pushButton_mileSearch")
        self.horizontalLayout_mile.addWidget(self.pushButton_mileSearch)
        self.gridLayout_mile.addLayout(self.horizontalLayout_mile, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_mile, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_milestone, "")
        self.tab_feedbackTopic = QtWidgets.QWidget()
        self.tab_feedbackTopic.setObjectName("tab_feedbackTopic")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_feedbackTopic)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_feed = QtWidgets.QGridLayout()
        self.gridLayout_feed.setObjectName("gridLayout_feed")
        self.horizontalLayout_feed = QtWidgets.QHBoxLayout()
        self.horizontalLayout_feed.setSpacing(7)
        self.horizontalLayout_feed.setObjectName("horizontalLayout_feed")
        self.label_feedShow = QtWidgets.QLabel(self.tab_feedbackTopic)
        self.label_feedShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_feedShow.setObjectName("label_feedShow")
        self.horizontalLayout_feed.addWidget(self.label_feedShow)
        self.comboBox_feedShow = QtWidgets.QComboBox(self.tab_feedbackTopic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feedShow.sizePolicy().hasHeightForWidth())
        self.comboBox_feedShow.setSizePolicy(sizePolicy)
        self.comboBox_feedShow.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_feedShow.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_feedShow.setObjectName("comboBox_feedShow")
        self.horizontalLayout_feed.addWidget(self.comboBox_feedShow)
        self.label_feedback = QtWidgets.QLabel(self.tab_feedbackTopic)
        self.label_feedback.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_feedback.setObjectName("label_feedback")
        self.horizontalLayout_feed.addWidget(self.label_feedback)
        self.comboBox_feedback = QtWidgets.QComboBox(self.tab_feedbackTopic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feedback.sizePolicy().hasHeightForWidth())
        self.comboBox_feedback.setSizePolicy(sizePolicy)
        self.comboBox_feedback.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_feedback.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_feedback.setObjectName("comboBox_feedback")
        self.horizontalLayout_feed.addWidget(self.comboBox_feedback)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_feed.addItem(spacerItem3)
        self.pushButton_feedSearch = QtWidgets.QPushButton(self.tab_feedbackTopic)
        self.pushButton_feedSearch.setObjectName("pushButton_feedSearch")
        self.horizontalLayout_feed.addWidget(self.pushButton_feedSearch)
        self.gridLayout_feed.addLayout(self.horizontalLayout_feed, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_feed, 0, 0, 1, 1)
        self.tabWidget_main.addTab(self.tab_feedbackTopic, "")
        self.gridLayout_6.addWidget(self.tabWidget_main, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_snapShow.setText(QtWidgets.QApplication.translate("Form", "show", None, -1))
        self.label_snapSeq.setText(QtWidgets.QApplication.translate("Form", "seq", None, -1))
        self.label_snapShot.setText(QtWidgets.QApplication.translate("Form", "shot", None, -1))
        self.pushButton_snapSearch.setText(QtWidgets.QApplication.translate("Form", "Refresh", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_snapShot), QtWidgets.QApplication.translate("Form", "   Snapshot   ", None, -1))
        self.label_reSupShow.setText(QtWidgets.QApplication.translate("Form", "show", None, -1))
        self.label_reSupSeq.setText(QtWidgets.QApplication.translate("Form", "review", None, -1))
        self.pushButton_resupSearch.setText(QtWidgets.QApplication.translate("Form", "Refresh", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_reviewSup), QtWidgets.QApplication.translate("Form", "Review Supervisor", None, -1))
        self.label_mileShow.setText(QtWidgets.QApplication.translate("Form", "show", None, -1))
        self.label_milestone.setText(QtWidgets.QApplication.translate("Form", "milestone", None, -1))
        self.checkBox_mileAll.setText(QtWidgets.QApplication.translate("Form", "All", None, -1))
        self.pushButton_mileSearch.setText(QtWidgets.QApplication.translate("Form", "Refresh", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_milestone), QtWidgets.QApplication.translate("Form", "Milestone", None, -1))
        self.label_feedShow.setText(QtWidgets.QApplication.translate("Form", "show", None, -1))
        self.label_feedback.setText(QtWidgets.QApplication.translate("Form", "Topic", None, -1))
        self.pushButton_feedSearch.setText(QtWidgets.QApplication.translate("Form", "Refresh", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_feedbackTopic), QtWidgets.QApplication.translate("Form", "Feedback Topic", None, -1))

