# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dxEditOrder.ui',
# licensing of 'ui_dxEditOrder.ui' applies.
#
# Created: Fri Aug 20 10:56:21 2021
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(965, 60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_11 = QtWidgets.QGridLayout(Form)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setMinimumSize(QtCore.QSize(900, 0))
        self.main_frame.setAutoFillBackground(False)
        self.main_frame.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_frame.setLineWidth(2)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.main_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout_6 = QtWidgets.QHBoxLayout()
        self.layout_6.setSpacing(8)
        self.layout_6.setObjectName("layout_6")
        self.show_label = QtWidgets.QLabel(self.frame_2)
        self.show_label.setMinimumSize(QtCore.QSize(60, 15))
        self.show_label.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.show_label.setFont(font)
        self.show_label.setStyleSheet("color : white;")
        self.show_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.show_label.setObjectName("show_label")
        self.layout_6.addWidget(self.show_label)
        self.show_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.show_comboBox.setMinimumSize(QtCore.QSize(40, 15))
        self.show_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.show_comboBox.setFont(font)
        self.show_comboBox.setMouseTracking(True)
        self.show_comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.show_comboBox.setStyleSheet("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;  combobox-popup: 0;")
        self.show_comboBox.setMaxVisibleItems(20)
        self.show_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.show_comboBox.setObjectName("show_comboBox")
        self.layout_6.addWidget(self.show_comboBox)
        self.task_label = QtWidgets.QLabel(self.frame_2)
        self.task_label.setEnabled(True)
        self.task_label.setMinimumSize(QtCore.QSize(0, 15))
        self.task_label.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.task_label.setFont(font)
        self.task_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.task_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.task_label.setObjectName("task_label")
        self.layout_6.addWidget(self.task_label)
        self.task_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.task_comboBox.setEnabled(True)
        self.task_comboBox.setMinimumSize(QtCore.QSize(40, 15))
        self.task_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.task_comboBox.setFont(font)
        self.task_comboBox.setMouseTracking(True)
        self.task_comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.task_comboBox.setStyleSheet("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;  combobox-popup: 0;")
        self.task_comboBox.setEditable(False)
        self.task_comboBox.setMaxVisibleItems(8)
        self.task_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.task_comboBox.setObjectName("task_comboBox")
        self.layout_6.addWidget(self.task_comboBox)
        self.seq_label = QtWidgets.QLabel(self.frame_2)
        self.seq_label.setMinimumSize(QtCore.QSize(0, 15))
        self.seq_label.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.seq_label.setFont(font)
        self.seq_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.seq_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seq_label.setObjectName("seq_label")
        self.layout_6.addWidget(self.seq_label)
        self.editStart_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editStart_lineEdit.sizePolicy().hasHeightForWidth())
        self.editStart_lineEdit.setSizePolicy(sizePolicy)
        self.editStart_lineEdit.setMinimumSize(QtCore.QSize(40, 15))
        self.editStart_lineEdit.setMaximumSize(QtCore.QSize(60, 35))
        self.editStart_lineEdit.setObjectName("editStart_lineEdit")
        self.layout_6.addWidget(self.editStart_lineEdit)
        self.seq_label_2 = QtWidgets.QLabel(self.frame_2)
        self.seq_label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.seq_label_2.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.seq_label_2.setFont(font)
        self.seq_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.seq_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seq_label_2.setObjectName("seq_label_2")
        self.layout_6.addWidget(self.seq_label_2)
        self.editEnd_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editEnd_lineEdit.sizePolicy().hasHeightForWidth())
        self.editEnd_lineEdit.setSizePolicy(sizePolicy)
        self.editEnd_lineEdit.setMinimumSize(QtCore.QSize(40, 15))
        self.editEnd_lineEdit.setMaximumSize(QtCore.QSize(60, 35))
        self.editEnd_lineEdit.setObjectName("editEnd_lineEdit")
        self.layout_6.addWidget(self.editEnd_lineEdit)
        self.import_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.import_pushButton.setMinimumSize(QtCore.QSize(130, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.import_pushButton.setFont(font)
        self.import_pushButton.setStyleSheet("color : white;\n"
"background-color: rgb(62, 109, 186);")
        self.import_pushButton.setObjectName("import_pushButton")
        self.layout_6.addWidget(self.import_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_6.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.layout_6)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout_11.addWidget(self.main_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.show_label.setText(QtWidgets.QApplication.translate("Form", "Show -", None, -1))
        self.task_label.setText(QtWidgets.QApplication.translate("Form", "Task -", None, -1))
        self.seq_label.setText(QtWidgets.QApplication.translate("Form", "EditOrder -", None, -1))
        self.seq_label_2.setText(QtWidgets.QApplication.translate("Form", "~", None, -1))
        self.import_pushButton.setText(QtWidgets.QApplication.translate("Form", "IMPORT", None, -1))

