# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shotpub_matchmove_widget.ui'
#
# Created: Tue Feb 21 12:37:31 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

#from PyQt4 import QtCore, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_shotpub_camera_Dialog(object):
    def setupUi(self, shotpub_camera_Dialog):
        shotpub_camera_Dialog.setObjectName(_fromUtf8("shotpub_camera_Dialog"))
        shotpub_camera_Dialog.resize(522, 734)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(shotpub_camera_Dialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.header = QtWidgets.QHBoxLayout()
        self.header.setObjectName(_fromUtf8("header"))
        self.header_title = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.header_title.setMinimumSize(QtCore.QSize(0, 0))
        self.header_title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.header_title.setFont(font)
        self.header_title.setObjectName(_fromUtf8("header_title"))
        self.header.addWidget(self.header_title)
        self.header_ver = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.header_ver.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_ver.setObjectName(_fromUtf8("header_ver"))
        self.header.addWidget(self.header_ver)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.header)
        self.pubTarget = QtWidgets.QHBoxLayout()
        self.pubTarget.setObjectName(_fromUtf8("pubTarget"))
        self.pubTarget_title = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.pubTarget_title.setMinimumSize(QtCore.QSize(80, 30))
        self.pubTarget_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pubTarget_title.setObjectName(_fromUtf8("pubTarget_title"))
        self.pubTarget.addWidget(self.pubTarget_title)
        self.pubTarget_show = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.pubTarget_show.setMinimumSize(QtCore.QSize(100, 0))
        self.pubTarget_show.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pubTarget_show.setObjectName(_fromUtf8("pubTarget_show"))
        self.pubTarget_show.addItem(_fromUtf8(""))
        self.pubTarget.addWidget(self.pubTarget_show)
        self.pubTarget_seq = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.pubTarget_seq.setMinimumSize(QtCore.QSize(100, 0))
        self.pubTarget_seq.setObjectName(_fromUtf8("pubTarget_seq"))
        self.pubTarget_seq.addItem(_fromUtf8(""))
        self.pubTarget.addWidget(self.pubTarget_seq)
        self.pubTarget_shot = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.pubTarget_shot.setMinimumSize(QtCore.QSize(120, 0))
        self.pubTarget_shot.setObjectName(_fromUtf8("pubTarget_shot"))
        self.pubTarget_shot.addItem(_fromUtf8(""))
        self.pubTarget.addWidget(self.pubTarget_shot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pubTarget.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.pubTarget)
        self.user = QtWidgets.QHBoxLayout()
        self.user.setObjectName(_fromUtf8("user"))
        self.user_title = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.user_title.setMinimumSize(QtCore.QSize(80, 30))
        self.user_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user_title.setObjectName(_fromUtf8("user_title"))
        self.user.addWidget(self.user_title)
        self.user_user = QtWidgets.QLineEdit(shotpub_camera_Dialog)
        self.user_user.setMaximumSize(QtCore.QSize(150, 16777215))
        self.user_user.setObjectName(_fromUtf8("user_user"))
        self.user.addWidget(self.user_user)
        self.ver_title = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.ver_title.setMinimumSize(QtCore.QSize(80, 30))
        self.ver_title.setObjectName(_fromUtf8("ver_title"))
        self.user.addWidget(self.ver_title)
        self.ver_spin = QtWidgets.QSpinBox(shotpub_camera_Dialog)
        self.ver_spin.setMinimumSize(QtCore.QSize(100, 0))
        self.ver_spin.setObjectName(_fromUtf8("ver_spin"))
        self.user.addWidget(self.ver_spin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.user)
        self.sceneOptions = QtWidgets.QGroupBox(shotpub_camera_Dialog)
        self.sceneOptions.setObjectName(_fromUtf8("sceneOptions"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sceneOptions)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sceneOptions_layout1 = QtWidgets.QGridLayout()
        self.sceneOptions_layout1.setObjectName(_fromUtf8("sceneOptions_layout1"))
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sceneOptions_layout1.addItem(spacerItem3, 0, 3, 3, 1)
        self.sceneOptions_endFrame = QtWidgets.QLineEdit(self.sceneOptions)
        self.sceneOptions_endFrame.setMinimumSize(QtCore.QSize(70, 0))
        self.sceneOptions_endFrame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sceneOptions_endFrame.setObjectName(_fromUtf8("sceneOptions_endFrame"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_endFrame, 0, 2, 2, 1)
        self.sceneOptions_startFrame = QtWidgets.QLineEdit(self.sceneOptions)
        self.sceneOptions_startFrame.setMinimumSize(QtCore.QSize(70, 0))
        self.sceneOptions_startFrame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sceneOptions_startFrame.setObjectName(_fromUtf8("sceneOptions_startFrame"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_startFrame, 0, 1, 2, 1)
        self.sceneOptions_frame = QtWidgets.QLabel(self.sceneOptions)
        self.sceneOptions_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.sceneOptions_frame.setObjectName(_fromUtf8("sceneOptions_frame"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_frame, 0, 0, 2, 1)
        self.sceneOptions_renderRes = QtWidgets.QLabel(self.sceneOptions)
        self.sceneOptions_renderRes.setObjectName(_fromUtf8("sceneOptions_renderRes"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_renderRes, 2, 0, 1, 1)
        self.sceneOptions_renderWidth = QtWidgets.QLineEdit(self.sceneOptions)
        self.sceneOptions_renderWidth.setMinimumSize(QtCore.QSize(70, 0))
        self.sceneOptions_renderWidth.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sceneOptions_renderWidth.setObjectName(_fromUtf8("sceneOptions_renderWidth"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_renderWidth, 2, 1, 1, 1)
        self.sceneOptions_renderHeight = QtWidgets.QLineEdit(self.sceneOptions)
        self.sceneOptions_renderHeight.setMinimumSize(QtCore.QSize(70, 0))
        self.sceneOptions_renderHeight.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sceneOptions_renderHeight.setObjectName(_fromUtf8("sceneOptions_renderHeight"))
        self.sceneOptions_layout1.addWidget(self.sceneOptions_renderHeight, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.sceneOptions_layout1)
        self.sceneOptions_layout2 = QtWidgets.QGridLayout()
        self.sceneOptions_layout2.setObjectName(_fromUtf8("sceneOptions_layout2"))
        # self.sceneOptions_fbx = QtWidgets.QCheckBox(self.sceneOptions)
        # self.sceneOptions_fbx.setEnabled(True)
        # #self.sceneOptions_fbx.setChecked(True)
        # self.sceneOptions_fbx.setObjectName(_fromUtf8("sceneOptions_fbx"))
        # self.sceneOptions_layout2.addWidget(self.sceneOptions_fbx, 0, 1, 1, 1)
        # self.sceneOptions_geo_loc = QtWidgets.QCheckBox(self.sceneOptions)
        # self.sceneOptions_geo_loc.setEnabled(True)
        # self.sceneOptions_geo_loc.setChecked(True)
        # self.sceneOptions_geo_loc.setObjectName(_fromUtf8("sceneOptions_geo_loc"))
        # self.sceneOptions_layout2.addWidget(self.sceneOptions_geo_loc, 0, 1, 1, 1)
        self.sceneOptions_maya = QtWidgets.QCheckBox(self.sceneOptions)
        self.sceneOptions_maya.setEnabled(False)
        self.sceneOptions_maya.setChecked(True)
        self.sceneOptions_maya.setObjectName(_fromUtf8("sceneOptions_maya"))
        self.sceneOptions_layout2.addWidget(self.sceneOptions_maya, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sceneOptions_layout2.addItem(spacerItem4, 0, 2, 1, 1)
        self.sceneOptions_abc = QtWidgets.QCheckBox(self.sceneOptions)
        self.sceneOptions_abc.setEnabled(True)
        self.sceneOptions_abc.setChecked(True)
        self.sceneOptions_abc.setObjectName(_fromUtf8("sceneOptions_abc"))
        self.sceneOptions_layout2.addWidget(self.sceneOptions_abc, 1, 0, 1, 1)
        self.sceneOptions_retime = QtWidgets.QCheckBox(self.sceneOptions)
        self.sceneOptions_retime.setEnabled(True)
        self.sceneOptions_retime.setChecked(False)
        self.sceneOptions_retime.setObjectName(_fromUtf8("sceneOptions_retime"))
        self.sceneOptions_layout2.addWidget(self.sceneOptions_retime, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.sceneOptions_layout2)
        self.verticalLayout_3.addWidget(self.sceneOptions)
        self.camOptions = QtWidgets.QGroupBox(shotpub_camera_Dialog)
        self.camOptions.setObjectName(_fromUtf8("camOptions"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.camOptions)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.camOptions_layout1 = QtWidgets.QGridLayout()
        self.camOptions_layout1.setObjectName(_fromUtf8("camOptions_layout1"))
        self.camOptions_leftCam = QtWidgets.QLabel(self.camOptions)
        self.camOptions_leftCam.setMinimumSize(QtCore.QSize(100, 0))
        self.camOptions_leftCam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camOptions_leftCam.setObjectName(_fromUtf8("camOptions_leftCam"))
        self.camOptions_layout1.addWidget(self.camOptions_leftCam, 0, 0, 1, 1)
        self.camOptions_leftCamList = QtWidgets.QComboBox(self.camOptions)
        self.camOptions_leftCamList.setMinimumSize(QtCore.QSize(250, 0))
        self.camOptions_leftCamList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camOptions_leftCamList.setObjectName(_fromUtf8("camOptions_leftCamList"))
        self.camOptions_layout1.addWidget(self.camOptions_leftCamList, 0, 1, 1, 1)
        self.camOptions_reload = QtWidgets.QPushButton(self.camOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camOptions_reload.sizePolicy().hasHeightForWidth())
        self.camOptions_reload.setSizePolicy(sizePolicy)
        self.camOptions_reload.setMinimumSize(QtCore.QSize(60, 0))
        self.camOptions_reload.setMaximumSize(QtCore.QSize(60, 16777215))
        self.camOptions_reload.setObjectName(_fromUtf8("camOptions_reload"))
        self.camOptions_layout1.addWidget(self.camOptions_reload, 0, 2, 2, 1)
        self.camOptions_rightCam = QtWidgets.QLabel(self.camOptions)
        self.camOptions_rightCam.setEnabled(False)
        self.camOptions_rightCam.setMinimumSize(QtCore.QSize(0, 0))
        self.camOptions_rightCam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camOptions_rightCam.setObjectName(_fromUtf8("camOptions_rightCam"))
        self.camOptions_layout1.addWidget(self.camOptions_rightCam, 1, 0, 1, 1)
        self.camOptions_rightCamList = QtWidgets.QComboBox(self.camOptions)
        self.camOptions_rightCamList.setEnabled(False)
        self.camOptions_rightCamList.setMinimumSize(QtCore.QSize(0, 0))
        self.camOptions_rightCamList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camOptions_rightCamList.setObjectName(_fromUtf8("camOptions_rightCamList"))
        self.camOptions_layout1.addWidget(self.camOptions_rightCamList, 1, 1, 1, 1)
        self.camOptions_plate = QtWidgets.QLabel(self.camOptions)
        self.camOptions_plate.setEnabled(True)
        self.camOptions_plate.setMinimumSize(QtCore.QSize(0, 0))
        self.camOptions_plate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.camOptions_plate.setObjectName(_fromUtf8("camOptions_plate"))
        self.camOptions_layout1.addWidget(self.camOptions_plate, 3, 0, 1, 1)
        self.camOptions_plateList = QtWidgets.QComboBox(self.camOptions)
        self.camOptions_plateList.setEnabled(True)
        self.camOptions_plateList.setMinimumSize(QtCore.QSize(100, 0))
        self.camOptions_plateList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.camOptions_plateList.setObjectName(_fromUtf8("camOptions_plateList"))
        self.camOptions_layout1.addWidget(self.camOptions_plateList, 3, 1, 1, 1)
        self.camOptions_stereo = QtWidgets.QCheckBox(self.camOptions)
        self.camOptions_stereo.setObjectName(_fromUtf8("camOptions_stereo"))
        self.camOptions_layout1.addWidget(self.camOptions_stereo, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.camOptions_layout1.addItem(spacerItem5, 0, 3, 4, 1)
        self.verticalLayout.addLayout(self.camOptions_layout1)
        self.camOptions_line = QtWidgets.QFrame(self.camOptions)
        self.camOptions_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.camOptions_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.camOptions_line.setObjectName(_fromUtf8("camOptions_line"))
        self.verticalLayout.addWidget(self.camOptions_line)
        self.camOptions_layout2 = QtWidgets.QGridLayout()
        self.camOptions_layout2.setObjectName(_fromUtf8("camOptions_layout2"))
        self.camOptions_overscan = QtWidgets.QCheckBox(self.camOptions)
        self.camOptions_overscan.setChecked(False)
        self.camOptions_overscan.setObjectName(_fromUtf8("camOptions_overscan"))
        self.camOptions_layout2.addWidget(self.camOptions_overscan, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.camOptions_layout2.addItem(spacerItem6, 0, 2, 2, 1)
        # self.camOptions_mbKey = QtWidgets.QCheckBox(self.camOptions)
        # self.camOptions_mbKey.setEnabled(False)
        # self.camOptions_mbKey.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.camOptions_mbKey.setChecked(False)
        # self.camOptions_mbKey.setObjectName(_fromUtf8("camOptions_mbKey"))
        # self.camOptions_layout2.addWidget(self.camOptions_mbKey, 1, 0, 1, 1)
        self.camOptions_lockCam = QtWidgets.QCheckBox(self.camOptions)
        self.camOptions_lockCam.setEnabled(True)
        self.camOptions_lockCam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camOptions_lockCam.setChecked(True)
        self.camOptions_lockCam.setObjectName(_fromUtf8("camOptions_lockCam"))
        #self.camOptions_layout2.addWidget(self.camOptions_lockCam, 1, 1, 1, 1)
        self.camOptions_layout2.addWidget(self.camOptions_lockCam, 1, 0, 1, 1)
        self.camOptions_iplane = QtWidgets.QCheckBox(self.camOptions)
        self.camOptions_iplane.setEnabled(False)
        self.camOptions_iplane.setChecked(True)
        self.camOptions_iplane.setObjectName(_fromUtf8("camOptions_iplane"))
        self.camOptions_layout2.addWidget(self.camOptions_iplane, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.camOptions_layout2)
        self.camOptions_line3 = QtWidgets.QFrame(self.camOptions)
        self.camOptions_line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.camOptions_line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.camOptions_line3.setObjectName(_fromUtf8("camOptions_line3"))
        self.verticalLayout.addWidget(self.camOptions_line3)
        self.camOptions_layout3 = QtWidgets.QGridLayout()
        self.camOptions_layout3.setObjectName(_fromUtf8("camOptions_layout3"))
        # self.camOptions_mayaCam = QtWidgets.QCheckBox(self.camOptions)
        # self.camOptions_mayaCam.setEnabled(False)
        # self.camOptions_mayaCam.setMinimumSize(QtCore.QSize(0, 0))
        # self.camOptions_mayaCam.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.camOptions_mayaCam.setCheckable(True)
        # self.camOptions_mayaCam.setChecked(True)
        # self.camOptions_mayaCam.setObjectName(_fromUtf8("camOptions_mayaCam"))
        # self.camOptions_layout3.addWidget(self.camOptions_mayaCam, 0, 0, 1, 1)
        # self.camOptions_fbxCam = QtWidgets.QCheckBox(self.camOptions)
        # self.camOptions_fbxCam.setEnabled(True)
        # self.camOptions_fbxCam.setCheckable(True)
        # self.camOptions_fbxCam.setChecked(True)
        # self.camOptions_fbxCam.setObjectName(_fromUtf8("camOptions_fbxCam"))
        # self.camOptions_layout3.addWidget(self.camOptions_fbxCam, 0, 1, 1, 1)
        self.camOptions_abcCam = QtWidgets.QCheckBox(self.camOptions)
        self.camOptions_abcCam.setEnabled(True)
        self.camOptions_abcCam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camOptions_abcCam.setCheckable(True)
        self.camOptions_abcCam.setChecked(True)
        self.camOptions_abcCam.setObjectName(_fromUtf8("camOptions_abcCam"))
        #self.camOptions_layout3.addWidget(self.camOptions_abcCam, 1, 0, 1, 1)
        self.camOptions_layout3.addWidget(self.camOptions_abcCam, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.camOptions_layout3.addItem(spacerItem7, 0, 2, 2, 1)
        self.verticalLayout.addLayout(self.camOptions_layout3)
        self.camOptions_line2 = QtWidgets.QFrame(self.camOptions)
        self.camOptions_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.camOptions_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.camOptions_line2.setObjectName(_fromUtf8("camOptions_line2"))
        self.verticalLayout.addWidget(self.camOptions_line2)
        self.verticalLayout_3.addWidget(self.camOptions)
        self.doPub = QtWidgets.QHBoxLayout()
        self.doPub.setObjectName(_fromUtf8("doPub"))
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.doPub.addItem(spacerItem8)
        self.doPub_do = QtWidgets.QPushButton(shotpub_camera_Dialog)
        self.doPub_do.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doPub_do.setObjectName(_fromUtf8("doPub_do"))
        self.doPub.addWidget(self.doPub_do)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.doPub.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.doPub)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)

        self.retranslateUi(shotpub_camera_Dialog)
        QtCore.QMetaObject.connectSlotsByName(shotpub_camera_Dialog)

    def retranslateUi(self, shotpub_camera_Dialog):
        shotpub_camera_Dialog.setWindowTitle(_translate("shotpub_camera_Dialog", "ShotPub - matchmove", None))
        self.header_title.setText(_translate("shotpub_camera_Dialog", "shotpub - matchmove", None))
        self.header_ver.setText(_translate("shotpub_camera_Dialog", "v1.3", None))
        self.pubTarget_title.setText(_translate("shotpub_camera_Dialog", "Publish to", None))
        self.pubTarget_show.setItemText(0, _translate("shotpub_camera_Dialog", "select show", None))
        self.pubTarget_seq.setItemText(0, _translate("shotpub_camera_Dialog", "select seq", None))
        self.pubTarget_shot.setItemText(0, _translate("shotpub_camera_Dialog", "select shot", None))
        self.user_title.setText(_translate("shotpub_camera_Dialog", "User", None))
        self.ver_title.setText(_translate("shotpub_camera_Dialog", "Ver", None))
        self.sceneOptions.setTitle(_translate("shotpub_camera_Dialog", "Scene Options", None))
        self.sceneOptions_frame.setText(_translate("shotpub_camera_Dialog", "Frame Range", None))
        self.sceneOptions_renderRes.setText(_translate("shotpub_camera_Dialog", "Render Res", None))
        #self.sceneOptions_geo_loc.setText(_translate("shotpub_camera_Dialog", "export geo&&loc?", None))
        self.sceneOptions_maya.setText(_translate("shotpub_camera_Dialog", "Maya Scene", None))
        self.sceneOptions_abc.setText(_translate("shotpub_camera_Dialog", "Alembic Scene", None))
        self.sceneOptions_retime.setText(_translate("shotpub_camera_Dialog", "Retime", None))
        self.camOptions.setTitle(_translate("shotpub_camera_Dialog", "Camera Options", None))
        self.camOptions_leftCam.setText(_translate("shotpub_camera_Dialog", "Camera", None))
        self.camOptions_reload.setText(_translate("shotpub_camera_Dialog", "Reload", None))
        self.camOptions_rightCam.setText(_translate("shotpub_camera_Dialog", "Only Stereo", None))
        self.camOptions_plate.setText(_translate("shotpub_camera_Dialog", "Plate Type", None))
        self.camOptions_stereo.setText(_translate("shotpub_camera_Dialog", "Stereo Camera", None))
        self.camOptions_overscan.setText(_translate("shotpub_camera_Dialog", "Overscan", None))
        #self.camOptions_mbKey.setText(_translate("shotpub_camera_Dialog", "Add Handle Key for MB", None))
        self.camOptions_lockCam.setText(_translate("shotpub_camera_Dialog", "Lock Camera", None))
        self.camOptions_iplane.setText(_translate("shotpub_camera_Dialog", "Renew Imageplane", None))
        #self.camOptions_mayaCam.setText(_translate("shotpub_camera_Dialog", "Maya Camera", None))
        #self.camOptions_fbxCam.setText(_translate("shotpub_camera_Dialog", "FBX Camera", None))
        self.camOptions_abcCam.setText(_translate("shotpub_camera_Dialog", "Alembic Camera", None))
        self.doPub_do.setText(_translate("shotpub_camera_Dialog", "Publish", None))

