# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'txtool.ui'
#
# Created: Wed Dec 23 15:50:29 2020
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtWidgets, QtGui, QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_dxt(object):
    def setupUi(self, dxt):
        dxt.setObjectName(_fromUtf8("dxt"))
        dxt.resize(450, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dxt.sizePolicy().hasHeightForWidth())
        dxt.setSizePolicy(sizePolicy)
        dxt.setMinimumSize(QtCore.QSize(450, 270))
        dxt.setMaximumSize(QtCore.QSize(450, 270))
        self.layoutWidget = QtWidgets.QWidget(dxt)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 448, 247))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.logo_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(230, 81))
        self.logo_label.setMaximumSize(QtCore.QSize(230, 81))
        self.logo_label.setObjectName(_fromUtf8("logo_label"))
        self.verticalLayout_4.addWidget(self.logo_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.cmd_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cmd_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.cmd_comboBox.setObjectName(_fromUtf8("cmd_comboBox"))
        self.verticalLayout_3.addWidget(self.cmd_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mgrid_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mgrid_label.sizePolicy().hasHeightForWidth())
        self.mgrid_label.setSizePolicy(sizePolicy)
        self.mgrid_label.setMinimumSize(QtCore.QSize(97, 97))
        self.mgrid_label.setMaximumSize(QtCore.QSize(97, 97))
        self.mgrid_label.setObjectName(_fromUtf8("mgrid_label"))
        self.gridLayout_2.addWidget(self.mgrid_label, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.T_black = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_black.sizePolicy().hasHeightForWidth())
        self.T_black.setSizePolicy(sizePolicy)
        self.T_black.setMaximumSize(QtCore.QSize(30, 30))
        self.T_black.setText(_fromUtf8(""))
        self.T_black.setCheckable(True)
        self.T_black.setChecked(False)
        self.T_black.setObjectName(_fromUtf8("T_black"))
        self.verticalLayout_2.addWidget(self.T_black)
        self.T_clamp = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_clamp.sizePolicy().hasHeightForWidth())
        self.T_clamp.setSizePolicy(sizePolicy)
        self.T_clamp.setMaximumSize(QtCore.QSize(30, 30))
        self.T_clamp.setText(_fromUtf8(""))
        self.T_clamp.setCheckable(True)
        self.T_clamp.setObjectName(_fromUtf8("T_clamp"))
        self.verticalLayout_2.addWidget(self.T_clamp)
        self.T_periodic = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_periodic.sizePolicy().hasHeightForWidth())
        self.T_periodic.setSizePolicy(sizePolicy)
        self.T_periodic.setMaximumSize(QtCore.QSize(30, 30))
        self.T_periodic.setText(_fromUtf8(""))
        self.T_periodic.setCheckable(True)
        self.T_periodic.setChecked(True)
        self.T_periodic.setObjectName(_fromUtf8("T_periodic"))
        self.verticalLayout_2.addWidget(self.T_periodic)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.S_black = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_black.sizePolicy().hasHeightForWidth())
        self.S_black.setSizePolicy(sizePolicy)
        self.S_black.setMaximumSize(QtCore.QSize(30, 30))
        self.S_black.setAutoFillBackground(True)
        self.S_black.setText(_fromUtf8(""))
        self.S_black.setCheckable(True)
        self.S_black.setChecked(False)
        self.S_black.setFlat(False)
        self.S_black.setObjectName(_fromUtf8("S_black"))
        self.horizontalLayout_3.addWidget(self.S_black)
        self.S_clamp = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_clamp.sizePolicy().hasHeightForWidth())
        self.S_clamp.setSizePolicy(sizePolicy)
        self.S_clamp.setMaximumSize(QtCore.QSize(30, 30))
        self.S_clamp.setText(_fromUtf8(""))
        self.S_clamp.setCheckable(True)
        self.S_clamp.setObjectName(_fromUtf8("S_clamp"))
        self.horizontalLayout_3.addWidget(self.S_clamp)
        self.S_periodic = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_periodic.sizePolicy().hasHeightForWidth())
        self.S_periodic.setSizePolicy(sizePolicy)
        self.S_periodic.setMaximumSize(QtCore.QSize(30, 30))
        self.S_periodic.setText(_fromUtf8(""))
        self.S_periodic.setCheckable(True)
        self.S_periodic.setChecked(True)
        self.S_periodic.setObjectName(_fromUtf8("S_periodic"))
        self.horizontalLayout_3.addWidget(self.S_periodic)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.ST_link = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ST_link.sizePolicy().hasHeightForWidth())
        self.ST_link.setSizePolicy(sizePolicy)
        self.ST_link.setMaximumSize(QtCore.QSize(30, 30))
        self.ST_link.setAutoFillBackground(False)
        self.ST_link.setText(_fromUtf8(""))
        self.ST_link.setCheckable(True)
        self.ST_link.setChecked(True)
        self.ST_link.setObjectName(_fromUtf8("ST_link"))
        self.gridLayout_2.addWidget(self.ST_link, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.format_label = QtWidgets.QLabel(self.layoutWidget)
        self.format_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.format_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.format_label.setObjectName(_fromUtf8("format_label"))
        self.gridLayout_4.addWidget(self.format_label, 2, 0, 1, 1)
        self.format_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_comboBox.sizePolicy().hasHeightForWidth())
        self.format_comboBox.setSizePolicy(sizePolicy)
        self.format_comboBox.setMinimumSize(QtCore.QSize(120, 28))
        self.format_comboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.format_comboBox.setObjectName(_fromUtf8("format_comboBox"))
        self.gridLayout_4.addWidget(self.format_comboBox, 2, 1, 1, 1)
        self.type_label = QtWidgets.QLabel(self.layoutWidget)
        self.type_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.type_label.setObjectName(_fromUtf8("type_label"))
        self.gridLayout_4.addWidget(self.type_label, 3, 0, 1, 1)
        self.type_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.type_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.type_comboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.type_comboBox.setObjectName(_fromUtf8("type_comboBox"))
        self.gridLayout_4.addWidget(self.type_comboBox, 3, 1, 1, 1)
        self.precision_label = QtWidgets.QLabel(self.layoutWidget)
        self.precision_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.precision_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.precision_label.setObjectName(_fromUtf8("precision_label"))
        self.gridLayout_4.addWidget(self.precision_label, 4, 0, 1, 1)
        self.precision_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.precision_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.precision_comboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.precision_comboBox.setObjectName(_fromUtf8("precision_comboBox"))
        self.gridLayout_4.addWidget(self.precision_comboBox, 4, 1, 1, 1)
        self.access_label = QtWidgets.QLabel(self.layoutWidget)
        self.access_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.access_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.access_label.setObjectName(_fromUtf8("access_label"))
        self.gridLayout_4.addWidget(self.access_label, 5, 0, 1, 1)
        self.access_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.access_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.access_comboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.access_comboBox.setObjectName(_fromUtf8("access_comboBox"))
        self.gridLayout_4.addWidget(self.access_comboBox, 5, 1, 1, 1)
        self.pattern_label = QtWidgets.QLabel(self.layoutWidget)
        self.pattern_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pattern_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pattern_label.setObjectName(_fromUtf8("pattern_label"))
        self.gridLayout_4.addWidget(self.pattern_label, 6, 0, 1, 1)
        self.pattern_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.pattern_comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.pattern_comboBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pattern_comboBox.setObjectName(_fromUtf8("pattern_comboBox"))
        self.gridLayout_4.addWidget(self.pattern_comboBox, 6, 1, 1, 1)
        self.newer_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.newer_checkBox.setMinimumSize(QtCore.QSize(0, 24))
        self.newer_checkBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.newer_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newer_checkBox.setChecked(True)
        self.newer_checkBox.setObjectName(_fromUtf8("newer_checkBox"))
        self.gridLayout_4.addWidget(self.newer_checkBox, 1, 1, 1, 1)
        self.txmove_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.txmove_checkBox.setFont(font)
        self.txmove_checkBox.setChecked(True)
        self.txmove_checkBox.setObjectName(_fromUtf8("txmove_checkBox"))
        self.gridLayout_4.addWidget(self.txmove_checkBox, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)

        self.retranslateUi(dxt)
        QtCore.QMetaObject.connectSlotsByName(dxt)

    def retranslateUi(self, dxt):
        dxt.setWindowTitle(_translate("dxt", "dxTool Window", None))
        self.logo_label.setText(_translate("dxt", "TextLabel", None))
        self.label_2.setText(_translate("dxt", "Command", None))
        self.mgrid_label.setText(_translate("dxt", "grid_img", None))
        self.format_label.setText(_translate("dxt", "Format", None))
        self.type_label.setText(_translate("dxt", "Type", None))
        self.precision_label.setText(_translate("dxt", "Precision", None))
        self.access_label.setText(_translate("dxt", "Access", None))
        self.pattern_label.setText(_translate("dxt", "Pattern", None))
        self.newer_checkBox.setText(_translate("dxt", "Newer", None))
        self.txmove_checkBox.setText(_translate("dxt", "move to ../tex", None))

