# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AstRefPubUI.ui'
#
# Created: Fri Sep  8 18:35:05 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

import pymodule.Qt.QtWidgets as QtGui
from pymodule.Qt import QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AstRefPub(object):
    def setupUi(self, AstRefPub):
        AstRefPub.setObjectName(_fromUtf8("AstRefPub"))
        AstRefPub.resize(865, 586)
        self.gridLayout_4 = QtGui.QGridLayout(AstRefPub)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.marvPathEdit = QtGui.QLineEdit(AstRefPub)
        self.marvPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.marvPathEdit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.marvPathEdit.setReadOnly(True)
        self.marvPathEdit.setObjectName(_fromUtf8("marvPathEdit"))
        self.gridLayout.addWidget(self.marvPathEdit, 9, 1, 1, 3)
        self.hairPathEdit = QtGui.QLineEdit(AstRefPub)
        self.hairPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.hairPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hairPathEdit.setReadOnly(True)
        self.hairPathEdit.setObjectName(_fromUtf8("hairPathEdit"))
        self.gridLayout.addWidget(self.hairPathEdit, 10, 1, 1, 3)
        self.STDPathEdit = QtGui.QLineEdit(AstRefPub)
        self.STDPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.STDPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.STDPathEdit.setReadOnly(True)
        self.STDPathEdit.setObjectName(_fromUtf8("STDPathEdit"))
        self.gridLayout.addWidget(self.STDPathEdit, 11, 1, 1, 3)
        self.categoryComboBox = QtGui.QComboBox(AstRefPub)
        self.categoryComboBox.setEditable(True)
        self.categoryComboBox.setObjectName(_fromUtf8("categoryComboBox"))
        self.gridLayout.addWidget(self.categoryComboBox, 1, 3, 1, 2)
        self.label_7 = QtGui.QLabel(AstRefPub)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.assetPathEdit = QtGui.QLineEdit(AstRefPub)
        self.assetPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.assetPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.assetPathEdit.setReadOnly(True)
        self.assetPathEdit.setObjectName(_fromUtf8("assetPathEdit"))
        self.gridLayout.addWidget(self.assetPathEdit, 2, 1, 1, 3)
        self.assetPathBtn = QtGui.QPushButton(AstRefPub)
        self.assetPathBtn.setObjectName(_fromUtf8("assetPathBtn"))
        self.gridLayout.addWidget(self.assetPathBtn, 2, 4, 1, 1)
        self.label_6 = QtGui.QLabel(AstRefPub)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.texturePathEdit = QtGui.QLineEdit(AstRefPub)
        self.texturePathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.texturePathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.texturePathEdit.setReadOnly(True)
        self.texturePathEdit.setObjectName(_fromUtf8("texturePathEdit"))
        self.gridLayout.addWidget(self.texturePathEdit, 3, 1, 1, 3)
        self.texturePathBtn = QtGui.QPushButton(AstRefPub)
        self.texturePathBtn.setObjectName(_fromUtf8("texturePathBtn"))
        self.gridLayout.addWidget(self.texturePathBtn, 3, 4, 1, 1)
        self.label_3 = QtGui.QLabel(AstRefPub)
        self.label_3.setBaseSize(QtCore.QSize(90, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.mariPathEdit = QtGui.QLineEdit(AstRefPub)
        self.mariPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.mariPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mariPathEdit.setReadOnly(True)
        self.mariPathEdit.setObjectName(_fromUtf8("mariPathEdit"))
        self.gridLayout.addWidget(self.mariPathEdit, 4, 1, 1, 3)
        self.mariPathBtn = QtGui.QPushButton(AstRefPub)
        self.mariPathBtn.setObjectName(_fromUtf8("mariPathBtn"))
        self.gridLayout.addWidget(self.mariPathBtn, 4, 4, 1, 1)
        self.label_8 = QtGui.QLabel(AstRefPub)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(AstRefPub)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.typeComboBox = QtGui.QComboBox(AstRefPub)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.typeComboBox, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(AstRefPub)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.shaderPathEdit = QtGui.QLineEdit(AstRefPub)
        self.shaderPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.shaderPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        # self.shaderPathEdit.setReadOnly(True)
        self.shaderPathEdit.setObjectName(_fromUtf8("shaderPathEdit"))
        self.gridLayout.addWidget(self.shaderPathEdit, 8, 1, 1, 3)
        self.label_12 = QtGui.QLabel(AstRefPub)
        self.label_12.setBaseSize(QtCore.QSize(90, 40))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_marv = QtGui.QLabel(AstRefPub)
        self.label_marv.setBaseSize(QtCore.QSize(90, 40))
        self.label_marv.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_marv.setObjectName(_fromUtf8("label_marv"))
        self.gridLayout.addWidget(self.label_marv, 9, 0, 1, 1)
        self.label_5 = QtGui.QLabel(AstRefPub)
        self.label_5.setBaseSize(QtCore.QSize(90, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.label_13 = QtGui.QLabel(AstRefPub)
        self.label_13.setBaseSize(QtCore.QSize(90, 40))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.label_2 = QtGui.QLabel(AstRefPub)
        self.label_2.setBaseSize(QtCore.QSize(90, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.shaderPathBtn = QtGui.QPushButton(AstRefPub)
        self.shaderPathBtn.setObjectName(_fromUtf8("shaderPathBtn"))
        self.gridLayout.addWidget(self.shaderPathBtn, 8, 4, 1, 1)
        self.marvPathBtn = QtGui.QPushButton(AstRefPub)
        self.marvPathBtn .setObjectName(_fromUtf8("marvPathBtn "))
        self.gridLayout.addWidget(self.marvPathBtn , 9, 4, 1, 1)
        self.hairPathBtn = QtGui.QPushButton(AstRefPub)
        self.hairPathBtn.setObjectName(_fromUtf8("hairPathBtn"))
        self.gridLayout.addWidget(self.hairPathBtn, 10, 4, 1, 1)
        self.STDPathBtn = QtGui.QPushButton(AstRefPub)
        self.STDPathBtn.setObjectName(_fromUtf8("STDPathBtn"))
        self.gridLayout.addWidget(self.STDPathBtn, 11, 4, 1, 1)
        self.zBrushPathBtn = QtGui.QPushButton(AstRefPub)
        self.zBrushPathBtn.setObjectName(_fromUtf8("zBrushPathBtn"))
        self.gridLayout.addWidget(self.zBrushPathBtn, 5, 4, 1, 1)
        self.zBrushPathEdit = QtGui.QLineEdit(AstRefPub)
        self.zBrushPathEdit.setBaseSize(QtCore.QSize(0, 0))
        self.zBrushPathEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zBrushPathEdit.setReadOnly(True)
        self.zBrushPathEdit.setObjectName(_fromUtf8("zBrushPathEdit"))
        self.gridLayout.addWidget(self.zBrushPathEdit, 5, 1, 1, 3)
        self.assetTitleEdit = QtGui.QLineEdit(AstRefPub)
        self.assetTitleEdit.setBaseSize(QtCore.QSize(0, 0))
        self.assetTitleEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.assetTitleEdit.setObjectName(_fromUtf8("assetTitleEdit"))
        self.gridLayout.addWidget(self.assetTitleEdit, 0, 1, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 3)
        self.takePicBtn = QtGui.QPushButton(AstRefPub)
        self.takePicBtn.setObjectName(_fromUtf8("takePicBtn"))
        self.gridLayout_2.addWidget(self.takePicBtn, 2, 1, 1, 2)
        self.importPicBtn = QtGui.QPushButton(AstRefPub)
        self.importPicBtn.setObjectName(_fromUtf8("importPicBtn"))
        self.gridLayout_2.addWidget(self.importPicBtn, 2, 0, 1, 1)
        self.imgLabel = previewWidget(AstRefPub)
        self.imgLabel.setMinimumSize(QtCore.QSize(260, 169))
        self.imgLabel.setMaximumSize(QtCore.QSize(260, 169))
        self.imgLabel.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.imgLabel.setText(_fromUtf8(""))
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName(_fromUtf8("imgLabel"))
        self.gridLayout_2.addWidget(self.imgLabel, 1, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(AstRefPub)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.tagsTextEdit = QtGui.QTextEdit(AstRefPub)
        self.tagsTextEdit.setObjectName(_fromUtf8("tagsTextEdit"))
        self.verticalLayout_2.addWidget(self.tagsTextEdit)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(AstRefPub)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.descTextEdit = QtGui.QTextEdit(AstRefPub)
        self.descTextEdit.setObjectName(_fromUtf8("descTextEdit"))
        self.verticalLayout.addWidget(self.descTextEdit)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(645, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.resetBtn = QtGui.QPushButton(AstRefPub)
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.horizontalLayout.addWidget(self.resetBtn)
        self.closeBtn = QtGui.QPushButton(AstRefPub)
        self.closeBtn.setObjectName(_fromUtf8("closeBtn"))
        self.horizontalLayout.addWidget(self.closeBtn)
        self.publishBtn = QtGui.QPushButton(AstRefPub)
        self.publishBtn.setObjectName(_fromUtf8("publishBtn"))
        self.horizontalLayout.addWidget(self.publishBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 1, 1, 1)

        self.retranslateUi(AstRefPub)
        QtCore.QMetaObject.connectSlotsByName(AstRefPub)

    def retranslateUi(self, AstRefPub):
        AstRefPub.setWindowTitle(_translate("AstRefPub", "Asset Reference Publish by daeseok.chae", None))
        self.label_7.setText(_translate("AstRefPub", "Asset Path", None))
        self.assetPathBtn.setText(_translate("AstRefPub", "...", None))
        self.label_6.setText(_translate("AstRefPub", "Texture Path", None))
        self.texturePathBtn.setText(_translate("AstRefPub", "...", None))
        self.label_3.setText(_translate("AstRefPub", "Mari Path", None))
        self.mariPathBtn.setText(_translate("AstRefPub", "...", None))
        self.label_8.setText(_translate("AstRefPub", "AssetTitle", None))
        self.label_9.setText(_translate("AstRefPub", "Asset Type", None))
        self.typeComboBox.setItemText(0, _translate("AstRefPub", "char", None))
        self.typeComboBox.setItemText(1, _translate("AstRefPub", "prop", None))
        self.typeComboBox.setItemText(2, _translate("AstRefPub", "env", None))
        self.typeComboBox.setItemText(3, _translate("AstRefPub", "vehicle", None))
        self.label_11.setText(_translate("AstRefPub", "Category", None))
        self.label_12.setText(_translate("AstRefPub", "ZBrush Path", None))
        self.label_marv.setText(_translate("AstRefPub", "Marv Path", None))
        self.label_5.setText(_translate("AstRefPub", "Hair Path", None))
        self.label_2.setText(_translate("AstRefPub", "Shader Path", None))
        self.shaderPathBtn.setText(_translate("AstRefPub", "...", None))
        self.marvPathBtn.setText(_translate("AstRefPub", "...", None))
        self.hairPathBtn.setText(_translate("AstRefPub", "...", None))
        self.STDPathBtn.setText(_translate("AstRefPub", "...", None))
        self.zBrushPathBtn.setText(_translate("AstRefPub", "...", None))
        self.takePicBtn.setText(_translate("AstRefPub", "take Picture", None))
        self.importPicBtn.setText(_translate("AstRefPub", "Capture Viewport", None))
        self.label.setText(_translate("AstRefPub", "Tags", None))
        self.label_10.setText(_translate("AstRefPub", "Description", None))
        self.label_13.setText(_translate("AstRefPub", "SpeedTree Path", None))
        self.resetBtn.setText(_translate("AstRefPub", "Reset", None))
        self.closeBtn.setText(_translate("AstRefPub", "Close", None))
        self.publishBtn.setText(_translate("AstRefPub", "Publish", None))

class previewWidget(QtGui.QLabel):
    def __init__(self, parent):
        QtGui.QLabel.__init__(self, parent)

        self.setAcceptDrops(True)

    def dragEnterEvent(self, event):
        event.accept()

    def dragMoveEvent(self, event):
        event.accept()

    def dropEvent(self, event):
        fileName = event.mimeData().urls()[0].toLocalFile()
        print fileName
        self.parent().setPixmap(fileName)
        event.accept()