# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spanner2_ui.ui'
#
# Created: Tue Mar 13 16:25:10 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtGui
from PySide2 import QtWidgets
from PySide2 import QtCore


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1054, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(1400, 1200))
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout_11 = QtWidgets.QGridLayout(Form)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 734))
        self.frame_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_7.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.filePath_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePath_lineEdit.sizePolicy().hasHeightForWidth())
        self.filePath_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filePath_lineEdit.setFont(font)
        self.filePath_lineEdit.setInputMask(_fromUtf8(""))
        self.filePath_lineEdit.setReadOnly(True)
        self.filePath_lineEdit.setObjectName(_fromUtf8("filePath_lineEdit"))
        self.horizontalLayout_2.addWidget(self.filePath_lineEdit)
        self.openPath_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPath_btn.sizePolicy().hasHeightForWidth())
        self.openPath_btn.setSizePolicy(sizePolicy)
        self.openPath_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openPath_btn.setFont(font)
        self.openPath_btn.setText(_fromUtf8(""))
        self.openPath_btn.setIconSize(QtCore.QSize(30, 30))
        self.openPath_btn.setObjectName(_fromUtf8("openPath_btn"))
        self.horizontalLayout_2.addWidget(self.openPath_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.fileName_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileName_lineEdit.sizePolicy().hasHeightForWidth())
        self.fileName_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fileName_lineEdit.setFont(font)
        self.fileName_lineEdit.setReadOnly(True)
        self.fileName_lineEdit.setObjectName(_fromUtf8("fileName_lineEdit"))
        self.horizontalLayout_3.addWidget(self.fileName_lineEdit)
        self.update_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_btn.sizePolicy().hasHeightForWidth())
        self.update_btn.setSizePolicy(sizePolicy)
        self.update_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.update_btn.setText(_fromUtf8(""))
        self.update_btn.setObjectName(_fromUtf8("update_btn"))
        self.horizontalLayout_3.addWidget(self.update_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addToInventory_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addToInventory_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.addToInventory_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.addToInventory_pushButton.setText(_fromUtf8(""))
        self.addToInventory_pushButton.setObjectName(_fromUtf8("addToInventory_pushButton"))
        self.horizontalLayout.addWidget(self.addToInventory_pushButton)
        self.rig_malfunction_checker_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.rig_malfunction_checker_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.rig_malfunction_checker_pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rig_malfunction_checker_pushButton.setText(_fromUtf8(""))
        self.rig_malfunction_checker_pushButton.setObjectName(_fromUtf8("rig_malfunction_checker_pushButton"))
        self.horizontalLayout.addWidget(self.rig_malfunction_checker_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveDev_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDev_btn.sizePolicy().hasHeightForWidth())
        self.saveDev_btn.setSizePolicy(sizePolicy)
        self.saveDev_btn.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveDev_btn.setFont(font)
        self.saveDev_btn.setObjectName(_fromUtf8("saveDev_btn"))
        self.horizontalLayout.addWidget(self.saveDev_btn)
        self.savePub_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePub_btn.sizePolicy().hasHeightForWidth())
        self.savePub_btn.setSizePolicy(sizePolicy)
        self.savePub_btn.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.savePub_btn.setFont(font)
        self.savePub_btn.setObjectName(_fromUtf8("savePub_btn"))
        self.horizontalLayout.addWidget(self.savePub_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(570, 0))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_17 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_13.addWidget(self.label_17, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem3, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_13.addWidget(self.label_18, 0, 4, 1, 1)
        self.name_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.gridLayout_13.addWidget(self.name_label, 0, 5, 1, 1)
        self.show_comboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_comboBox.sizePolicy().hasHeightForWidth())
        self.show_comboBox.setSizePolicy(sizePolicy)
        self.show_comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.show_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.show_comboBox.setFont(font)
        self.show_comboBox.setStyleSheet(_fromUtf8("QComboBox QAbstractItemView::item{margin-top: 5px;}"))
        self.show_comboBox.setEditable(False)
        self.show_comboBox.setMaxVisibleItems(10)
        self.show_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.show_comboBox.setMinimumContentsLength(0)
        self.show_comboBox.setIconSize(QtCore.QSize(25, 50))
        self.show_comboBox.setFrame(True)
        self.show_comboBox.setObjectName(_fromUtf8("show_comboBox"))
        self.gridLayout_13.addWidget(self.show_comboBox, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.comboBox.setAcceptDrops(True)
        self.comboBox.setEditable(False)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_13.addWidget(self.comboBox, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.task_tab = QtWidgets.QTabWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_tab.sizePolicy().hasHeightForWidth())
        self.task_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_tab.setFont(font)
        self.task_tab.setObjectName(_fromUtf8("task_tab"))
        self.asset_tab = QtWidgets.QWidget()
        self.asset_tab.setObjectName(_fromUtf8("asset_tab"))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.asset_tab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.assetType_listWidget = QtWidgets.QListWidget(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetType_listWidget.sizePolicy().hasHeightForWidth())
        self.assetType_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assetType_listWidget.setFont(font)
        self.assetType_listWidget.setObjectName(_fromUtf8("assetType_listWidget"))
        self.gridLayout_8.addWidget(self.assetType_listWidget, 1, 0, 1, 2)
        self.addAssetName_btn = QtWidgets.QPushButton(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAssetName_btn.sizePolicy().hasHeightForWidth())
        self.addAssetName_btn.setSizePolicy(sizePolicy)
        self.addAssetName_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addAssetName_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addAssetName_btn.setFont(font)
        self.addAssetName_btn.setObjectName(_fromUtf8("addAssetName_btn"))
        self.gridLayout_8.addWidget(self.addAssetName_btn, 0, 4, 1, 1)
        self.findAsset_lineEdit = QtWidgets.QLineEdit(self.asset_tab)
        self.findAsset_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.findAsset_lineEdit.setFont(font)
        self.findAsset_lineEdit.setObjectName(_fromUtf8("findAsset_lineEdit"))
        self.gridLayout_8.addWidget(self.findAsset_lineEdit, 0, 3, 1, 1)
        self.addWorkCode_btn = QtWidgets.QPushButton(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addWorkCode_btn.sizePolicy().hasHeightForWidth())
        self.addWorkCode_btn.setSizePolicy(sizePolicy)
        self.addWorkCode_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addWorkCode_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addWorkCode_btn.setFont(font)
        self.addWorkCode_btn.setObjectName(_fromUtf8("addWorkCode_btn"))
        self.gridLayout_8.addWidget(self.addWorkCode_btn, 0, 6, 1, 1)
        self.addAssetType_btn = QtWidgets.QPushButton(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAssetType_btn.sizePolicy().hasHeightForWidth())
        self.addAssetType_btn.setSizePolicy(sizePolicy)
        self.addAssetType_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addAssetType_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addAssetType_btn.setFont(font)
        self.addAssetType_btn.setObjectName(_fromUtf8("addAssetType_btn"))
        self.gridLayout_8.addWidget(self.addAssetType_btn, 0, 1, 1, 1)
        self.asset_listWidget = QtWidgets.QListWidget(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_listWidget.sizePolicy().hasHeightForWidth())
        self.asset_listWidget.setSizePolicy(sizePolicy)
        self.asset_listWidget.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.asset_listWidget.setFont(font)
        self.asset_listWidget.setObjectName(_fromUtf8("asset_listWidget"))
        self.gridLayout_8.addWidget(self.asset_listWidget, 1, 2, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.workCode_listWidget = QtWidgets.QListWidget(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workCode_listWidget.sizePolicy().hasHeightForWidth())
        self.workCode_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workCode_listWidget.setFont(font)
        self.workCode_listWidget.setObjectName(_fromUtf8("workCode_listWidget"))
        self.gridLayout_8.addWidget(self.workCode_listWidget, 1, 5, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 0, 5, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 0, 0, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_15 = QtWidgets.QLabel(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.assetOpenDevPreview_btn = QtWidgets.QPushButton(self.asset_tab)
        self.assetOpenDevPreview_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.assetOpenDevPreview_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.assetOpenDevPreview_btn.setText(_fromUtf8(""))
        self.assetOpenDevPreview_btn.setIconSize(QtCore.QSize(20, 20))
        self.assetOpenDevPreview_btn.setObjectName(_fromUtf8("assetOpenDevPreview_btn"))
        self.horizontalLayout_6.addWidget(self.assetOpenDevPreview_btn)
        self.label_16 = QtWidgets.QLabel(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.assetOpenPubPreview_btn = QtWidgets.QPushButton(self.asset_tab)
        self.assetOpenPubPreview_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.assetOpenPubPreview_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.assetOpenPubPreview_btn.setText(_fromUtf8(""))
        self.assetOpenPubPreview_btn.setIconSize(QtCore.QSize(20, 20))
        self.assetOpenPubPreview_btn.setObjectName(_fromUtf8("assetOpenPubPreview_btn"))
        self.horizontalLayout_6.addWidget(self.assetOpenPubPreview_btn)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 1, 0, 1, 3)
        self.mb_radioButton = QtWidgets.QRadioButton(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mb_radioButton.sizePolicy().hasHeightForWidth())
        self.mb_radioButton.setSizePolicy(sizePolicy)
        self.mb_radioButton.setObjectName(_fromUtf8("mb_radioButton"))
        self.gridLayout_12.addWidget(self.mb_radioButton, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.asset_tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.assetDev_listWidget = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetDev_listWidget.sizePolicy().hasHeightForWidth())
        self.assetDev_listWidget.setSizePolicy(sizePolicy)
        self.assetDev_listWidget.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assetDev_listWidget.setFont(font)
        self.assetDev_listWidget.setObjectName(_fromUtf8("assetDev_listWidget"))
        self.assetPub_listWidget = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetPub_listWidget.sizePolicy().hasHeightForWidth())
        self.assetPub_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assetPub_listWidget.setFont(font)
        self.assetPub_listWidget.setObjectName(_fromUtf8("assetPub_listWidget"))
        self.gridLayout_12.addWidget(self.splitter, 2, 0, 1, 3)
        self.ma_radioButton = QtWidgets.QRadioButton(self.asset_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ma_radioButton.sizePolicy().hasHeightForWidth())
        self.ma_radioButton.setSizePolicy(sizePolicy)
        self.ma_radioButton.setObjectName(_fromUtf8("ma_radioButton"))
        self.gridLayout_12.addWidget(self.ma_radioButton, 3, 1, 1, 1)
        self.task_tab.addTab(self.asset_tab, _fromUtf8(""))
        self.shot_tab = QtWidgets.QWidget()
        self.shot_tab.setObjectName(_fromUtf8("shot_tab"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.shot_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_21 = QtWidgets.QLabel(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 0, 0, 1, 1)
        self.addShotType_btn = QtWidgets.QPushButton(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addShotType_btn.sizePolicy().hasHeightForWidth())
        self.addShotType_btn.setSizePolicy(sizePolicy)
        self.addShotType_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addShotType_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addShotType_btn.setFont(font)
        self.addShotType_btn.setObjectName(_fromUtf8("addShotType_btn"))
        self.gridLayout_9.addWidget(self.addShotType_btn, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        self.label_19.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 0, 2, 1, 1)
        self.findShot_lineEdit = QtWidgets.QLineEdit(self.shot_tab)
        self.findShot_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.findShot_lineEdit.setObjectName(_fromUtf8("findShot_lineEdit"))
        self.gridLayout_9.addWidget(self.findShot_lineEdit, 0, 3, 1, 1)
        self.addShotName_btn = QtWidgets.QPushButton(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addShotName_btn.sizePolicy().hasHeightForWidth())
        self.addShotName_btn.setSizePolicy(sizePolicy)
        self.addShotName_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addShotName_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addShotName_btn.setFont(font)
        self.addShotName_btn.setObjectName(_fromUtf8("addShotName_btn"))
        self.gridLayout_9.addWidget(self.addShotName_btn, 0, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 0, 5, 1, 1)
        self.addShotWorkCode_btn = QtWidgets.QPushButton(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addShotWorkCode_btn.sizePolicy().hasHeightForWidth())
        self.addShotWorkCode_btn.setSizePolicy(sizePolicy)
        self.addShotWorkCode_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.addShotWorkCode_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addShotWorkCode_btn.setFont(font)
        self.addShotWorkCode_btn.setObjectName(_fromUtf8("addShotWorkCode_btn"))
        self.gridLayout_9.addWidget(self.addShotWorkCode_btn, 0, 6, 1, 1)
        self.shotType_listWidget = QtWidgets.QListWidget(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotType_listWidget.sizePolicy().hasHeightForWidth())
        self.shotType_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shotType_listWidget.setFont(font)
        self.shotType_listWidget.setObjectName(_fromUtf8("shotType_listWidget"))
        self.gridLayout_9.addWidget(self.shotType_listWidget, 1, 0, 1, 2)
        self.shot_listWidget = QtWidgets.QListWidget(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_listWidget.sizePolicy().hasHeightForWidth())
        self.shot_listWidget.setSizePolicy(sizePolicy)
        self.shot_listWidget.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shot_listWidget.setFont(font)
        self.shot_listWidget.setObjectName(_fromUtf8("shot_listWidget"))
        self.gridLayout_9.addWidget(self.shot_listWidget, 1, 2, 1, 3)
        self.shotWorkCode_listWidget = QtWidgets.QListWidget(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotWorkCode_listWidget.sizePolicy().hasHeightForWidth())
        self.shotWorkCode_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shotWorkCode_listWidget.setFont(font)
        self.shotWorkCode_listWidget.setObjectName(_fromUtf8("shotWorkCode_listWidget"))
        self.gridLayout_9.addWidget(self.shotWorkCode_listWidget, 1, 5, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 0, 1, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.splitter_2.setFont(font)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.shotDev_listWidget = QtWidgets.QListWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotDev_listWidget.sizePolicy().hasHeightForWidth())
        self.shotDev_listWidget.setSizePolicy(sizePolicy)
        self.shotDev_listWidget.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shotDev_listWidget.setFont(font)
        self.shotDev_listWidget.setObjectName(_fromUtf8("shotDev_listWidget"))
        self.shotPub_listWidget = QtWidgets.QListWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotPub_listWidget.sizePolicy().hasHeightForWidth())
        self.shotPub_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shotPub_listWidget.setFont(font)
        self.shotPub_listWidget.setObjectName(_fromUtf8("shotPub_listWidget"))
        self.gridLayout_3.addWidget(self.splitter_2, 2, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_23 = QtWidgets.QLabel(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.shot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 1, 1)
        self.shotOpenDevPreview_btn = QtWidgets.QPushButton(self.shot_tab)
        self.shotOpenDevPreview_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.shotOpenDevPreview_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.shotOpenDevPreview_btn.setText(_fromUtf8(""))
        self.shotOpenDevPreview_btn.setIconSize(QtCore.QSize(20, 20))
        self.shotOpenDevPreview_btn.setObjectName(_fromUtf8("shotOpenDevPreview_btn"))
        self.gridLayout_2.addWidget(self.shotOpenDevPreview_btn, 0, 1, 1, 1)
        self.shotOpenPubDataPreview_btn = QtWidgets.QPushButton(self.shot_tab)
        self.shotOpenPubDataPreview_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.shotOpenPubDataPreview_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.shotOpenPubDataPreview_btn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.shotOpenPubDataPreview_btn.setIconSize(QtCore.QSize(20, 20))
        self.shotOpenPubDataPreview_btn.setObjectName(_fromUtf8("shotOpenPubDataPreview_btn"))
        self.gridLayout_2.addWidget(self.shotOpenPubDataPreview_btn, 0, 4, 1, 1)
        self.shotOpenPubPreview_btn = QtWidgets.QPushButton(self.shot_tab)
        self.shotOpenPubPreview_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.shotOpenPubPreview_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.shotOpenPubPreview_btn.setText(_fromUtf8(""))
        self.shotOpenPubPreview_btn.setIconSize(QtCore.QSize(20, 20))
        self.shotOpenPubPreview_btn.setObjectName(_fromUtf8("shotOpenPubPreview_btn"))
        self.gridLayout_2.addWidget(self.shotOpenPubPreview_btn, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.task_tab.addTab(self.shot_tab, _fromUtf8(""))
        self.myTask_tab = QtWidgets.QWidget()
        self.myTask_tab.setObjectName(_fromUtf8("myTask_tab"))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.myTask_tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_7 = QtWidgets.QLabel(self.myTask_tab)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 0, 0, 1, 1)
        self.team_comboBox = QtWidgets.QComboBox(self.myTask_tab)
        self.team_comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.team_comboBox.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.team_comboBox.setFont(font)
        self.team_comboBox.setObjectName(_fromUtf8("team_comboBox"))
        self.gridLayout_10.addWidget(self.team_comboBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.myTask_tab)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 0, 2, 1, 1)
        self.name_comboBox = QtWidgets.QComboBox(self.myTask_tab)
        self.name_comboBox.setMinimumSize(QtCore.QSize(120, 30))
        self.name_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_comboBox.setFont(font)
        self.name_comboBox.setObjectName(_fromUtf8("name_comboBox"))
        self.gridLayout_10.addWidget(self.name_comboBox, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 4, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtWidgets.QLabel(self.myTask_tab)
        self.label_6.setMaximumSize(QtCore.QSize(10, 10))
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(203, 203, 203);"))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_27 = QtWidgets.QLabel(self.myTask_tab)
        self.label_27.setMinimumSize(QtCore.QSize(40, 0))
        self.label_27.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_7.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.myTask_tab)
        self.label_28.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("background-color: rgb(253, 255, 107);"))
        self.label_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_28.setLineWidth(1)
        self.label_28.setMidLineWidth(0)
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_7.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.myTask_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_7.addWidget(self.label_29)
        self.label_31 = QtWidgets.QLabel(self.myTask_tab)
        self.label_31.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet(_fromUtf8("background-color: rgb(255, 177, 20);"))
        self.label_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setLineWidth(1)
        self.label_31.setMidLineWidth(0)
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_7.addWidget(self.label_31)
        self.label_30 = QtWidgets.QLabel(self.myTask_tab)
        self.label_30.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_7.addWidget(self.label_30)
        self.label_35 = QtWidgets.QLabel(self.myTask_tab)
        self.label_35.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("background-color: rgb(42, 255, 120);"))
        self.label_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_7.addWidget(self.label_35)
        self.label_34 = QtWidgets.QLabel(self.myTask_tab)
        self.label_34.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_7.addWidget(self.label_34)
        self.label_37 = QtWidgets.QLabel(self.myTask_tab)
        self.label_37.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet(_fromUtf8("background-color: rgb(73, 252, 255);"))
        self.label_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_7.addWidget(self.label_37)
        self.label_36 = QtWidgets.QLabel(self.myTask_tab)
        self.label_36.setMinimumSize(QtCore.QSize(30, 0))
        self.label_36.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_7.addWidget(self.label_36)
        self.label_38 = QtWidgets.QLabel(self.myTask_tab)
        self.label_38.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(88, 144, 204);"))
        self.label_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_38.setText(_fromUtf8(""))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_7.addWidget(self.label_38)
        self.label_40 = QtWidgets.QLabel(self.myTask_tab)
        self.label_40.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_7.addWidget(self.label_40)
        self.label_33 = QtWidgets.QLabel(self.myTask_tab)
        self.label_33.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("background-color: rgb(255, 123, 125);"))
        self.label_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_7.addWidget(self.label_33)
        self.label_32 = QtWidgets.QLabel(self.myTask_tab)
        self.label_32.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_7.addWidget(self.label_32)
        self.label_43 = QtWidgets.QLabel(self.myTask_tab)
        self.label_43.setMaximumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet(_fromUtf8("background-color: rgb(130, 130, 130);"))
        self.label_43.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_43.setText(_fromUtf8(""))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_7.addWidget(self.label_43)
        self.label_39 = QtWidgets.QLabel(self.myTask_tab)
        self.label_39.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_7.addWidget(self.label_39)
        self.gridLayout_10.addLayout(self.horizontalLayout_7, 1, 0, 1, 5)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.nonMyAsset_listWidget = QtWidgets.QListWidget(self.myTask_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nonMyAsset_listWidget.setFont(font)
        self.nonMyAsset_listWidget.setObjectName(_fromUtf8("nonMyAsset_listWidget"))
        self.gridLayout_5.addWidget(self.nonMyAsset_listWidget, 0, 2, 1, 1)
        self.myAsset_listWidget = QtWidgets.QListWidget(self.myTask_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.myAsset_listWidget.setFont(font)
        self.myAsset_listWidget.setStyleSheet(_fromUtf8(""))
        self.myAsset_listWidget.setObjectName(_fromUtf8("myAsset_listWidget"))
        self.gridLayout_5.addWidget(self.myAsset_listWidget, 0, 0, 1, 1)
        self.nonMyShot_listWidget = QtWidgets.QListWidget(self.myTask_tab)
        self.nonMyShot_listWidget.setMinimumSize(QtCore.QSize(110, 0))
        self.nonMyShot_listWidget.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nonMyShot_listWidget.setFont(font)
        self.nonMyShot_listWidget.setObjectName(_fromUtf8("nonMyShot_listWidget"))
        self.gridLayout_5.addWidget(self.nonMyShot_listWidget, 0, 3, 1, 1)
        self.myShotName_listWidget = QtWidgets.QListWidget(self.myTask_tab)
        self.myShotName_listWidget.setMinimumSize(QtCore.QSize(110, 0))
        self.myShotName_listWidget.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.myShotName_listWidget.setFont(font)
        self.myShotName_listWidget.setObjectName(_fromUtf8("myShotName_listWidget"))
        self.gridLayout_5.addWidget(self.myShotName_listWidget, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 4, 0, 1, 5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_10.addItem(spacerItem5, 5, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_26 = QtWidgets.QLabel(self.myTask_tab)
        self.label_26.setMinimumSize(QtCore.QSize(110, 0))
        self.label_26.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.myTask_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.myTask_tab)
        self.label_24.setMinimumSize(QtCore.QSize(110, 0))
        self.label_24.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.myTask_tab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 3, 0, 1, 5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtWidgets.QLabel(self.myTask_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("background-color: rgb(112, 170, 73);\n"
"color: rgb(232, 232, 232);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.myTask_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(69, 137, 209);\n"
"color: rgb(232, 232, 232);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 2, 0, 1, 5)
        self.task_tab.addTab(self.myTask_tab, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.task_tab, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setMinimumSize(QtCore.QSize(430, 650))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame1.setFont(font)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 7, 0, 1, 1)
        self.snapShot_pushButton = QtWidgets.QPushButton(self.frame1)
        self.snapShot_pushButton.setObjectName(_fromUtf8("snapShot_pushButton"))
        self.gridLayout_6.addWidget(self.snapShot_pushButton, 2, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 5, 0, 1, 1)
        self.history_treeWidget = QtWidgets.QTreeWidget(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_treeWidget.sizePolicy().hasHeightForWidth())
        self.history_treeWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.history_treeWidget.setFont(font)
        self.history_treeWidget.setStyleSheet(_fromUtf8("QTreeWidget:item:selected{background:rgb(232, 155, 0);}"))
        self.history_treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.history_treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.history_treeWidget.setAutoScrollMargin(16)
        self.history_treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.history_treeWidget.setTabKeyNavigation(False)
        self.history_treeWidget.setProperty("showDropIndicator", False)
        self.history_treeWidget.setAlternatingRowColors(False)
        self.history_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.history_treeWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.history_treeWidget.setIndentation(50)
        self.history_treeWidget.setRootIsDecorated(False)
        self.history_treeWidget.setUniformRowHeights(True)
        self.history_treeWidget.setItemsExpandable(True)
        self.history_treeWidget.setAnimated(False)
        self.history_treeWidget.setAllColumnsShowFocus(False)
        self.history_treeWidget.setExpandsOnDoubleClick(True)
        self.history_treeWidget.setObjectName(_fromUtf8("history_treeWidget"))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.history_treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.history_treeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.history_treeWidget.headerItem().setFont(2, font)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.history_treeWidget.headerItem().setFont(3, font)
        self.history_treeWidget.header().setVisible(True)
        self.history_treeWidget.header().setCascadingSectionResizes(True)
        self.history_treeWidget.header().setDefaultSectionSize(50)
        self.history_treeWidget.header().setHighlightSections(False)
        self.history_treeWidget.header().setMinimumSectionSize(18)
        self.history_treeWidget.header().setSortIndicatorShown(True)
        self.history_treeWidget.header().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.history_treeWidget, 4, 0, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.snapshot_label = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshot_label.sizePolicy().hasHeightForWidth())
        self.snapshot_label.setSizePolicy(sizePolicy)
        self.snapshot_label.setMinimumSize(QtCore.QSize(350, 230))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.snapshot_label.setFont(font)
        self.snapshot_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.snapshot_label.setText(_fromUtf8(""))
        self.snapshot_label.setScaledContents(True)
        self.snapshot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.snapshot_label.setOpenExternalLinks(True)
        self.snapshot_label.setObjectName(_fromUtf8("snapshot_label"))
        self.gridLayout_6.addWidget(self.snapshot_label, 1, 0, 1, 4)
        self.comment_textEdit = QtWidgets.QTextEdit(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_textEdit.sizePolicy().hasHeightForWidth())
        self.comment_textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_textEdit.setFont(font)
        self.comment_textEdit.setObjectName(_fromUtf8("comment_textEdit"))
        self.gridLayout_6.addWidget(self.comment_textEdit, 6, 0, 1, 4)
        self.editNote_btn = QtWidgets.QPushButton(self.frame1)
        self.editNote_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.editNote_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.editNote_btn.setText(_fromUtf8(""))
        self.editNote_btn.setIconSize(QtCore.QSize(20, 20))
        self.editNote_btn.setObjectName(_fromUtf8("editNote_btn"))
        self.gridLayout_6.addWidget(self.editNote_btn, 7, 3, 1, 1)
        self.saveNote_btn = QtWidgets.QPushButton(self.frame1)
        self.saveNote_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.saveNote_btn.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveNote_btn.setFont(font)
        self.saveNote_btn.setIconSize(QtCore.QSize(20, 20))
        self.saveNote_btn.setObjectName(_fromUtf8("saveNote_btn"))
        self.gridLayout_6.addWidget(self.saveNote_btn, 7, 2, 1, 1)
        self.gridLayout_11.addWidget(self.frame1, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.show_comboBox.setCurrentIndex(-1)
        self.task_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_2.setTitle(_translate("Form", "Currently Open", None))
        self.label_2.setText(_translate("Form", "File Path:", None))
        self.label.setText(_translate("Form", "File Name:", None))
        self.saveDev_btn.setText(_translate("Form", "Save Devel", None))
        self.savePub_btn.setText(_translate("Form", "Save Publish", None))
        self.label_17.setText(_translate("Form", "Show", None))
        self.label_18.setText(_translate("Form", "Name", None))
        self.name_label.setText(_translate("Form", "jungmin.leer", None))
        self.addAssetName_btn.setText(_translate("Form", "+", None))
        self.addWorkCode_btn.setText(_translate("Form", "+", None))
        self.addAssetType_btn.setText(_translate("Form", "+", None))
        self.label_13.setText(_translate("Form", "Name", None))
        self.label_12.setText(_translate("Form", "Asset Type", None))
        self.label_14.setText(_translate("Form", "Work Code", None))
        self.label_15.setText(_translate("Form", "Devel View", None))
        self.label_16.setText(_translate("Form", "Publish View", None))
        self.mb_radioButton.setText(_translate("Form", "mb", None))
        self.ma_radioButton.setText(_translate("Form", "ma", None))
        self.task_tab.setTabText(self.task_tab.indexOf(self.asset_tab), _translate("Form", "Asset", None))
        self.label_21.setText(_translate("Form", "Shot Type", None))
        self.addShotType_btn.setText(_translate("Form", "+", None))
        self.label_19.setText(_translate("Form", "Name", None))
        self.addShotName_btn.setText(_translate("Form", "+", None))
        self.label_22.setText(_translate("Form", "Work Code", None))
        self.addShotWorkCode_btn.setText(_translate("Form", "+", None))
        self.label_23.setText(_translate("Form", "Devel View", None))
        self.label_20.setText(_translate("Form", "Publish View", None))
        self.shotOpenPubDataPreview_btn.setText(_translate("Form", "D", None))
        self.task_tab.setTabText(self.task_tab.indexOf(self.shot_tab), _translate("Form", "Shot", None))
        self.label_7.setText(_translate("Form", "Team", None))
        self.label_8.setText(_translate("Form", "Name", None))
        self.label_27.setText(_translate("Form", "Waiting", None))
        self.label_29.setText(_translate("Form", " Ready", None))
        self.label_30.setText(_translate("Form", "In-progress", None))
        self.label_34.setText(_translate("Form", "Review", None))
        self.label_36.setText(_translate("Form", "OK", None))
        self.label_40.setText(_translate("Form", "Approved", None))
        self.label_32.setText(_translate("Form", "Retake", None))
        self.label_39.setText(_translate("Form", "Omit, Hold", None))
        self.label_26.setText(_translate("Form", "Shot", None))
        self.label_5.setText(_translate("Form", "Asset", None))
        self.label_24.setText(_translate("Form", "Shot", None))
        self.label_25.setText(_translate("Form", "Asset", None))
        self.label_4.setText(_translate("Form", "  Working", None))
        self.label_3.setText(_translate("Form", "  Non Working", None))
        self.task_tab.setTabText(self.task_tab.indexOf(self.myTask_tab), _translate("Form", "My Task", None))
        self.label_10.setText(_translate("Form", "history", None))
        self.snapShot_pushButton.setText(_translate("Form", "  Take Snapshot", None))
        self.label_9.setText(_translate("Form", "note", None))
        self.history_treeWidget.setSortingEnabled(True)
        self.history_treeWidget.headerItem().setText(0, _translate("Form", "Author", None))
        self.history_treeWidget.headerItem().setText(1, _translate("Form", "Event", None))
        self.history_treeWidget.headerItem().setText(2, _translate("Form", "file", None))
        self.history_treeWidget.headerItem().setText(3, _translate("Form", "Date (M/D/Y h:m:s)", None))
        self.label_11.setText(_translate("Form", "snapshot", None))
        self.saveNote_btn.setText(_translate("Form", "+ Note", None))


