# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sendTractor.ui'
#
# Created: Fri Jan  3 16:29:45 2020
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtWidgets
from PySide2 import QtGui
from PySide2 import QtCore

from dxConfig import dxConfig 

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(544, 582)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 230))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_3.addWidget(self.spinBox, 1, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_3.addWidget(self.spinBox_2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_3.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_3.addWidget(self.spinBox_4, 3, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 4, 3, 1, 1)
        self.serviceLabel = QtWidgets.QLabel(self.groupBox_2)
        self.serviceLabel.setText(_fromUtf8(""))
        self.serviceLabel.setObjectName(_fromUtf8("serviceLabel"))
        self.gridLayout_3.addWidget(self.serviceLabel, 2, 3, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_3, 5, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_3.addWidget(self.checkBox_2, 5, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        # self.comboBox_4.addItem(_fromUtf8(""))
        # self.comboBox_4.addItem(_fromUtf8(""))
        # self.comboBox_4.addItem(_fromUtf8(""))
        # self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_4, 0, 1, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_4.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Tractor Setting", None))
        self.label.setText(_translate("Dialog", "Shot Duration", None))
        self.label_2.setText(_translate("Dialog", "Frames Per Blade", None))
        self.label_4.setText(_translate("Dialog", "Priority", None))
        self.checkBox.setText(_translate("Dialog", "Input", None))
        self.label_3.setText(_translate("Dialog", "Limit Tag", None))
        self.comboBox.setItemText(0, _translate("Dialog", "None", None))
        self.comboBox.setItemText(1, _translate("Dialog", "5", None))
        self.comboBox.setItemText(2, _translate("Dialog", "10", None))
        self.comboBox.setItemText(3, _translate("Dialog", "20", None))
        self.comboBox.setItemText(4, _translate("Dialog", "30", None))
        self.comboBox.setItemText(5, _translate("Dialog", "40", None))
        self.comboBox.setItemText(6, _translate("Dialog", "50", None))
        self.comboBox.setItemText(7, _translate("Dialog", "60", None))
        self.comboBox.setItemText(8, _translate("Dialog", "70", None))
        self.comboBox.setItemText(9, _translate("Dialog", "80", None))
        self.comboBox.setItemText(10, _translate("Dialog", "90", None))
        self.comboBox.setItemText(11, _translate("Dialog", "100", None))
        self.comboBox.setItemText(12, _translate("Dialog", "12", None))
        self.comboBox.setItemText(13, _translate("Dialog", "24", None))
        self.comboBox.setItemText(14, _translate("Dialog", "36", None))
        self.comboBox.setItemText(15, _translate("Dialog", "48", None))
        self.label_5.setText(_translate("Dialog", "Service Key :", None))
        self.label_6.setText(_translate("Dialog", "FPS", None))
        self.comboBox_3.setItemText(0, _translate("Dialog", "24", None))
        self.comboBox_3.setItemText(1, _translate("Dialog", "23.98", None))
        self.comboBox_3.setItemText(2, _translate("Dialog", "23.976", None))
        self.comboBox_3.setItemText(3, _translate("Dialog", "29.97", None))
        self.comboBox_3.setItemText(4, _translate("Dialog", "30", None))
        self.comboBox_3.setItemText(5, _translate("Dialog", "48", None))
        self.comboBox_3.setItemText(6, _translate("Dialog", "60", None))
        self.checkBox_2.setText(_translate("Dialog", "Auto Play", None))
        self.label_7.setText(_translate("Dialog", "Engine", None))

        for index, tractorIP in enumerate(dxConfig.getConf("TRACTOR_NUKE_IP")):
            self.comboBox_4.addItem(tractorIP)
        # self.comboBox_4.setItemText(0, _translate("Dialog", "10.0.0.71", None))
        # self.comboBox_4.setItemText(1, _translate("Dialog", "10.0.0.35", None))
        # self.comboBox_4.setItemText(2, _translate("Dialog", "10.0.0.30", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Write Nodes", None))
