# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AssetExportUI.ui'
#
# Created: Fri Nov 30 16:47:56 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore
from PySide2 import QtWidgets
from PySide2 import QtGui

import os
currentDir = os.path.dirname(__file__)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1000, 834)
        # Form.setStyleSheet(_fromUtf8("background-color: rgb(90,90,90)"))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setStyleSheet(_fromUtf8(""))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.headerItem().setText(1, _fromUtf8("2"))
        self.treeWidget.header().resizeSection(0, 800)
        self.treeWidget.header().resizeSection(1, 60)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color : white;padding : 0 5 0 5 px;"))
        # self.label_4.setStyleSheet(_fromUtf8("color : white;background-color: rgb(90,90,90);padding : 0 5 0 5 px;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.showEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.showEdit.setFont(font)
        self.showEdit.setStyleSheet(_fromUtf8("color : white"))
        self.showEdit.setObjectName(_fromUtf8("showEdit"))
        self.horizontalLayout_2.addWidget(self.showEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(62, 115, 186);padding:  0 0 0 20 px;"))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/USDLogo.png" % currentDir)))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(62, 115, 186);color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("background-color: rgb(62, 115, 186);color: rgb(255, 255, 255);"))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.clipCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.clipCheckBox.setFont(font)
        self.clipCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.clipCheckBox.setObjectName(_fromUtf8("clipCheckBox"))
        self.horizontalLayout_3.addWidget(self.clipCheckBox)
        self.elementCheckBox = QtWidgets.QCheckBox(Form)
        self.elementCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.elementCheckBox.setFont(font)
        self.elementCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.elementCheckBox.setObjectName(_fromUtf8("elementCheckBox"))
        self.horizontalLayout_3.addWidget(self.elementCheckBox)
        self.purposeCheckBox = QtWidgets.QCheckBox(Form)
        self.purposeCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.purposeCheckBox.setFont(font)
        self.purposeCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.purposeCheckBox.setObjectName(_fromUtf8("purposeCheckBox"))
        self.horizontalLayout_3.addWidget(self.purposeCheckBox)
        self.lodVariantCheckBox = QtWidgets.QCheckBox(Form)
        self.lodVariantCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lodVariantCheckBox.setFont(font)
        self.lodVariantCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.lodVariantCheckBox.setObjectName(_fromUtf8("lodVariantCheckBox"))
        self.horizontalLayout_3.addWidget(self.lodVariantCheckBox)
        self.stepLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.stepLabel.setFont(font)
        self.stepLabel.setStyleSheet(_fromUtf8("color : white;"))
        self.stepLabel.setObjectName(_fromUtf8("stepLabel"))
        self.horizontalLayout_3.addWidget(self.stepLabel)
        self.stepEdit = QtWidgets.QLineEdit(Form)
        self.stepEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.stepEdit.setFont(font)
        self.stepEdit.setStyleSheet(_fromUtf8("color : white;"))
        self.stepEdit.setText(_fromUtf8(""))
        self.stepEdit.setObjectName(_fromUtf8("stepEdit"))
        self.horizontalLayout_3.addWidget(self.stepEdit)
        self.loopCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopCheckBox.setFont(font)
        self.loopCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.loopCheckBox.setObjectName(_fromUtf8("loopCheckBox"))
        self.horizontalLayout_3.addWidget(self.loopCheckBox)
        self.loopRangeLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopRangeLabel.setFont(font)
        self.loopRangeLabel.setStyleSheet(_fromUtf8("color : white;"))
        self.loopRangeLabel.setObjectName(_fromUtf8("loopRangeLabel"))
        self.horizontalLayout_3.addWidget(self.loopRangeLabel)
        self.loopStartEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopStartEdit.setFont(font)
        self.loopStartEdit.setStyleSheet(_fromUtf8("color : white;"))
        self.loopStartEdit.setObjectName(_fromUtf8("loopStartEdit"))
        self.horizontalLayout_3.addWidget(self.loopStartEdit)
        self.loopEndEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopEndEdit.setFont(font)
        self.loopEndEdit.setStyleSheet(_fromUtf8("color : white;"))
        self.loopEndEdit.setObjectName(_fromUtf8("loopEndEdit"))
        self.horizontalLayout_3.addWidget(self.loopEndEdit)
        self.loopScaleLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopScaleLabel.setFont(font)
        self.loopScaleLabel.setStyleSheet(_fromUtf8("color : white;"))
        self.loopScaleLabel.setObjectName(_fromUtf8("loopScaleLabel"))
        self.horizontalLayout_3.addWidget(self.loopScaleLabel)
        self.loopScaleEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.loopScaleEdit.setFont(font)
        self.loopScaleEdit.setStyleSheet(_fromUtf8("color : white;"))
        self.loopScaleEdit.setObjectName(_fromUtf8("loopScaleEdit"))
        self.horizontalLayout_3.addWidget(self.loopScaleEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.overWriteCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.overWriteCheckBox.setFont(font)
        self.overWriteCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.overWriteCheckBox.setObjectName(_fromUtf8("overWriteCheckBox"))
        self.horizontalLayout_3.addWidget(self.overWriteCheckBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 2)
        self.assetExportBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.assetExportBtn.setFont(font)
        self.assetExportBtn.setStyleSheet(_fromUtf8("color : white;background-color: rgb(62, 109, 186);"))
        self.assetExportBtn.setObjectName(_fromUtf8("assetExportBtn"))
        self.gridLayout.addWidget(self.assetExportBtn, 5, 0, 1, 1)
        self.shotExportBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.shotExportBtn.setFont(font)
        self.shotExportBtn.setStyleSheet(_fromUtf8("color : white;background-color: rgb(62, 109, 186);"))
        self.shotExportBtn.setObjectName(_fromUtf8("shotExportBtn"))
        self.gridLayout.addWidget(self.shotExportBtn, 5, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Asset Usd Export", None))
        self.treeWidget.headerItem().setText(1, _translate("Form", "2", None))
        self.label_4.setText(_translate("Form", "SHOW DIR", None))
        self.showEdit.setText(_translate("Form", "test_pub", None))
        self.label_2.setText(_translate("Form", "ASSET EXPORT", None))
        self.label_3.setText(_translate("Form", "", None))
        self.clipCheckBox.setText(_translate("Form", "Clip", None))
        self.elementCheckBox.setText(_translate("Form", "Element", None))
        self.purposeCheckBox.setText(_translate("Form", "Purpose", None))
        self.lodVariantCheckBox.setText(_translate("Form", "LOD", None))
        self.stepLabel.setText(_translate("Form", "STEP", None))
        self.stepEdit.setPlaceholderText(_translate("Form", "1.0", None))
        self.loopCheckBox.setText(_translate("Form", "Loop", None))
        self.loopRangeLabel.setText(_translate("Form", "Range", None))
        self.loopStartEdit.setPlaceholderText(_translate("Form", "1001", None))
        self.loopEndEdit.setPlaceholderText(_translate("Form", "5000", None))
        self.loopScaleLabel.setText(_translate("Form", "Time Scale", None))
        self.loopScaleEdit.setPlaceholderText(_translate("Form", "0.8, 1.0, 1.5", None))
        self.overWriteCheckBox.setText(_translate("Form", "OverWrite", None))
        self.assetExportBtn.setText(_translate("Form", "ASSET EXPORT", None))
        self.shotExportBtn.setText(_translate("Form", "SHOT EXPORT", None))
