# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './speedTreeToUSDUI.ui',
# licensing of './speedTreeToUSDUI.ui' applies.
#
# Created: Tue Aug 11 19:34:01 2020
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_stu_win(object):
    def setupUi(self, stu_win):
        stu_win.setObjectName("stu_win")
        stu_win.setWindowModality(QtCore.Qt.ApplicationModal)
        stu_win.resize(1150, 827)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stu_win.sizePolicy().hasHeightForWidth())
        stu_win.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(stu_win)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stu_layout_1 = QtWidgets.QHBoxLayout()
        self.stu_layout_1.setSpacing(0)
        self.stu_layout_1.setObjectName("stu_layout_1")
        self.stu_titleLogo_label = QtWidgets.QLabel(stu_win)
        self.stu_titleLogo_label.setMaximumSize(QtCore.QSize(80, 70))
        self.stu_titleLogo_label.setStyleSheet("background-color: rgb(62, 115, 186);\n"
"padding:  7 8 9 18 px;")
        self.stu_titleLogo_label.setText("")
        self.stu_titleLogo_label.setPixmap(QtGui.QPixmap("icons/speedtree_logo.png"))
        self.stu_titleLogo_label.setScaledContents(True)
        self.stu_titleLogo_label.setWordWrap(False)
        self.stu_titleLogo_label.setObjectName("stu_titleLogo_label")
        self.stu_layout_1.addWidget(self.stu_titleLogo_label)
        self.stu_title_label = QtWidgets.QLabel(stu_win)
        self.stu_title_label.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_title_label.setFont(font)
        self.stu_title_label.setStyleSheet("background-color: rgb(62, 115, 186);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.stu_title_label.setScaledContents(False)
        self.stu_title_label.setObjectName("stu_title_label")
        self.stu_layout_1.addWidget(self.stu_title_label)
        self.stu_user_label = QtWidgets.QLabel(stu_win)
        self.stu_user_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_user_label.setFont(font)
        self.stu_user_label.setStyleSheet("background-color: rgb(62, 115, 186);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.stu_user_label.setObjectName("stu_user_label")
        self.stu_layout_1.addWidget(self.stu_user_label)
        self.stu_user_name_label = QtWidgets.QLabel(stu_win)
        self.stu_user_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.stu_user_name_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_user_name_label.setFont(font)
        self.stu_user_name_label.setStyleSheet("background-color: rgb(62, 115, 186);\n"
"color: rgb(255, 255, 255);padding:  0 8 0 5 px;")
        self.stu_user_name_label.setObjectName("stu_user_name_label")
        self.stu_layout_1.addWidget(self.stu_user_name_label)
        self.stu_layout_1.setStretch(1, 1)
        self.verticalLayout.addLayout(self.stu_layout_1)
        self.stu_frame_1 = QtWidgets.QFrame(stu_win)
        self.stu_frame_1.setMinimumSize(QtCore.QSize(900, 0))
        self.stu_frame_1.setAutoFillBackground(False)
        self.stu_frame_1.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.stu_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stu_frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_frame_1.setLineWidth(2)
        self.stu_frame_1.setObjectName("stu_frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stu_frame_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stu_frame_5 = QtWidgets.QFrame(self.stu_frame_1)
        self.stu_frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_frame_5.setObjectName("stu_frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stu_frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stu_layout_15 = QtWidgets.QGridLayout()
        self.stu_layout_15.setContentsMargins(5, 5, 5, 5)
        self.stu_layout_15.setObjectName("stu_layout_15")
        self.stu_xmlFile_lineEdit = QtWidgets.QLineEdit(self.stu_frame_5)
        self.stu_xmlFile_lineEdit.setAutoFillBackground(False)
        self.stu_xmlFile_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_xmlFile_lineEdit.setObjectName("stu_xmlFile_lineEdit")
        self.stu_layout_15.addWidget(self.stu_xmlFile_lineEdit, 2, 1, 1, 1)
        self.stu_label_11 = QtWidgets.QLabel(self.stu_frame_5)
        self.stu_label_11.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_11.setFont(font)
        self.stu_label_11.setStyleSheet("color : white;")
        self.stu_label_11.setObjectName("stu_label_11")
        self.stu_layout_15.addWidget(self.stu_label_11, 0, 0, 1, 1)
        self.stu_xmlFile_find_pushButton = QtWidgets.QPushButton(self.stu_frame_5)
        self.stu_xmlFile_find_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stu_xmlFile_find_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stu_xmlFile_find_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.stu_xmlFile_find_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.stu_xmlFile_find_pushButton.setObjectName("stu_xmlFile_find_pushButton")
        self.stu_layout_15.addWidget(self.stu_xmlFile_find_pushButton, 2, 2, 1, 1)
        self.stu_abcFile_lineEdit = QtWidgets.QLineEdit(self.stu_frame_5)
        self.stu_abcFile_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_abcFile_lineEdit.setObjectName("stu_abcFile_lineEdit")
        self.stu_layout_15.addWidget(self.stu_abcFile_lineEdit, 0, 1, 1, 1)
        self.stu_abcFile_find_pushButton = QtWidgets.QPushButton(self.stu_frame_5)
        self.stu_abcFile_find_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stu_abcFile_find_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stu_abcFile_find_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.stu_abcFile_find_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.stu_abcFile_find_pushButton.setObjectName("stu_abcFile_find_pushButton")
        self.stu_layout_15.addWidget(self.stu_abcFile_find_pushButton, 0, 2, 1, 1)
        self.stu_label_12 = QtWidgets.QLabel(self.stu_frame_5)
        self.stu_label_12.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_12.setFont(font)
        self.stu_label_12.setStyleSheet("color : white;")
        self.stu_label_12.setObjectName("stu_label_12")
        self.stu_layout_15.addWidget(self.stu_label_12, 2, 0, 1, 1)
        self.stu_xmlFile_openDir_pushButton = QtWidgets.QPushButton(self.stu_frame_5)
        self.stu_xmlFile_openDir_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stu_xmlFile_openDir_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stu_xmlFile_openDir_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.stu_xmlFile_openDir_pushButton.setText("")
        self.stu_xmlFile_openDir_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.stu_xmlFile_openDir_pushButton.setObjectName("stu_xmlFile_openDir_pushButton")
        self.stu_layout_15.addWidget(self.stu_xmlFile_openDir_pushButton, 2, 3, 1, 1)
        self.stu_abcFile_openDir_pushButton = QtWidgets.QPushButton(self.stu_frame_5)
        self.stu_abcFile_openDir_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stu_abcFile_openDir_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stu_abcFile_openDir_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.stu_abcFile_openDir_pushButton.setText("")
        self.stu_abcFile_openDir_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.stu_abcFile_openDir_pushButton.setObjectName("stu_abcFile_openDir_pushButton")
        self.stu_layout_15.addWidget(self.stu_abcFile_openDir_pushButton, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.stu_layout_15)
        self.verticalLayout_2.addWidget(self.stu_frame_5)
        self.frame_2 = QtWidgets.QFrame(self.stu_frame_1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stu_layout_16 = QtWidgets.QHBoxLayout()
        self.stu_layout_16.setObjectName("stu_layout_16")
        self.stu_label_6 = QtWidgets.QLabel(self.frame_2)
        self.stu_label_6.setMinimumSize(QtCore.QSize(90, 35))
        self.stu_label_6.setMaximumSize(QtCore.QSize(90, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_6.setFont(font)
        self.stu_label_6.setStyleSheet("color : white;")
        self.stu_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.stu_label_6.setObjectName("stu_label_6")
        self.stu_layout_16.addWidget(self.stu_label_6)
        self.stu_roots_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.stu_roots_comboBox.setMinimumSize(QtCore.QSize(100, 35))
        self.stu_roots_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_roots_comboBox.setFont(font)
        self.stu_roots_comboBox.setMouseTracking(True)
        self.stu_roots_comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stu_roots_comboBox.setStyleSheet("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;")
        self.stu_roots_comboBox.setObjectName("stu_roots_comboBox")
        self.stu_roots_comboBox.addItem("")
        self.stu_roots_comboBox.addItem("")
        self.stu_layout_16.addWidget(self.stu_roots_comboBox)
        self.stu_label_9 = QtWidgets.QLabel(self.frame_2)
        self.stu_label_9.setMinimumSize(QtCore.QSize(20, 35))
        self.stu_label_9.setMaximumSize(QtCore.QSize(20, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_9.setFont(font)
        self.stu_label_9.setStyleSheet("color : white;")
        self.stu_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.stu_label_9.setObjectName("stu_label_9")
        self.stu_layout_16.addWidget(self.stu_label_9)
        self.stu_show_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.stu_show_comboBox.setMinimumSize(QtCore.QSize(100, 35))
        self.stu_show_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_show_comboBox.setFont(font)
        self.stu_show_comboBox.setMouseTracking(True)
        self.stu_show_comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stu_show_comboBox.setStyleSheet("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;")
        self.stu_show_comboBox.setObjectName("stu_show_comboBox")
        self.stu_layout_16.addWidget(self.stu_show_comboBox)
        self.stu_label_10 = QtWidgets.QLabel(self.frame_2)
        self.stu_label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.stu_label_10.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_10.setFont(font)
        self.stu_label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.stu_label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stu_label_10.setObjectName("stu_label_10")
        self.stu_layout_16.addWidget(self.stu_label_10)
        self.stu_asset_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.stu_asset_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.stu_asset_lineEdit.setFont(font)
        self.stu_asset_lineEdit.setObjectName("stu_asset_lineEdit")
        self.stu_layout_16.addWidget(self.stu_asset_lineEdit)
        self.stu_label_8 = QtWidgets.QLabel(self.frame_2)
        self.stu_label_8.setMinimumSize(QtCore.QSize(80, 30))
        self.stu_label_8.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_8.setFont(font)
        self.stu_label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.stu_label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stu_label_8.setObjectName("stu_label_8")
        self.stu_layout_16.addWidget(self.stu_label_8)
        self.stu_ver_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.stu_ver_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.stu_ver_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.stu_ver_lineEdit.setFont(font)
        self.stu_ver_lineEdit.setObjectName("stu_ver_lineEdit")
        self.stu_layout_16.addWidget(self.stu_ver_lineEdit)
        self.stu_label_7 = QtWidgets.QLabel(self.frame_2)
        self.stu_label_7.setMinimumSize(QtCore.QSize(70, 30))
        self.stu_label_7.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_7.setFont(font)
        self.stu_label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.stu_label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stu_label_7.setObjectName("stu_label_7")
        self.stu_layout_16.addWidget(self.stu_label_7)
        self.stu_texVer_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.stu_texVer_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.stu_texVer_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.stu_texVer_lineEdit.setFont(font)
        self.stu_texVer_lineEdit.setObjectName("stu_texVer_lineEdit")
        self.stu_layout_16.addWidget(self.stu_texVer_lineEdit)
        self.verticalLayout_8.addLayout(self.stu_layout_16)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.stu_layout_3 = QtWidgets.QHBoxLayout()
        self.stu_layout_3.setObjectName("stu_layout_3")
        self.stu_layout_13 = QtWidgets.QVBoxLayout()
        self.stu_layout_13.setContentsMargins(0, -1, -1, 0)
        self.stu_layout_13.setObjectName("stu_layout_13")
        self.stu_scenegraph_frame = QtWidgets.QFrame(self.stu_frame_1)
        self.stu_scenegraph_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_scenegraph_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_scenegraph_frame.setObjectName("stu_scenegraph_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stu_scenegraph_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stu_layout_14 = QtWidgets.QHBoxLayout()
        self.stu_layout_14.setObjectName("stu_layout_14")
        self.stu_spacer_5 = QtWidgets.QLabel(self.stu_scenegraph_frame)
        self.stu_spacer_5.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_spacer_5.setFont(font)
        self.stu_spacer_5.setStyleSheet("color : white;")
        self.stu_spacer_5.setObjectName("stu_spacer_5")
        self.stu_layout_14.addWidget(self.stu_spacer_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stu_layout_14.addItem(spacerItem)
        self.stu_scenegraph_high_checkBox = QtWidgets.QCheckBox(self.stu_scenegraph_frame)
        self.stu_scenegraph_high_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.stu_scenegraph_high_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_scenegraph_high_checkBox.setFont(font)
        self.stu_scenegraph_high_checkBox.setToolTip("")
        self.stu_scenegraph_high_checkBox.setAutoFillBackground(False)
        self.stu_scenegraph_high_checkBox.setStyleSheet("color : white;")
        self.stu_scenegraph_high_checkBox.setChecked(True)
        self.stu_scenegraph_high_checkBox.setObjectName("stu_scenegraph_high_checkBox")
        self.stu_layout_14.addWidget(self.stu_scenegraph_high_checkBox)
        self.stu_scenegraph_mid_checkBox = QtWidgets.QCheckBox(self.stu_scenegraph_frame)
        self.stu_scenegraph_mid_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.stu_scenegraph_mid_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_scenegraph_mid_checkBox.setFont(font)
        self.stu_scenegraph_mid_checkBox.setToolTip("")
        self.stu_scenegraph_mid_checkBox.setAutoFillBackground(False)
        self.stu_scenegraph_mid_checkBox.setStyleSheet("color : white;")
        self.stu_scenegraph_mid_checkBox.setObjectName("stu_scenegraph_mid_checkBox")
        self.stu_layout_14.addWidget(self.stu_scenegraph_mid_checkBox)
        self.stu_scenegraph_low_checkBox = QtWidgets.QCheckBox(self.stu_scenegraph_frame)
        self.stu_scenegraph_low_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.stu_scenegraph_low_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_scenegraph_low_checkBox.setFont(font)
        self.stu_scenegraph_low_checkBox.setToolTip("")
        self.stu_scenegraph_low_checkBox.setAutoFillBackground(False)
        self.stu_scenegraph_low_checkBox.setStyleSheet("color : white;")
        self.stu_scenegraph_low_checkBox.setObjectName("stu_scenegraph_low_checkBox")
        self.stu_layout_14.addWidget(self.stu_scenegraph_low_checkBox)
        self.stu_riggingData_checkBox = QtWidgets.QCheckBox(self.stu_scenegraph_frame)
        self.stu_riggingData_checkBox.setEnabled(False)
        self.stu_riggingData_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.stu_riggingData_checkBox.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_riggingData_checkBox.setFont(font)
        self.stu_riggingData_checkBox.setToolTip("")
        self.stu_riggingData_checkBox.setAutoFillBackground(False)
        self.stu_riggingData_checkBox.setStyleSheet("color : white;")
        self.stu_riggingData_checkBox.setCheckable(True)
        self.stu_riggingData_checkBox.setObjectName("stu_riggingData_checkBox")
        self.stu_layout_14.addWidget(self.stu_riggingData_checkBox)
        self.verticalLayout_5.addLayout(self.stu_layout_14)
        self.stu_sceneGraph_treeWidget = QtWidgets.QTreeWidget(self.stu_scenegraph_frame)
        self.stu_sceneGraph_treeWidget.setRootIsDecorated(True)
        self.stu_sceneGraph_treeWidget.setHeaderHidden(True)
        self.stu_sceneGraph_treeWidget.setObjectName("stu_sceneGraph_treeWidget")
        self.stu_sceneGraph_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.stu_sceneGraph_treeWidget)
        self.stu_layout_13.addWidget(self.stu_scenegraph_frame)
        self.stu_layout_3.addLayout(self.stu_layout_13)
        self.stu_layout_4 = QtWidgets.QVBoxLayout()
        self.stu_layout_4.setObjectName("stu_layout_4")
        self.stu_textureGroup_frame = QtWidgets.QFrame(self.stu_frame_1)
        self.stu_textureGroup_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_textureGroup_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_textureGroup_frame.setObjectName("stu_textureGroup_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stu_textureGroup_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stu_layout_12 = QtWidgets.QHBoxLayout()
        self.stu_layout_12.setObjectName("stu_layout_12")
        self.stu_label_5 = QtWidgets.QLabel(self.stu_textureGroup_frame)
        self.stu_label_5.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_5.setFont(font)
        self.stu_label_5.setStyleSheet("color : white;")
        self.stu_label_5.setObjectName("stu_label_5")
        self.stu_layout_12.addWidget(self.stu_label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stu_layout_12.addItem(spacerItem1)
        self.stu_textureGroup_add_pushButton = QtWidgets.QPushButton(self.stu_textureGroup_frame)
        self.stu_textureGroup_add_pushButton.setMinimumSize(QtCore.QSize(23, 23))
        self.stu_textureGroup_add_pushButton.setMaximumSize(QtCore.QSize(23, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.stu_textureGroup_add_pushButton.setFont(font)
        self.stu_textureGroup_add_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.stu_textureGroup_add_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.stu_textureGroup_add_pushButton.setFlat(True)
        self.stu_textureGroup_add_pushButton.setObjectName("stu_textureGroup_add_pushButton")
        self.stu_layout_12.addWidget(self.stu_textureGroup_add_pushButton)
        self.verticalLayout_6.addLayout(self.stu_layout_12)
        self.stu_textureGroup_treeWidget = QtWidgets.QTreeWidget(self.stu_textureGroup_frame)
        self.stu_textureGroup_treeWidget.setRootIsDecorated(True)
        self.stu_textureGroup_treeWidget.setHeaderHidden(True)
        self.stu_textureGroup_treeWidget.setObjectName("stu_textureGroup_treeWidget")
        self.stu_textureGroup_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.stu_textureGroup_treeWidget)
        self.verticalLayout_6.setStretch(1, 1)
        self.stu_layout_4.addWidget(self.stu_textureGroup_frame)
        self.stu_layout_5 = QtWidgets.QHBoxLayout()
        self.stu_layout_5.setObjectName("stu_layout_5")
        self.stu_materialSet_frame = QtWidgets.QFrame(self.stu_frame_1)
        self.stu_materialSet_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_materialSet_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_materialSet_frame.setObjectName("stu_materialSet_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.stu_materialSet_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stu_layout_11 = QtWidgets.QHBoxLayout()
        self.stu_layout_11.setObjectName("stu_layout_11")
        self.stu_label_4 = QtWidgets.QLabel(self.stu_materialSet_frame)
        self.stu_label_4.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_label_4.setFont(font)
        self.stu_label_4.setStyleSheet("color : white;")
        self.stu_label_4.setObjectName("stu_label_4")
        self.stu_layout_11.addWidget(self.stu_label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stu_layout_11.addItem(spacerItem2)
        self.stu_materialSet_add_pushButton = QtWidgets.QPushButton(self.stu_materialSet_frame)
        self.stu_materialSet_add_pushButton.setMinimumSize(QtCore.QSize(23, 23))
        self.stu_materialSet_add_pushButton.setMaximumSize(QtCore.QSize(23, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.stu_materialSet_add_pushButton.setFont(font)
        self.stu_materialSet_add_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.stu_materialSet_add_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.stu_materialSet_add_pushButton.setFlat(True)
        self.stu_materialSet_add_pushButton.setObjectName("stu_materialSet_add_pushButton")
        self.stu_layout_11.addWidget(self.stu_materialSet_add_pushButton)
        self.verticalLayout_11.addLayout(self.stu_layout_11)
        self.stu_materialSet_treeWidget = QtWidgets.QTreeWidget(self.stu_materialSet_frame)
        self.stu_materialSet_treeWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.stu_materialSet_treeWidget.setRootIsDecorated(True)
        self.stu_materialSet_treeWidget.setHeaderHidden(True)
        self.stu_materialSet_treeWidget.setObjectName("stu_materialSet_treeWidget")
        self.stu_materialSet_treeWidget.headerItem().setText(0, "1")
        self.stu_materialSet_treeWidget.header().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.stu_materialSet_treeWidget)
        self.stu_layout_5.addWidget(self.stu_materialSet_frame)
        self.stu_clip_frame = QtWidgets.QFrame(self.stu_frame_1)
        self.stu_clip_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_clip_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_clip_frame.setObjectName("stu_clip_frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.stu_clip_frame)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stu_layout_6 = QtWidgets.QHBoxLayout()
        self.stu_layout_6.setObjectName("stu_layout_6")
        self.stu_clip_checkBox = QtWidgets.QCheckBox(self.stu_clip_frame)
        self.stu_clip_checkBox.setMinimumSize(QtCore.QSize(10, 25))
        self.stu_clip_checkBox.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.stu_clip_checkBox.setFont(font)
        self.stu_clip_checkBox.setToolTip("")
        self.stu_clip_checkBox.setAutoFillBackground(False)
        self.stu_clip_checkBox.setStyleSheet("color : white;")
        self.stu_clip_checkBox.setObjectName("stu_clip_checkBox")
        self.stu_layout_6.addWidget(self.stu_clip_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stu_layout_6.addItem(spacerItem3)
        self.verticalLayout_15.addLayout(self.stu_layout_6)
        self.stu_layout_7 = QtWidgets.QVBoxLayout()
        self.stu_layout_7.setObjectName("stu_layout_7")
        self.stu_line_1 = QtWidgets.QFrame(self.stu_clip_frame)
        self.stu_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.stu_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stu_line_1.setObjectName("stu_line_1")
        self.stu_layout_7.addWidget(self.stu_line_1)
        self.stu_layout_8 = QtWidgets.QGridLayout()
        self.stu_layout_8.setObjectName("stu_layout_8")
        self.stu_export_end_lineEdit = QtWidgets.QLineEdit(self.stu_clip_frame)
        self.stu_export_end_lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.stu_export_end_lineEdit.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_export_end_lineEdit.setFont(font)
        self.stu_export_end_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_export_end_lineEdit.setObjectName("stu_export_end_lineEdit")
        self.stu_layout_8.addWidget(self.stu_export_end_lineEdit, 1, 3, 1, 1)
        self.stu_export_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_export_label.setFont(font)
        self.stu_export_label.setCursor(QtCore.Qt.ArrowCursor)
        self.stu_export_label.setStyleSheet("color : white;")
        self.stu_export_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_export_label.setObjectName("stu_export_label")
        self.stu_layout_8.addWidget(self.stu_export_label, 1, 0, 1, 1)
        self.stu_frame_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_frame_label.setFont(font)
        self.stu_frame_label.setCursor(QtCore.Qt.ArrowCursor)
        self.stu_frame_label.setStyleSheet("color : white;")
        self.stu_frame_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_frame_label.setObjectName("stu_frame_label")
        self.stu_layout_8.addWidget(self.stu_frame_label, 0, 0, 1, 1)
        self.stu_frame_end_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_frame_end_label.setFont(font)
        self.stu_frame_end_label.setCursor(QtCore.Qt.ArrowCursor)
        self.stu_frame_end_label.setStyleSheet("color : white;")
        self.stu_frame_end_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_frame_end_label.setObjectName("stu_frame_end_label")
        self.stu_layout_8.addWidget(self.stu_frame_end_label, 0, 3, 1, 1)
        self.stu_frame_start_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_frame_start_label.setFont(font)
        self.stu_frame_start_label.setCursor(QtCore.Qt.ArrowCursor)
        self.stu_frame_start_label.setStyleSheet("color : white;")
        self.stu_frame_start_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_frame_start_label.setObjectName("stu_frame_start_label")
        self.stu_layout_8.addWidget(self.stu_frame_start_label, 0, 1, 1, 1)
        self.stu_fps_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_fps_label.setFont(font)
        self.stu_fps_label.setCursor(QtCore.Qt.ArrowCursor)
        self.stu_fps_label.setStyleSheet("color : white;")
        self.stu_fps_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_fps_label.setObjectName("stu_fps_label")
        self.stu_layout_8.addWidget(self.stu_fps_label, 2, 0, 1, 1)
        self.stu_fps_lineEdit = QtWidgets.QLineEdit(self.stu_clip_frame)
        self.stu_fps_lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.stu_fps_lineEdit.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_fps_lineEdit.setFont(font)
        self.stu_fps_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_fps_lineEdit.setObjectName("stu_fps_lineEdit")
        self.stu_layout_8.addWidget(self.stu_fps_lineEdit, 2, 1, 1, 1)
        self.stu_loop_checkBox = QtWidgets.QCheckBox(self.stu_clip_frame)
        self.stu_loop_checkBox.setMinimumSize(QtCore.QSize(65, 0))
        self.stu_loop_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_loop_checkBox.setFont(font)
        self.stu_loop_checkBox.setToolTip("")
        self.stu_loop_checkBox.setAutoFillBackground(False)
        self.stu_loop_checkBox.setStyleSheet("color : white;")
        self.stu_loop_checkBox.setChecked(True)
        self.stu_loop_checkBox.setObjectName("stu_loop_checkBox")
        self.stu_layout_8.addWidget(self.stu_loop_checkBox, 2, 3, 1, 1)
        self.stu_export_start_lineEdit = QtWidgets.QLineEdit(self.stu_clip_frame)
        self.stu_export_start_lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.stu_export_start_lineEdit.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_export_start_lineEdit.setFont(font)
        self.stu_export_start_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_export_start_lineEdit.setObjectName("stu_export_start_lineEdit")
        self.stu_layout_8.addWidget(self.stu_export_start_lineEdit, 1, 1, 1, 1)
        self.stu_layout_7.addLayout(self.stu_layout_8)
        self.stu_layout_9 = QtWidgets.QGridLayout()
        self.stu_layout_9.setVerticalSpacing(0)
        self.stu_layout_9.setObjectName("stu_layout_9")
        self.stu_speed_m0_8_checkBox = QtWidgets.QCheckBox(self.stu_clip_frame)
        self.stu_speed_m0_8_checkBox.setMinimumSize(QtCore.QSize(65, 0))
        self.stu_speed_m0_8_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_speed_m0_8_checkBox.setFont(font)
        self.stu_speed_m0_8_checkBox.setToolTip("")
        self.stu_speed_m0_8_checkBox.setAutoFillBackground(False)
        self.stu_speed_m0_8_checkBox.setStyleSheet("color : white;")
        self.stu_speed_m0_8_checkBox.setChecked(True)
        self.stu_speed_m0_8_checkBox.setObjectName("stu_speed_m0_8_checkBox")
        self.stu_layout_9.addWidget(self.stu_speed_m0_8_checkBox, 0, 1, 1, 1)
        self.stu_speed_m1_5_checkBox = QtWidgets.QCheckBox(self.stu_clip_frame)
        self.stu_speed_m1_5_checkBox.setMinimumSize(QtCore.QSize(65, 0))
        self.stu_speed_m1_5_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_speed_m1_5_checkBox.setFont(font)
        self.stu_speed_m1_5_checkBox.setToolTip("")
        self.stu_speed_m1_5_checkBox.setAutoFillBackground(False)
        self.stu_speed_m1_5_checkBox.setStyleSheet("color : white;")
        self.stu_speed_m1_5_checkBox.setChecked(True)
        self.stu_speed_m1_5_checkBox.setObjectName("stu_speed_m1_5_checkBox")
        self.stu_layout_9.addWidget(self.stu_speed_m1_5_checkBox, 0, 4, 1, 1)
        self.stu_speed_m1_0_checkBox = QtWidgets.QCheckBox(self.stu_clip_frame)
        self.stu_speed_m1_0_checkBox.setMinimumSize(QtCore.QSize(65, 0))
        self.stu_speed_m1_0_checkBox.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_speed_m1_0_checkBox.setFont(font)
        self.stu_speed_m1_0_checkBox.setToolTip("")
        self.stu_speed_m1_0_checkBox.setAutoFillBackground(False)
        self.stu_speed_m1_0_checkBox.setStyleSheet("color : white;")
        self.stu_speed_m1_0_checkBox.setChecked(True)
        self.stu_speed_m1_0_checkBox.setObjectName("stu_speed_m1_0_checkBox")
        self.stu_layout_9.addWidget(self.stu_speed_m1_0_checkBox, 0, 2, 1, 1)
        self.stu_layout_7.addLayout(self.stu_layout_9)
        self.verticalLayout_15.addLayout(self.stu_layout_7)
        self.stu_layout_10 = QtWidgets.QHBoxLayout()
        self.stu_layout_10.setObjectName("stu_layout_10")
        self.stu_speed_label = QtWidgets.QLabel(self.stu_clip_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.stu_speed_label.setFont(font)
        self.stu_speed_label.setStyleSheet("color : white;")
        self.stu_speed_label.setObjectName("stu_speed_label")
        self.stu_layout_10.addWidget(self.stu_speed_label)
        self.stu_speed_lineEdit = QtWidgets.QLineEdit(self.stu_clip_frame)
        self.stu_speed_lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.stu_speed_lineEdit.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stu_speed_lineEdit.setFont(font)
        self.stu_speed_lineEdit.setStyleSheet("color : white;\n"
"background-color: rgb(100,100,100);")
        self.stu_speed_lineEdit.setObjectName("stu_speed_lineEdit")
        self.stu_layout_10.addWidget(self.stu_speed_lineEdit)
        self.verticalLayout_15.addLayout(self.stu_layout_10)
        self.verticalLayout_15.setStretch(1, 1)
        self.stu_layout_5.addWidget(self.stu_clip_frame)
        self.stu_layout_4.addLayout(self.stu_layout_5)
        self.stu_layout_4.setStretch(0, 1)
        self.stu_layout_3.addLayout(self.stu_layout_4)
        self.stu_layout_3.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.stu_layout_3)
        self.stu_layout_2 = QtWidgets.QHBoxLayout()
        self.stu_layout_2.setContentsMargins(10, 6, -1, -1)
        self.stu_layout_2.setObjectName("stu_layout_2")
        self.stu_message_label = QtWidgets.QLabel(self.stu_frame_1)
        self.stu_message_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.stu_message_label.setStyleSheet("color: rgb(255,  30, 10);\n"
"font: 75 12pt \"Cantarell\";")
        self.stu_message_label.setTextFormat(QtCore.Qt.AutoText)
        self.stu_message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stu_message_label.setObjectName("stu_message_label")
        self.stu_layout_2.addWidget(self.stu_message_label)
        self.stu_machineType_comboBox = QtWidgets.QComboBox(self.stu_frame_1)
        self.stu_machineType_comboBox.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_machineType_comboBox.setFont(font)
        self.stu_machineType_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.stu_machineType_comboBox.setAccessibleDescription("")
        self.stu_machineType_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stu_machineType_comboBox.setAutoFillBackground(False)
        self.stu_machineType_comboBox.setStyleSheet("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;")
        self.stu_machineType_comboBox.setObjectName("stu_machineType_comboBox")
        self.stu_machineType_comboBox.addItem("")
        self.stu_machineType_comboBox.addItem("")
        self.stu_layout_2.addWidget(self.stu_machineType_comboBox)
        self.stu_export_pushButton = QtWidgets.QPushButton(self.stu_frame_1)
        self.stu_export_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.stu_export_pushButton.setFont(font)
        self.stu_export_pushButton.setStyleSheet("color : white;\n"
"background-color: rgb(62, 109, 186);")
        self.stu_export_pushButton.setObjectName("stu_export_pushButton")
        self.stu_layout_2.addWidget(self.stu_export_pushButton)
        self.stu_layout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.stu_layout_2)
        self.verticalLayout.addWidget(self.stu_frame_1)

        self.retranslateUi(stu_win)
        QtCore.QMetaObject.connectSlotsByName(stu_win)
        stu_win.setTabOrder(self.stu_abcFile_lineEdit, self.stu_abcFile_find_pushButton)
        stu_win.setTabOrder(self.stu_abcFile_find_pushButton, self.stu_abcFile_openDir_pushButton)
        stu_win.setTabOrder(self.stu_abcFile_openDir_pushButton, self.stu_xmlFile_lineEdit)
        stu_win.setTabOrder(self.stu_xmlFile_lineEdit, self.stu_xmlFile_find_pushButton)
        stu_win.setTabOrder(self.stu_xmlFile_find_pushButton, self.stu_xmlFile_openDir_pushButton)
        stu_win.setTabOrder(self.stu_xmlFile_openDir_pushButton, self.stu_asset_lineEdit)
        stu_win.setTabOrder(self.stu_asset_lineEdit, self.stu_ver_lineEdit)
        stu_win.setTabOrder(self.stu_ver_lineEdit, self.stu_texVer_lineEdit)
        stu_win.setTabOrder(self.stu_texVer_lineEdit, self.stu_sceneGraph_treeWidget)
        stu_win.setTabOrder(self.stu_sceneGraph_treeWidget, self.stu_materialSet_add_pushButton)
        stu_win.setTabOrder(self.stu_materialSet_add_pushButton, self.stu_materialSet_treeWidget)
        stu_win.setTabOrder(self.stu_materialSet_treeWidget, self.stu_clip_checkBox)
        stu_win.setTabOrder(self.stu_clip_checkBox, self.stu_export_start_lineEdit)
        stu_win.setTabOrder(self.stu_export_start_lineEdit, self.stu_export_end_lineEdit)
        stu_win.setTabOrder(self.stu_export_end_lineEdit, self.stu_fps_lineEdit)
        stu_win.setTabOrder(self.stu_fps_lineEdit, self.stu_speed_m0_8_checkBox)
        stu_win.setTabOrder(self.stu_speed_m0_8_checkBox, self.stu_speed_m1_0_checkBox)
        stu_win.setTabOrder(self.stu_speed_m1_0_checkBox, self.stu_speed_m1_5_checkBox)
        stu_win.setTabOrder(self.stu_speed_m1_5_checkBox, self.stu_textureGroup_add_pushButton)
        stu_win.setTabOrder(self.stu_textureGroup_add_pushButton, self.stu_textureGroup_treeWidget)
        stu_win.setTabOrder(self.stu_textureGroup_treeWidget, self.stu_machineType_comboBox)
        stu_win.setTabOrder(self.stu_machineType_comboBox, self.stu_export_pushButton)

    def retranslateUi(self, stu_win):
        stu_win.setWindowTitle(QtWidgets.QApplication.translate("stu_win", "Form", None, -1))
        self.stu_title_label.setText(QtWidgets.QApplication.translate("stu_win", " SPEEDTREE TO USD v1.0", None, -1))
        self.stu_user_label.setText(QtWidgets.QApplication.translate("stu_win", "USER :", None, -1))
        self.stu_user_name_label.setText(QtWidgets.QApplication.translate("stu_win", "sdsdf", None, -1))
        self.stu_label_11.setText(QtWidgets.QApplication.translate("stu_win", "ABC FILE :", None, -1))
        self.stu_xmlFile_find_pushButton.setText(QtWidgets.QApplication.translate("stu_win", "...", None, -1))
        self.stu_abcFile_find_pushButton.setText(QtWidgets.QApplication.translate("stu_win", "...", None, -1))
        self.stu_label_12.setText(QtWidgets.QApplication.translate("stu_win", "XML FILE :", None, -1))
        self.stu_label_6.setText(QtWidgets.QApplication.translate("stu_win", "OUTPUT :", None, -1))
        self.stu_roots_comboBox.setItemText(0, QtWidgets.QApplication.translate("stu_win", "/show", None, -1))
        self.stu_roots_comboBox.setItemText(1, QtWidgets.QApplication.translate("stu_win", "/assetlib", None, -1))
        self.stu_label_9.setText(QtWidgets.QApplication.translate("stu_win", "/ ", None, -1))
        self.stu_label_10.setText(QtWidgets.QApplication.translate("stu_win", "/ assset / ", None, -1))
        self.stu_label_8.setText(QtWidgets.QApplication.translate("stu_win", "Ver. ", None, -1))
        self.stu_label_7.setText(QtWidgets.QApplication.translate("stu_win", "Tex Ver. ", None, -1))
        self.stu_spacer_5.setText(QtWidgets.QApplication.translate("stu_win", "SCENEGRAPH", None, -1))
        self.stu_scenegraph_high_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "High", None, -1))
        self.stu_scenegraph_mid_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "Mid", None, -1))
        self.stu_scenegraph_low_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "Low", None, -1))
        self.stu_riggingData_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "Rigging Data", None, -1))
        self.stu_label_5.setText(QtWidgets.QApplication.translate("stu_win", "TEXTURE GROUP", None, -1))
        self.stu_textureGroup_add_pushButton.setText(QtWidgets.QApplication.translate("stu_win", "+", None, -1))
        self.stu_label_4.setText(QtWidgets.QApplication.translate("stu_win", "MATERIAL SET", None, -1))
        self.stu_materialSet_add_pushButton.setText(QtWidgets.QApplication.translate("stu_win", "+", None, -1))
        self.stu_clip_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "CLIP", None, -1))
        self.stu_export_end_lineEdit.setText(QtWidgets.QApplication.translate("stu_win", "0", None, -1))
        self.stu_export_label.setText(QtWidgets.QApplication.translate("stu_win", "Export :", None, -1))
        self.stu_frame_label.setText(QtWidgets.QApplication.translate("stu_win", "Frame :", None, -1))
        self.stu_frame_end_label.setText(QtWidgets.QApplication.translate("stu_win", "0", None, -1))
        self.stu_frame_start_label.setText(QtWidgets.QApplication.translate("stu_win", "0", None, -1))
        self.stu_fps_label.setText(QtWidgets.QApplication.translate("stu_win", "fps :", None, -1))
        self.stu_fps_lineEdit.setText(QtWidgets.QApplication.translate("stu_win", "24", None, -1))
        self.stu_loop_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "Loop", None, -1))
        self.stu_export_start_lineEdit.setText(QtWidgets.QApplication.translate("stu_win", "0", None, -1))
        self.stu_speed_m0_8_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "x0.8", None, -1))
        self.stu_speed_m1_5_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "x1.5", None, -1))
        self.stu_speed_m1_0_checkBox.setText(QtWidgets.QApplication.translate("stu_win", "x1.0", None, -1))
        self.stu_speed_label.setText(QtWidgets.QApplication.translate("stu_win", "Speed", None, -1))
        self.stu_message_label.setText(QtWidgets.QApplication.translate("stu_win", "ERROR MESSGE", None, -1))
        self.stu_machineType_comboBox.setItemText(0, QtWidgets.QApplication.translate("stu_win", "LOCAL", None, -1))
        self.stu_machineType_comboBox.setItemText(1, QtWidgets.QApplication.translate("stu_win", "TRACTOR", None, -1))
        self.stu_export_pushButton.setText(QtWidgets.QApplication.translate("stu_win", "EXPORT", None, -1))

