# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ddpm2017.ui',
# licensing of './ddpm2017.ui' applies.
#
# Created: Thu Aug 13 18:56:43 2020
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DDPM(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(624, 494)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 90, 90);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.artistName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.artistName_lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.artistName_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.artistName_lineEdit.setObjectName("artistName_lineEdit")
        self.horizontalLayout.addWidget(self.artistName_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.sceneName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.sceneName_lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.sceneName_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sceneName_lineEdit.setObjectName("sceneName_lineEdit")
        self.horizontalLayout.addWidget(self.sceneName_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.depart_comboBox = QtWidgets.QComboBox(self.frame)
        self.depart_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.depart_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.depart_comboBox.setObjectName("depart_comboBox")
        self.horizontalLayout_2.addWidget(self.depart_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.status_comboBox = QtWidgets.QComboBox(self.frame)
        self.status_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.status_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.status_comboBox.setObjectName("status_comboBox")
        self.horizontalLayout_2.addWidget(self.status_comboBox)
        self.progress_comboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_comboBox.sizePolicy().hasHeightForWidth())
        self.progress_comboBox.setSizePolicy(sizePolicy)
        self.progress_comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.progress_comboBox.setObjectName("progress_comboBox")
        self.horizontalLayout_2.addWidget(self.progress_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.autoHud_checkBox = QtWidgets.QCheckBox(self.frame)
        self.autoHud_checkBox.setObjectName("autoHud_checkBox")
        self.horizontalLayout_3.addWidget(self.autoHud_checkBox)
        self.hudOn_Btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hudOn_Btn.sizePolicy().hasHeightForWidth())
        self.hudOn_Btn.setSizePolicy(sizePolicy)
        self.hudOn_Btn.setMinimumSize(QtCore.QSize(80, 20))
        self.hudOn_Btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.hudOn_Btn.setObjectName("hudOn_Btn")
        self.horizontalLayout_3.addWidget(self.hudOn_Btn)
        self.hudOff_Btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hudOff_Btn.sizePolicy().hasHeightForWidth())
        self.hudOff_Btn.setSizePolicy(sizePolicy)
        self.hudOff_Btn.setMinimumSize(QtCore.QSize(80, 20))
        self.hudOff_Btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.hudOff_Btn.setObjectName("hudOff_Btn")
        self.horizontalLayout_3.addWidget(self.hudOff_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.option_frame = QtWidgets.QFrame(Form)
        self.option_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.option_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.option_frame.setObjectName("option_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.option_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.option_frame)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.codec_comboBox = QtWidgets.QComboBox(self.option_frame)
        self.codec_comboBox.setObjectName("codec_comboBox")
        self.horizontalLayout_10.addWidget(self.codec_comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_14 = QtWidgets.QFrame(self.option_frame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_4.addWidget(self.line_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.option_frame)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.prvSizeW_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.prvSizeW_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.prvSizeW_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.prvSizeW_lineEdit.setObjectName("prvSizeW_lineEdit")
        self.horizontalLayout_4.addWidget(self.prvSizeW_lineEdit)
        self.label_9 = QtWidgets.QLabel(self.option_frame)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.prvSizeH_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.prvSizeH_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.prvSizeH_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.prvSizeH_lineEdit.setObjectName("prvSizeH_lineEdit")
        self.horizontalLayout_4.addWidget(self.prvSizeH_lineEdit)
        self.line_13 = QtWidgets.QFrame(self.option_frame)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_4.addWidget(self.line_13)
        self.prvSizePreset_comboBox = QtWidgets.QComboBox(self.option_frame)
        self.prvSizePreset_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.prvSizePreset_comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.prvSizePreset_comboBox.setObjectName("prvSizePreset_comboBox")
        self.horizontalLayout_4.addWidget(self.prvSizePreset_comboBox)
        self.projectList_comboBox = QtWidgets.QComboBox(self.option_frame)
        self.projectList_comboBox.setObjectName("projectList_comboBox")
        self.horizontalLayout_4.addWidget(self.projectList_comboBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_6 = QtWidgets.QFrame(self.option_frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.option_frame)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.startFrame_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.startFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.startFrame_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.startFrame_lineEdit.setObjectName("startFrame_lineEdit")
        self.horizontalLayout_6.addWidget(self.startFrame_lineEdit)
        self.label_11 = QtWidgets.QLabel(self.option_frame)
        self.label_11.setMinimumSize(QtCore.QSize(10, 0))
        self.label_11.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.endFrame_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.endFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.endFrame_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.endFrame_lineEdit.setObjectName("endFrame_lineEdit")
        self.horizontalLayout_6.addWidget(self.endFrame_lineEdit)
        self.line_12 = QtWidgets.QFrame(self.option_frame)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_6.addWidget(self.line_12)
        self.label_5 = QtWidgets.QLabel(self.option_frame)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.seqStartFrame_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.seqStartFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.seqStartFrame_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.seqStartFrame_lineEdit.setObjectName("seqStartFrame_lineEdit")
        self.horizontalLayout_6.addWidget(self.seqStartFrame_lineEdit)
        self.label_12 = QtWidgets.QLabel(self.option_frame)
        self.label_12.setMinimumSize(QtCore.QSize(10, 0))
        self.label_12.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.seqEndFrame_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.seqEndFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.seqEndFrame_lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.seqEndFrame_lineEdit.setObjectName("seqEndFrame_lineEdit")
        self.horizontalLayout_6.addWidget(self.seqEndFrame_lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_7 = QtWidgets.QFrame(self.option_frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.rmSeq_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.rmSeq_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.rmSeq_checkBox.setStyleSheet("")
        self.rmSeq_checkBox.setChecked(False)
        self.rmSeq_checkBox.setObjectName("rmSeq_checkBox")
        self.horizontalLayout_7.addWidget(self.rmSeq_checkBox)
        self.offScreen_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.offScreen_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.offScreen_checkBox.setObjectName("offScreen_checkBox")
        self.horizontalLayout_7.addWidget(self.offScreen_checkBox)
        self.camSeq_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.camSeq_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.camSeq_checkBox.setObjectName("camSeq_checkBox")
        self.horizontalLayout_7.addWidget(self.camSeq_checkBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.addStamp_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.addStamp_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.addStamp_checkBox.setObjectName("addStamp_checkBox")
        self.horizontalLayout_8.addWidget(self.addStamp_checkBox)
        self.addCompRetime_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.addCompRetime_checkBox.setMinimumSize(QtCore.QSize(150, 0))
        self.addCompRetime_checkBox.setObjectName("addCompRetime_checkBox")
        self.horizontalLayout_8.addWidget(self.addCompRetime_checkBox)
        self.showImageplane_checkBox = QtWidgets.QCheckBox(self.option_frame)
        self.showImageplane_checkBox.setObjectName("showImageplane_checkBox")
        self.horizontalLayout_8.addWidget(self.showImageplane_checkBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.line_5 = QtWidgets.QFrame(self.option_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.option_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 90, 90);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.output_lineEdit = QtWidgets.QLineEdit(self.option_frame)
        self.output_lineEdit.setObjectName("output_lineEdit")
        self.horizontalLayout_5.addWidget(self.output_lineEdit)
        self.browse_Btn = QtWidgets.QPushButton(self.option_frame)
        self.browse_Btn.setMinimumSize(QtCore.QSize(30, 27))
        self.browse_Btn.setMaximumSize(QtCore.QSize(29, 16777215))
        self.browse_Btn.setObjectName("browse_Btn")
        self.horizontalLayout_5.addWidget(self.browse_Btn)
        self.openDir_Btn = QtWidgets.QPushButton(self.option_frame)
        self.openDir_Btn.setMinimumSize(QtCore.QSize(30, 0))
        self.openDir_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.openDir_Btn.setText("")
        self.openDir_Btn.setObjectName("openDir_Btn")
        self.horizontalLayout_5.addWidget(self.openDir_Btn)
        self.play_Btn = QtWidgets.QPushButton(self.option_frame)
        self.play_Btn.setMinimumSize(QtCore.QSize(30, 0))
        self.play_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.play_Btn.setText("")
        self.play_Btn.setObjectName("play_Btn")
        self.horizontalLayout_5.addWidget(self.play_Btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.option_frame, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.fcheck_Btn = QtWidgets.QPushButton(Form)
        self.fcheck_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.fcheck_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.fcheck_Btn.setIconSize(QtCore.QSize(24, 24))
        self.fcheck_Btn.setObjectName("fcheck_Btn")
        self.horizontalLayout_9.addWidget(self.fcheck_Btn)
        self.blueMatte_Btn = QtWidgets.QPushButton(Form)
        self.blueMatte_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.blueMatte_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.blueMatte_Btn.setIconSize(QtCore.QSize(24, 24))
        self.blueMatte_Btn.setObjectName("blueMatte_Btn")
        self.horizontalLayout_9.addWidget(self.blueMatte_Btn)
        self.createSequence_Btn = QtWidgets.QPushButton(Form)
        self.createSequence_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.createSequence_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.createSequence_Btn.setIconSize(QtCore.QSize(24, 24))
        self.createSequence_Btn.setObjectName("createSequence_Btn")
        self.horizontalLayout_9.addWidget(self.createSequence_Btn)
        self.createMovie_Btn = QtWidgets.QPushButton(Form)
        self.createMovie_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.createMovie_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.createMovie_Btn.setIconSize(QtCore.QSize(24, 24))
        self.createMovie_Btn.setObjectName("createMovie_Btn")
        self.horizontalLayout_9.addWidget(self.createMovie_Btn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.redshift_Btn = QtWidgets.QPushButton(Form)
        self.redshift_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.redshift_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.redshift_Btn.setText("")
        self.redshift_Btn.setIconSize(QtCore.QSize(32, 32))
        self.redshift_Btn.setObjectName("redshift_Btn")
        self.horizontalLayout_9.addWidget(self.redshift_Btn)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.refresh_Btn = QtWidgets.QPushButton(Form)
        self.refresh_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.refresh_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.refresh_Btn.setText("")
        self.refresh_Btn.setIconSize(QtCore.QSize(24, 24))
        self.refresh_Btn.setObjectName("refresh_Btn")
        self.horizontalLayout_9.addWidget(self.refresh_Btn)
        self.close_Btn = QtWidgets.QPushButton(Form)
        self.close_Btn.setMinimumSize(QtCore.QSize(60, 32))
        self.close_Btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.close_Btn.setIconSize(QtCore.QSize(24, 24))
        self.close_Btn.setObjectName("close_Btn")
        self.horizontalLayout_9.addWidget(self.close_Btn)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Artist", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Scene Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Department", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Status", None, -1))
        self.autoHud_checkBox.setText(QtWidgets.QApplication.translate("Form", "Auto", None, -1))
        self.hudOn_Btn.setText(QtWidgets.QApplication.translate("Form", "ON", None, -1))
        self.hudOff_Btn.setText(QtWidgets.QApplication.translate("Form", "OFF", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Codec", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Size", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Frame Range", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "to", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Seqencer Time", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "to", None, -1))
        self.rmSeq_checkBox.setText(QtWidgets.QApplication.translate("Form", "Remove Sequence", None, -1))
        self.offScreen_checkBox.setText(QtWidgets.QApplication.translate("Form", "Off Screen", None, -1))
        self.camSeq_checkBox.setText(QtWidgets.QApplication.translate("Form", "Camera Sequencer", None, -1))
        self.addStamp_checkBox.setText(QtWidgets.QApplication.translate("Form", "Add Stamp", None, -1))
        self.addCompRetime_checkBox.setText(QtWidgets.QApplication.translate("Form", "Add Comp Retime", None, -1))
        self.showImageplane_checkBox.setText(QtWidgets.QApplication.translate("Form", "Show Imageplane", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Output", None, -1))
        self.browse_Btn.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.fcheck_Btn.setText(QtWidgets.QApplication.translate("Form", "fcheck", None, -1))
        self.blueMatte_Btn.setText(QtWidgets.QApplication.translate("Form", "BlueMatte", None, -1))
        self.createSequence_Btn.setText(QtWidgets.QApplication.translate("Form", "Sequence", None, -1))
        self.createMovie_Btn.setText(QtWidgets.QApplication.translate("Form", "Movie", None, -1))
        self.close_Btn.setText(QtWidgets.QApplication.translate("Form", "Close", None, -1))
