# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DDani_ReferenceReplace.ui',
# licensing of 'DDani_ReferenceReplace.ui' applies.
#
# Created: Mon Nov  2 17:09:39 2020
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.DDaniRp_refList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DDaniRp_refList.sizePolicy().hasHeightForWidth())
        self.DDaniRp_refList.setSizePolicy(sizePolicy)
        self.DDaniRp_refList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DDaniRp_refList.setDragEnabled(False)
        self.DDaniRp_refList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.DDaniRp_refList.setObjectName("DDaniRp_refList")
        self.gridLayout.addWidget(self.DDaniRp_refList, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.ReferencingType_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.ReferencingType_Tab.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ReferencingType_Tab.setObjectName("ReferencingType_Tab")
        self.versionUp_Tab = QtWidgets.QWidget()
        self.versionUp_Tab.setObjectName("versionUp_Tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.versionUp_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DDaniRp_fileList = QtWidgets.QListWidget(self.versionUp_Tab)
        self.DDaniRp_fileList.setObjectName("DDaniRp_fileList")
        self.verticalLayout.addWidget(self.DDaniRp_fileList)
        self.ReferencingType_Tab.addTab(self.versionUp_Tab, "")
        self.CustomAsset_Tab = QtWidgets.QWidget()
        self.CustomAsset_Tab.setObjectName("CustomAsset_Tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CustomAsset_Tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Show_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        self.Show_CmbBox.setObjectName("Show_CmbBox")
        self.Show_CmbBox.addItem("")
        self.horizontalLayout_2.addWidget(self.Show_CmbBox)
        # self.AssetType_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        # self.AssetType_CmbBox.setObjectName("AssetType_CmbBox")
        # self.AssetType_CmbBox.addItem("")
        # self.horizontalLayout_2.addWidget(self.AssetType_CmbBox)
        self.Asset_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        self.Asset_CmbBox.setObjectName("Asset_CmbBox")
        self.Asset_CmbBox.addItem("")
        self.horizontalLayout_2.addWidget(self.Asset_CmbBox)
        self.Workcode_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        self.Workcode_CmbBox.setObjectName("Workcode_CmbBox")
        self.Workcode_CmbBox.addItem("")
        self.horizontalLayout_2.addWidget(self.Workcode_CmbBox)
        # self.Progress_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        # self.Progress_CmbBox.setObjectName("Progress_CmbBox")
        # self.Progress_CmbBox.addItem("")
        # self.horizontalLayout_2.addWidget(self.Progress_CmbBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.mbFileList_CmbBox = QtWidgets.QComboBox(self.CustomAsset_Tab)
        self.mbFileList_CmbBox.setMinimumSize(QtCore.QSize(300, 0))
        self.mbFileList_CmbBox.setObjectName("mbFileList_CmbBox")
        self.mbFileList_CmbBox.addItem("")
        self.horizontalLayout_4.addWidget(self.mbFileList_CmbBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.OldNameSpace_lineEdit = QtWidgets.QLineEdit(self.CustomAsset_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OldNameSpace_lineEdit.sizePolicy().hasHeightForWidth())
        self.OldNameSpace_lineEdit.setSizePolicy(sizePolicy)
        self.OldNameSpace_lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.OldNameSpace_lineEdit.setObjectName("OldNameSpace_lineEdit")
        self.horizontalLayout_3.addWidget(self.OldNameSpace_lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.NewNameSpace_lineEdit = QtWidgets.QLineEdit(self.CustomAsset_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewNameSpace_lineEdit.sizePolicy().hasHeightForWidth())
        self.NewNameSpace_lineEdit.setSizePolicy(sizePolicy)
        self.NewNameSpace_lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.NewNameSpace_lineEdit.setObjectName("NewNameSpace_lineEdit")
        self.horizontalLayout_3.addWidget(self.NewNameSpace_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.AssetPath_Txt = QtWidgets.QLabel(self.CustomAsset_Tab)
        self.AssetPath_Txt.setText("")
        self.AssetPath_Txt.setObjectName("AssetPath_Txt")
        self.horizontalLayout_5.addWidget(self.AssetPath_Txt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.ReferencingType_Tab.addTab(self.CustomAsset_Tab, "")
        self.gridLayout_2.addWidget(self.ReferencingType_Tab, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DDaniRp_DoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DDaniRp_DoBtn.setObjectName("DDaniRp_DoBtn")
        self.horizontalLayout.addWidget(self.DDaniRp_DoBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        # MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 27))
        # self.menubar.setObjectName("menubar")
        # # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ReferencingType_Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Reference Replace UI", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Select Reference", None, -1))
        self.ReferencingType_Tab.setTabText(self.ReferencingType_Tab.indexOf(self.versionUp_Tab), QtWidgets.QApplication.translate("MainWindow", "version up", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Path", None, -1))
        self.Show_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "--show--", None, -1))
        # self.AssetType_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "-- Asset Type --", None, -1))
        self.Asset_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "-- Asset --", None, -1))
        self.Workcode_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "-- Workcode --", None, -1))
        # self.Progress_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "-- Progress --", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Files", None, -1))
        self.mbFileList_CmbBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Select File", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "NameSpace :", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "to", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Asset Path :", None, -1))
        self.ReferencingType_Tab.setTabText(self.ReferencingType_Tab.indexOf(self.CustomAsset_Tab), QtWidgets.QApplication.translate("MainWindow", "other asset", None, -1))
        self.DDaniRp_DoBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Replace Reference", None, -1))
