# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nukeStamp_v03_koz.ui',
# licensing of 'ui_nukeStamp_v03_koz.ui' applies.
#
# Created: Thu Feb 24 15:29:28 2022
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("koz nukeStamp")
        MainWindow.resize(748, 278)
        MainWindow.setMinimumSize(QtCore.QSize(748, 212))
        MainWindow.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mov_textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.mov_textEdit.setGeometry(QtCore.QRect(20, 40, 681, 31))
        self.mov_textEdit.setObjectName("mov_textEdit")
        self.movEX_label = QtWidgets.QLabel(self.centralwidget)
        self.movEX_label.setGeometry(QtCore.QRect(130, 10, 611, 20))
        self.movEX_label.setObjectName("movEX_label")
        self.mov_label = QtWidgets.QLabel(self.centralwidget)
        self.mov_label.setGeometry(QtCore.QRect(20, 10, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mov_label.sizePolicy().hasHeightForWidth())
        self.mov_label.setSizePolicy(sizePolicy)
        self.mov_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.mov_label.setFont(font)
        self.mov_label.setStyleSheet("color : white;")
        self.mov_label.setObjectName("mov_label")
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setGeometry(QtCore.QRect(20, 80, 81, 25))
        self.filename_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.filename_label.setFont(font)
        self.filename_label.setStyleSheet("color : white;")
        self.filename_label.setObjectName("filename_label")
        self.movFile_find_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.movFile_find_pushButton.setGeometry(QtCore.QRect(710, 40, 30, 30))
        self.movFile_find_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.movFile_find_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.movFile_find_pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);")
        self.movFile_find_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.movFile_find_pushButton.setObjectName("movFile_find_pushButton")
        self.export_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.export_pushButton.setGeometry(QtCore.QRect(610, 230, 130, 40))
        self.export_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        self.export_pushButton.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.export_pushButton.setFont(font)
        self.export_pushButton.setStyleSheet("color : white;\n"
"background-color: rgb(62, 109, 186);")
        self.export_pushButton.setObjectName("export_pushButton")
        # self.overscan_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        # self.overscan_checkBox.setGeometry(QtCore.QRect(20, 230, 107, 29))
        # self.overscan_checkBox.setObjectName("overscan_checkBox")
        self.filename_textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filename_textEdit.setGeometry(QtCore.QRect(20, 110, 681, 31))
        self.filename_textEdit.setObjectName("filename_textEdit")
        self.comments_label = QtWidgets.QLabel(self.centralwidget)
        self.comments_label.setGeometry(QtCore.QRect(20, 150, 101, 25))
        self.comments_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.comments_label.setFont(font)
        self.comments_label.setStyleSheet("color : white;")
        self.comments_label.setObjectName("comments_label")
        self.comments_textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.comments_textEdit.setGeometry(QtCore.QRect(20, 180, 681, 31))
        self.comments_textEdit.setObjectName("comments_textEdit")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "koz nukeStamp", None, -1))
        self.movEX_label.setText(QtWidgets.QApplication.translate("MainWindow", "/show/koz/works/LAY/CV2pos/CV2pos_0020/dev/preview/CV2pos_0020_layout_v001_w001", None, -1))
        self.mov_label.setText(QtWidgets.QApplication.translate("MainWindow", "SEQ image", None, -1))
        self.filename_label.setText(QtWidgets.QApplication.translate("MainWindow", "FILENAME", None, -1))
        self.movFile_find_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.export_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "EXPORT", None, -1))
        # self.overscan_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "overscan", None, -1))
        self.comments_label.setText(QtWidgets.QApplication.translate("MainWindow", "COMMENTS", None, -1))
