# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taneControl_UI.ui'
#
# Created: Tue Sep  4 13:17:51 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from pymodule.Qt import QtCore
from pymodule.Qt import QtWidgets as QtGui
import pymodule.Qt as Qt

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(248, 430)
        self.label_1 = QtGui.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(10, 0, 211, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 161, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 141, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 91, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 231, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 40, 251, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 320, 211, 21))

        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 360, 211, 21))

        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))

        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 121, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_display0 = QtGui.QPushButton(Form)
        self.pushButton_display0.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.pushButton_display0.setObjectName(_fromUtf8("pushButton_display0"))
        self.pushButton_display1 = QtGui.QPushButton(Form)
        self.pushButton_display1.setGeometry(QtCore.QRect(80, 20, 71, 21))
        self.pushButton_display1.setObjectName(_fromUtf8("pushButton_display1"))
        self.pushButton_display2 = QtGui.QPushButton(Form)
        self.pushButton_display2.setGeometry(QtCore.QRect(160, 20, 81, 21))
        self.pushButton_display2.setObjectName(_fromUtf8("pushButton_display2"))
        self.pushButton_copy = QtGui.QPushButton(Form)
        self.pushButton_copy.setGeometry(QtCore.QRect(10, 70, 231, 31))
        self.pushButton_copy.setObjectName(_fromUtf8("pushButton_copy"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 100, 251, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.pushButton_set0 = QtGui.QPushButton(Form)
        self.pushButton_set0.setGeometry(QtCore.QRect(10, 130, 111, 21))
        self.pushButton_set0.setObjectName(_fromUtf8("pushButton_set0"))
        self.pushButton_set1 = QtGui.QPushButton(Form)
        self.pushButton_set1.setGeometry(QtCore.QRect(130, 130, 111, 21))
        self.pushButton_set1.setObjectName(_fromUtf8("pushButton_set1"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(0, 150, 251, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.pushButton_sc = QtGui.QPushButton(Form)
        self.pushButton_sc.setGeometry(QtCore.QRect(10, 180, 231, 21))
        self.pushButton_sc.setObjectName(_fromUtf8("pushButton_sc"))
        self.pushButton_update1 = QtGui.QPushButton(Form)
        self.pushButton_update1.setGeometry(QtCore.QRect(10, 240, 111, 21))
        self.pushButton_update1.setObjectName(_fromUtf8("pushButton_update1"))
        self.pushButton_update0 = QtGui.QPushButton(Form)
        self.pushButton_update0.setGeometry(QtCore.QRect(130, 240, 111, 21))
        self.pushButton_update0.setObjectName(_fromUtf8("pushButton_update0"))
        self.pushButton_bake1 = QtGui.QPushButton(Form)
        self.pushButton_bake1.setGeometry(QtCore.QRect(10, 290, 111, 21))
        self.pushButton_bake1.setObjectName(_fromUtf8("pushButton_bake1"))
        self.pushButton_bake0 = QtGui.QPushButton(Form)
        self.pushButton_bake0.setGeometry(QtCore.QRect(130, 290, 111, 21))
        self.pushButton_bake0.setObjectName(_fromUtf8("pushButton_bake0"))
        self.pushButton_reload = QtGui.QPushButton(Form)
        self.pushButton_reload.setGeometry(QtCore.QRect(10, 340, 231, 21))
        self.pushButton_reload.setObjectName(_fromUtf8("pushButton_reload"))
        self.pushButton_reload2 = QtGui.QPushButton(Form)
        self.pushButton_reload2.setGeometry(QtCore.QRect(10, 380, 231, 21))
        self.pushButton_reload2.setObjectName(_fromUtf8("pushButton_reload"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(0, 200, 251, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(0, 260, 251, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(0, 310, 251, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Tane control Tool", None))
        self.label_1.setText(_translate("Form", "TN display  Mode Change", None))
        self.label_2.setText(_translate("Form", "TN source rename", None))
        self.label_3.setText(_translate("Form", "Duplicate  TN_Tane", None))
        self.label_4.setText(_translate("Form", "TN bake rib", None))
        self.label_5.setText(_translate("Form", "TN Environment Auto update", None))
        self.label_9.setText(_translate("Form", "TN density Reload", None))
        self.label_11.setText(_translate("Form", "TN scenes Reload", None))
        self.label_10.setText(_translate("Form", "TN Set", None))
        self.pushButton_display0.setText(_translate("Form", "None", None))
        self.pushButton_display1.setText(_translate("Form", "Point", None))
        self.pushButton_display2.setText(_translate("Form", "Box", None))
        self.pushButton_copy.setText(_translate("Form", "Duplicate", None))
        self.pushButton_set0.setText(_translate("Form", "BaseMesh Set", None))
        self.pushButton_set1.setText(_translate("Form", "TN_Tane Set", None))
        self.pushButton_sc.setText(_translate("Form", "abcProxy node rename", None))
        self.pushButton_update1.setText(_translate("Form", "On", None))
        self.pushButton_update0.setText(_translate("Form", "Off", None))
        self.pushButton_bake1.setText(_translate("Form", "On", None))
        self.pushButton_bake0.setText(_translate("Form", "Off", None))
        self.pushButton_reload.setText(_translate("Form", "Reload mask Map", None))
        self.pushButton_reload2.setText(_translate("Form", "Reload Scenes", None))

