# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpuControlTool_UI_v01.ui'
#
# Created: Thu Aug 30 11:12:13 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from pymodule.Qt import QtCore
from pymodule.Qt import QtWidgets as QtGui
import pymodule.Qt as Qt

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(290, 658)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 520, 101, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(100, 528, 151, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 560, 91, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 580, 91, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 570, 211, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 620, 161, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 490, 91, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 211, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 101, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(10, 50, 271, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 271, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 590, 211, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 20, 161, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 620, 101, 31))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 480, 271, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 211, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(10, 370, 271, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 380, 211, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton_14 = QtGui.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 440, 271, 31))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 170, 101, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBox_3 = QtGui.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 150, 91, 21))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(70, 180, 91, 21))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.pushButton_6 = QtGui.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 150, 101, 51))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 110, 271, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 410, 231, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 400, 41, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(10, 200, 271, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.pushButton_8 = QtGui.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 270, 261, 31))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(10, 300, 271, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 310, 131, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_9 = QtGui.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 330, 271, 31))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 210, 201, 21))
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_RED = QtGui.QPushButton(Form)
        self.pushButton_RED.setGeometry(QtCore.QRect(10, 240, 21, 21))
        self.pushButton_RED.setStyleSheet(_fromUtf8("background-color:red"))
        self.pushButton_RED.setText(_fromUtf8(""))
        self.pushButton_RED.setObjectName(_fromUtf8("pushButton_RED"))
        self.pushButton_Purple = QtGui.QPushButton(Form)
        self.pushButton_Purple.setGeometry(QtCore.QRect(150, 240, 21, 21))
        self.pushButton_Purple.setStyleSheet(_fromUtf8("background-color:rgb(102, 0, 153)"))
        self.pushButton_Purple.setText(_fromUtf8(""))
        self.pushButton_Purple.setObjectName(_fromUtf8("pushButton_Purple"))
        self.pushButton_Yellow = QtGui.QPushButton(Form)
        self.pushButton_Yellow.setGeometry(QtCore.QRect(50, 240, 21, 21))
        self.pushButton_Yellow.setStyleSheet(_fromUtf8("background-color:yellow"))
        self.pushButton_Yellow.setText(_fromUtf8(""))
        self.pushButton_Yellow.setObjectName(_fromUtf8("pushButton_Yellow"))
        self.pushButton_Trans = QtGui.QPushButton(Form)
        self.pushButton_Trans.setGeometry(QtCore.QRect(190, 240, 21, 21))
        self.pushButton_Trans.setStyleSheet(_fromUtf8("background-color:rgb(0, 213, 255)"))
        self.pushButton_Trans.setObjectName(_fromUtf8("pushButton_Trans"))
        self.pushButton_Sky = QtGui.QPushButton(Form)
        self.pushButton_Sky.setGeometry(QtCore.QRect(110, 240, 21, 21))
        self.pushButton_Sky.setStyleSheet(_fromUtf8("background-color:rgb(0, 213, 255)"))
        self.pushButton_Sky.setText(_fromUtf8(""))
        self.pushButton_Sky.setObjectName(_fromUtf8("pushButton_Sky"))
        self.pushButton_Orange = QtGui.QPushButton(Form)
        self.pushButton_Orange.setGeometry(QtCore.QRect(30, 240, 21, 21))
        self.pushButton_Orange.setStyleSheet(_fromUtf8("background-color:orange"))
        self.pushButton_Orange.setText(_fromUtf8(""))
        self.pushButton_Orange.setObjectName(_fromUtf8("pushButton_Orange"))
        self.pushButton_Blue = QtGui.QPushButton(Form)
        self.pushButton_Blue.setGeometry(QtCore.QRect(130, 240, 21, 21))
        self.pushButton_Blue.setStyleSheet(_fromUtf8("background-color:rgb(0, 4, 255)"))
        self.pushButton_Blue.setText(_fromUtf8(""))
        self.pushButton_Blue.setObjectName(_fromUtf8("pushButton_Blue"))
        self.pushButton_YellowGreen = QtGui.QPushButton(Form)
        self.pushButton_YellowGreen.setGeometry(QtCore.QRect(70, 240, 21, 21))
        self.pushButton_YellowGreen.setStyleSheet(_fromUtf8("background-color:rgb(188, 225, 0)"))
        self.pushButton_YellowGreen.setText(_fromUtf8(""))
        self.pushButton_YellowGreen.setObjectName(_fromUtf8("pushButton_YellowGreen"))
        self.pushButton_Green = QtGui.QPushButton(Form)
        self.pushButton_Green.setGeometry(QtCore.QRect(90, 240, 21, 21))
        self.pushButton_Green.setStyleSheet(_fromUtf8("background-color:rgb(0, 170, 0)"))
        self.pushButton_Green.setText(_fromUtf8(""))
        self.pushButton_Green.setObjectName(_fromUtf8("pushButton_Green"))
        self.pushButton_lambert1 = QtGui.QPushButton(Form)
        self.pushButton_lambert1.setGeometry(QtCore.QRect(220, 230, 51, 31))
        self.pushButton_lambert1.setObjectName(_fromUtf8("pushButton_lambert1"))
        self.pushButton_Purple_2 = QtGui.QPushButton(Form)
        self.pushButton_Purple_2.setGeometry(QtCore.QRect(170, 240, 21, 21))
        self.pushButton_Purple_2.setStyleSheet(_fromUtf8("background-color:rgb(255, 0, 255)"))
        self.pushButton_Purple_2.setText(_fromUtf8(""))
        self.pushButton_Purple_2.setObjectName(_fromUtf8("pushButton_Purple_2"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "GPU Control Tool", None))
        self.label.setText(_translate("Form", "change Type: ", None))
        self.comboBox.setItemText(0, _translate("Form", "gpu", None))
        self.comboBox.setItemText(1, _translate("Form", "ZEnv", None))
        self.comboBox.setItemText(2, _translate("Form", "TANE", None))
        self.comboBox.setItemText(3, _translate("Form", "TANE_MAP", None))
        self.label_2.setText(_translate("Form", "Search:", None))
        self.label_3.setText(_translate("Form", "Replace:", None))
        self.pushButton.setText(_translate("Form", "All ", None))
        self.label_4.setText(_translate("Form", "Path Edit", None))
        self.label_5.setText(_translate("Form", "Layout Export Mode Changer", None))
        self.label_6.setText(_translate("Form", "Connect GPU", None))
        self.pushButton_2.setText(_translate("Form", "Selected", None))
        self.pushButton_5.setText(_translate("Form", "connect Creator ", None))
        self.pushButton_3.setText(_translate("Form", "All", None))
        self.pushButton_4.setText(_translate("Form", "Selected", None))
        self.label_7.setText(_translate("Form", "GPU Mode Changer", None))
        self.label_9.setText(_translate("Form", "Multi ABC Export", None))
        self.pushButton_14.setText(_translate("Form", "Export", None))
        self.label_13.setText(_translate("Form", "Mode:", None))
        self.label_14.setText(_translate("Form", "Display:", None))
        self.comboBox_3.setItemText(0, _translate("Form", "GPU", None))
        self.comboBox_3.setItemText(1, _translate("Form", "Mesh", None))
        self.comboBox_4.setItemText(0, _translate("Form", "Low", None))
        self.comboBox_4.setItemText(1, _translate("Form", "Render", None))
        self.pushButton_6.setText(_translate("Form", "Reload", None))
        self.label_8.setText(_translate("Form", "Path:", None))
        self.pushButton_8.setText(_translate("Form", "RandomAssign", None))
        self.label_11.setText(_translate("Form", "GPU create Group", None))
        self.pushButton_9.setText(_translate("Form", "selected", None))
        self.label_12.setText(_translate("Form", "GPU Viewport Color Assign", None))
        self.pushButton_Trans.setText(_translate("Form", "T", None))
        self.pushButton_lambert1.setText(_translate("Form", "reset", None))

