# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_usdsgviewer.ui',
# licensing of 'ui_usdsgviewer.ui' applies.
#
# Created: Thu Apr 22 11:05:32 2021
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1283, 918)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_11 = QtWidgets.QGridLayout(Form)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setMinimumSize(QtCore.QSize(1100, 818))
        self.main_frame.setAutoFillBackground(False)
        self.main_frame.setStyleSheet("")
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_frame.setLineWidth(2)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.layout_7 = QtWidgets.QVBoxLayout()
        self.layout_7.setSpacing(2)
        self.layout_7.setContentsMargins(0, -1, -1, 0)
        self.layout_7.setObjectName("layout_7")
        self.sceneGraph_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraph_frame.sizePolicy().hasHeightForWidth())
        self.sceneGraph_frame.setSizePolicy(sizePolicy)
        self.sceneGraph_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.sceneGraph_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sceneGraph_frame.setObjectName("sceneGraph_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sceneGraph_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.sceneGraph_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.layout_8 = QtWidgets.QHBoxLayout()
        self.layout_8.setObjectName("layout_8")
        self.show_label = QtWidgets.QLabel(self.frame_2)
        self.show_label.setMinimumSize(QtCore.QSize(80, 35))
        self.show_label.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.show_label.setFont(font)
        self.show_label.setStyleSheet("")
        self.show_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.show_label.setObjectName("show_label")
        self.layout_8.addWidget(self.show_label)
        self.show_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.show_comboBox.setMinimumSize(QtCore.QSize(100, 35))
        self.show_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.show_comboBox.setFont(font)
        self.show_comboBox.setMouseTracking(True)
        self.show_comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.show_comboBox.setStyleSheet("")
        self.show_comboBox.setObjectName("show_comboBox")
        self.layout_8.addWidget(self.show_comboBox)
        self.shot_label = QtWidgets.QLabel(self.frame_2)
        self.shot_label.setMinimumSize(QtCore.QSize(0, 30))
        self.shot_label.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.shot_label.setFont(font)
        self.shot_label.setStyleSheet("")
        self.shot_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shot_label.setObjectName("shot_label")
        self.layout_8.addWidget(self.shot_label)
        self.shot_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_lineEdit.sizePolicy().hasHeightForWidth())
        self.shot_lineEdit.setSizePolicy(sizePolicy)
        self.shot_lineEdit.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.shot_lineEdit.setFont(font)
        self.shot_lineEdit.setStyleSheet("")
        self.shot_lineEdit.setObjectName("shot_lineEdit")
        self.layout_8.addWidget(self.shot_lineEdit)
        self.search_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.search_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.search_pushButton.setFont(font)
        self.search_pushButton.setStyleSheet("")
        self.search_pushButton.setObjectName("search_pushButton")
        self.layout_8.addWidget(self.search_pushButton)
        self.usdviewer_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.usdviewer_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.usdviewer_pushButton.setFont(font)
        self.usdviewer_pushButton.setStyleSheet("")
        self.usdviewer_pushButton.setObjectName("usdviewer_pushButton")
        self.layout_8.addWidget(self.usdviewer_pushButton)
        self.render_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.render_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.render_pushButton.setFont(font)
        self.render_pushButton.setStyleSheet("")
        self.render_pushButton.setObjectName("render_pushButton")
        self.layout_8.addWidget(self.render_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_8.addItem(spacerItem)
        self.save_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.save_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setStyleSheet("")
        self.save_pushButton.setObjectName("save_pushButton")
        self.layout_8.addWidget(self.save_pushButton)
        self.verticalLayout_9.addLayout(self.layout_8)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.layout_9 = QtWidgets.QHBoxLayout()
        self.layout_9.setSpacing(4)
        self.layout_9.setObjectName("layout_9")
        self.sceneGraph_label = QtWidgets.QLabel(self.sceneGraph_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraph_label.sizePolicy().hasHeightForWidth())
        self.sceneGraph_label.setSizePolicy(sizePolicy)
        self.sceneGraph_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.sceneGraph_label.setFont(font)
        self.sceneGraph_label.setStyleSheet("")
        self.sceneGraph_label.setObjectName("sceneGraph_label")
        self.layout_9.addWidget(self.sceneGraph_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_9.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.layout_9)
        self.frame = QtWidgets.QFrame(self.sceneGraph_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 680))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.sceneGraph_treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.sceneGraph_treeWidget.setGeometry(QtCore.QRect(10, 11, 450, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraph_treeWidget.sizePolicy().hasHeightForWidth())
        self.sceneGraph_treeWidget.setSizePolicy(sizePolicy)
        self.sceneGraph_treeWidget.setMinimumSize(QtCore.QSize(450, 450))
        self.sceneGraph_treeWidget.setStyleSheet("")
        self.sceneGraph_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sceneGraph_treeWidget.setRootIsDecorated(True)
        self.sceneGraph_treeWidget.setHeaderHidden(True)
        self.sceneGraph_treeWidget.setObjectName("sceneGraph_treeWidget")
        self.sceneGraph_treeWidget.headerItem().setText(0, "1")
        self.variants_label = QtWidgets.QLabel(self.frame)
        self.variants_label.setGeometry(QtCore.QRect(10, 470, 180, 25))
        self.variants_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.variants_label.setFont(font)
        self.variants_label.setStyleSheet("")
        self.variants_label.setObjectName("variants_label")
        self.variant_treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.variant_treeWidget.setGeometry(QtCore.QRect(10, 501, 450, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variant_treeWidget.sizePolicy().hasHeightForWidth())
        self.variant_treeWidget.setSizePolicy(sizePolicy)
        self.variant_treeWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.variant_treeWidget.setStyleSheet("")
        self.variant_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.variant_treeWidget.setRootIsDecorated(True)
        self.variant_treeWidget.setHeaderHidden(True)
        self.variant_treeWidget.setObjectName("variant_treeWidget")
        self.variant_treeWidget.headerItem().setText(0, "1")
        self.metadata_label_3 = QtWidgets.QLabel(self.frame)
        self.metadata_label_3.setGeometry(QtCore.QRect(470, 10, 180, 20))
        self.metadata_label_3.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.metadata_label_3.setFont(font)
        self.metadata_label_3.setStyleSheet("")
        self.metadata_label_3.setObjectName("metadata_label_3")
        self.metadata_treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.metadata_treeWidget.setGeometry(QtCore.QRect(470, 40, 761, 731))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadata_treeWidget.sizePolicy().hasHeightForWidth())
        self.metadata_treeWidget.setSizePolicy(sizePolicy)
        self.metadata_treeWidget.setMinimumSize(QtCore.QSize(450, 450))
        self.metadata_treeWidget.setStyleSheet("")
        self.metadata_treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.metadata_treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.metadata_treeWidget.setAutoScroll(False)
        self.metadata_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.metadata_treeWidget.setRootIsDecorated(True)
        self.metadata_treeWidget.setHeaderHidden(True)
        self.metadata_treeWidget.setColumnCount(2)
        self.metadata_treeWidget.setObjectName("metadata_treeWidget")
        self.metadata_treeWidget.headerItem().setText(0, "1")
        self.metadata_treeWidget.headerItem().setText(1, "2")
        self.verticalLayout_5.addWidget(self.frame)
        self.layout_7.addWidget(self.sceneGraph_frame)
        self.layout_3.addLayout(self.layout_7)
        self.verticalLayout_2.addLayout(self.layout_3)
        self.gridLayout_11.addWidget(self.main_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.show_label.setText(QtWidgets.QApplication.translate("Form", "Show -  ", None, -1))
        self.shot_label.setText(QtWidgets.QApplication.translate("Form", "  Shot - ", None, -1))
        self.search_pushButton.setText(QtWidgets.QApplication.translate("Form", "SEARCH", None, -1))
        self.usdviewer_pushButton.setText(QtWidgets.QApplication.translate("Form", "VIEWER", None, -1))
        self.render_pushButton.setText(QtWidgets.QApplication.translate("Form", "USDRECODER", None, -1))
        self.save_pushButton.setText(QtWidgets.QApplication.translate("Form", "SAVE", None, -1))
        self.sceneGraph_label.setText(QtWidgets.QApplication.translate("Form", "SCENEGRAPH", None, -1))
        self.variants_label.setText(QtWidgets.QApplication.translate("Form", "VARIANTS", None, -1))
        self.metadata_label_3.setText(QtWidgets.QApplication.translate("Form", "METADATA", None, -1))

