# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_assetLibUtils.ui',
# licensing of './ui_assetLibUtils.ui' applies.
#
# Created: Tue Jul  5 12:42:15 2022
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AssetLibUtils(object):
    def setupUi(self, AssetLibUtils):
        AssetLibUtils.setObjectName("AssetLibUtils")
        AssetLibUtils.resize(808, 249)
        self.tabWidget = QtWidgets.QTabWidget(AssetLibUtils)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 791, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.render_tab = QtWidgets.QWidget()
        self.render_tab.setObjectName("render_tab")
        self.render_pushButton = QtWidgets.QPushButton(self.render_tab)
        self.render_pushButton.setGeometry(QtCore.QRect(630, 150, 151, 51))
        self.render_pushButton.setObjectName("render_pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.render_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 127))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.render_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.render_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.render_gridLayout.setObjectName("render_gridLayout")
        self.renderpath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.renderpath_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.renderpath_pushButton.setObjectName("renderpath_pushButton")
        self.render_gridLayout.addWidget(self.renderpath_pushButton, 1, 2, 1, 1)
        self.frame_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.frame_label.setObjectName("frame_label")
        self.render_gridLayout.addWidget(self.frame_label, 2, 0, 1, 1)
        self.renderpath_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.renderpath_label.setObjectName("renderpath_label")
        self.render_gridLayout.addWidget(self.renderpath_label, 1, 0, 1, 1)
        self.scene_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.scene_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.scene_pushButton.setObjectName("scene_pushButton")
        self.render_gridLayout.addWidget(self.scene_pushButton, 0, 2, 1, 1)
        self.renderpath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.renderpath_lineEdit.setObjectName("renderpath_lineEdit")
        self.render_gridLayout.addWidget(self.renderpath_lineEdit, 1, 1, 1, 1)
        self.scene_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scene_label.setObjectName("scene_label")
        self.render_gridLayout.addWidget(self.scene_label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameIn_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.frameIn_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameIn_lineEdit.setObjectName("frameIn_lineEdit")
        self.horizontalLayout.addWidget(self.frameIn_lineEdit)
        self._label = QtWidgets.QLabel(self.gridLayoutWidget)
        self._label.setMaximumSize(QtCore.QSize(5, 5))
        self._label.setObjectName("_label")
        self.horizontalLayout.addWidget(self._label)
        self.frameOut_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.frameOut_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameOut_lineEdit.setObjectName("frameOut_lineEdit")
        self.horizontalLayout.addWidget(self.frameOut_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.render_gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.scene_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.scene_lineEdit.setObjectName("scene_lineEdit")
        self.render_gridLayout.addWidget(self.scene_lineEdit, 0, 1, 1, 1)
        self.camera_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.camera_label.setObjectName("camera_label")
        self.render_gridLayout.addWidget(self.camera_label, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.camera_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.camera_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.camera_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.camera_comboBox.setObjectName("camera_comboBox")
        self.horizontalLayout_3.addWidget(self.camera_comboBox)
        self.reload_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reload_pushButton.setObjectName("reload_pushButton")
        self.horizontalLayout_3.addWidget(self.reload_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.render_gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.tabWidget.addTab(self.render_tab, "")
        self.assign_tab = QtWidgets.QWidget()
        self.assign_tab.setObjectName("assign_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.assign_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 771, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.assign_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.assign_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.assign_gridLayout.setObjectName("assign_gridLayout")
        self.txPath_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.txPath_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.txPath_pushButton.setObjectName("txPath_pushButton")
        self.assign_gridLayout.addWidget(self.txPath_pushButton, 0, 2, 1, 1)
        self.txPath_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.txPath_label.setObjectName("txPath_label")
        self.assign_gridLayout.addWidget(self.txPath_label, 0, 0, 1, 1)
        self.txPath_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txPath_lineEdit.setObjectName("txPath_lineEdit")
        self.assign_gridLayout.addWidget(self.txPath_lineEdit, 0, 1, 1, 1)
        self.assign_pushButton = QtWidgets.QPushButton(self.assign_tab)
        self.assign_pushButton.setGeometry(QtCore.QRect(630, 150, 151, 51))
        self.assign_pushButton.setObjectName("assign_pushButton")
        self.tabWidget.addTab(self.assign_tab, "")

        self.retranslateUi(AssetLibUtils)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AssetLibUtils)

    def retranslateUi(self, AssetLibUtils):
        AssetLibUtils.setWindowTitle(QtWidgets.QApplication.translate("AssetLibUtils", "AssetLib Utils", None, -1))
        self.render_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "Send Tractor", None, -1))
        self.renderpath_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "...", None, -1))
        self.frame_label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "FrameRange", None, -1))
        self.renderpath_label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "RenderPath", None, -1))
        self.scene_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "...", None, -1))
        self.scene_label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "SceneName", None, -1))
        self._label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "-", None, -1))
        self.camera_label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "Camera", None, -1))
        self.reload_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "Reload", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.render_tab), QtWidgets.QApplication.translate("AssetLibUtils", "Render to Tractor", None, -1))
        self.txPath_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "...", None, -1))
        self.txPath_label.setText(QtWidgets.QApplication.translate("AssetLibUtils", "TexturePath", None, -1))
        self.assign_pushButton.setText(QtWidgets.QApplication.translate("AssetLibUtils", "Assign Shader", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assign_tab), QtWidgets.QApplication.translate("AssetLibUtils", "Assign", None, -1))
