# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playblast.ui',
# licensing of 'playblast.ui' applies.
#
# Created: Fri Aug 14 15:27:18 2020
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DDMM(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 358)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_logo = QtWidgets.QLabel(Dialog)
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_3.addWidget(self.label_logo)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_codec = QtWidgets.QComboBox(Dialog)
        self.comboBox_codec.setObjectName("comboBox_codec")
        self.gridLayout.addWidget(self.comboBox_codec, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_displaySize = QtWidgets.QComboBox(Dialog)
        self.comboBox_displaySize.setObjectName("comboBox_displaySize")
        self.gridLayout.addWidget(self.comboBox_displaySize, 2, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_width = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_width.setEnabled(False)
        self.lineEdit_width.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.horizontalLayout_6.addWidget(self.lineEdit_width)
        self.lineEdit_height = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_height.setEnabled(False)
        self.lineEdit_height.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.horizontalLayout_6.addWidget(self.lineEdit_height)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_frameRange = QtWidgets.QLabel(Dialog)
        self.label_frameRange.setObjectName("label_frameRange")
        self.horizontalLayout_9.addWidget(self.label_frameRange)
        self.label_duration = QtWidgets.QLabel(Dialog)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_9.addWidget(self.label_duration)
        self.label_fps = QtWidgets.QLabel(Dialog)
        self.label_fps.setObjectName("label_fps")
        self.horizontalLayout_9.addWidget(self.label_fps)
        self.label_size = QtWidgets.QLabel(Dialog)
        self.label_size.setObjectName("label_size")
        self.horizontalLayout_9.addWidget(self.label_size)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_9, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.doubleSpinBox_scale = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_scale.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_scale.setDecimals(1)
        self.doubleSpinBox_scale.setMinimum(0.1)
        self.doubleSpinBox_scale.setMaximum(1.0)
        self.doubleSpinBox_scale.setSingleStep(0.1)
        self.doubleSpinBox_scale.setProperty("value", 1.0)
        self.doubleSpinBox_scale.setObjectName("doubleSpinBox_scale")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_scale)
        self.horizontalSlider_scale = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_scale.setMinimum(1)
        self.horizontalSlider_scale.setMaximum(10)
        self.horizontalSlider_scale.setProperty("value", 10)
        self.horizontalSlider_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_scale.setObjectName("horizontalSlider_scale")
        self.horizontalLayout_8.addWidget(self.horizontalSlider_scale)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBox_sequence = QtWidgets.QComboBox(Dialog)
        self.comboBox_sequence.setObjectName("comboBox_sequence")
        self.gridLayout.addWidget(self.comboBox_sequence, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.comboBox_fps = QtWidgets.QComboBox(Dialog)
        self.comboBox_fps.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_fps.setObjectName("comboBox_fps")
        self.comboBox_fps.setEditable(True)
        self.gridLayout.addWidget(self.comboBox_fps, 5, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_output = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_output.setReadOnly(True)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_2.addWidget(self.lineEdit_output)
        self.toolButton_browse = QtWidgets.QToolButton(Dialog)
        self.toolButton_browse.setObjectName("toolButton_browse")
        self.horizontalLayout_2.addWidget(self.toolButton_browse)
        self.toolButton_explorer = QtWidgets.QToolButton(Dialog)
        self.toolButton_explorer.setObjectName("toolButton_explorer")
        self.horizontalLayout_2.addWidget(self.toolButton_explorer)
        self.toolButton_play = QtWidgets.QToolButton(Dialog)
        self.toolButton_play.setObjectName("toolButton_play")
        self.horizontalLayout_2.addWidget(self.toolButton_play)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_create = QtWidgets.QPushButton(Dialog)
        self.pushButton_create.setAutoDefault(False)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout.addWidget(self.pushButton_create)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_sequence, self.comboBox_codec)
        Dialog.setTabOrder(self.comboBox_codec, self.comboBox_displaySize)
        Dialog.setTabOrder(self.comboBox_displaySize, self.lineEdit_width)
        Dialog.setTabOrder(self.lineEdit_width, self.lineEdit_height)
        Dialog.setTabOrder(self.lineEdit_height, self.doubleSpinBox_scale)
        Dialog.setTabOrder(self.doubleSpinBox_scale, self.horizontalSlider_scale)
        Dialog.setTabOrder(self.horizontalSlider_scale, self.lineEdit_output)
        Dialog.setTabOrder(self.lineEdit_output, self.toolButton_browse)
        Dialog.setTabOrder(self.toolButton_browse, self.toolButton_explorer)
        Dialog.setTabOrder(self.toolButton_explorer, self.pushButton_create)
        Dialog.setTabOrder(self.pushButton_create, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "DDMM - DEXTER DiGITAL Mov Maker v0.23 by PPS", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Codec", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Scale", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Display size", None, -1))
        self.label_frameRange.setText(QtWidgets.QApplication.translate("Dialog", "1 ~ 150", None, -1))
        self.label_duration.setText(QtWidgets.QApplication.translate("Dialog", "150", None, -1))
        self.label_fps.setText(QtWidgets.QApplication.translate("Dialog", "24 fps", None, -1))
        self.label_size.setText(QtWidgets.QApplication.translate("Dialog", "(MB)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Info", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Sequence", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "FPS", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Output", None, -1))
        self.toolButton_browse.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.toolButton_explorer.setText(QtWidgets.QApplication.translate("Dialog", "Explore", None, -1))
        self.toolButton_play.setText(QtWidgets.QApplication.translate("Dialog", "Play", None, -1))
        self.pushButton_create.setText(QtWidgets.QApplication.translate("Dialog", "Create", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))
