# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shotpub_anim_widget.ui'
#
# Created: Wed May 10 11:34:03 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

#from PyQt4 import QtCore, QtGui
from PySide2 import QtCore, QtGui, QtWidgets


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_shotpub_camera_Dialog(object):
    def setupUi(self, shotpub_camera_Dialog):
        shotpub_camera_Dialog.setObjectName(_fromUtf8("shotpub_camera_Dialog"))
        shotpub_camera_Dialog.setEnabled(True)
        shotpub_camera_Dialog.resize(474, 729)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(shotpub_camera_Dialog)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setObjectName(_fromUtf8("header_layout"))
        self.header = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.header.setMinimumSize(QtCore.QSize(0, 0))
        self.header.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.header.setFont(font)
        self.header.setObjectName(_fromUtf8("header"))
        self.header_layout.addWidget(self.header)
        self.ver = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.ver.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ver.setObjectName(_fromUtf8("ver"))
        self.header_layout.addWidget(self.ver)
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.header_layout)
        self.pub_layout = QtWidgets.QHBoxLayout()
        self.pub_layout.setObjectName(_fromUtf8("pub_layout"))
        self.pub = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.pub.setMinimumSize(QtCore.QSize(100, 30))
        self.pub.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pub.setObjectName(_fromUtf8("pub"))
        self.pub_layout.addWidget(self.pub)
        self.showUI = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.showUI.setMinimumSize(QtCore.QSize(100, 0))
        self.showUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.showUI.setObjectName(_fromUtf8("showUI"))
        self.showUI.addItem(_fromUtf8(""))
        self.pub_layout.addWidget(self.showUI)
        self.seqUI = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.seqUI.setMinimumSize(QtCore.QSize(100, 0))
        self.seqUI.setObjectName(_fromUtf8("seqUI"))
        self.seqUI.addItem(_fromUtf8(""))
        self.pub_layout.addWidget(self.seqUI)
        self.shotUI = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.shotUI.setMinimumSize(QtCore.QSize(120, 0))
        self.shotUI.setObjectName(_fromUtf8("shotUI"))
        self.shotUI.addItem(_fromUtf8(""))
        self.pub_layout.addWidget(self.shotUI)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.pub_layout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.pub_layout)
        self.user_layout = QtWidgets.QHBoxLayout()
        self.user_layout.setObjectName(_fromUtf8("user_layout"))
        self.user = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.user.setMinimumSize(QtCore.QSize(100, 30))
        self.user.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.user.setObjectName(_fromUtf8("user"))
        self.user_layout.addWidget(self.user)
        self.userUI = QtWidgets.QLineEdit(shotpub_camera_Dialog)
        self.userUI.setMaximumSize(QtCore.QSize(150, 16777215))
        self.userUI.setObjectName(_fromUtf8("userUI"))
        self.user_layout.addWidget(self.userUI)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.user_layout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.user_layout)
        self.dept_layout = QtWidgets.QHBoxLayout()
        self.dept_layout.setObjectName(_fromUtf8("dept_layout"))
        self.dept = QtWidgets.QLabel(shotpub_camera_Dialog)
        self.dept.setMinimumSize(QtCore.QSize(100, 30))
        self.dept.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dept.setObjectName(_fromUtf8("dept"))
        self.dept_layout.addWidget(self.dept)
        self.deptUI = QtWidgets.QComboBox(shotpub_camera_Dialog)
        self.deptUI.setMinimumSize(QtCore.QSize(100, 0))
        self.deptUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.deptUI.setObjectName(_fromUtf8("deptUI"))
        self.deptUI.addItem(_fromUtf8(""))
        self.deptUI.addItem(_fromUtf8(""))
        self.dept_layout.addWidget(self.deptUI)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.dept_layout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.dept_layout)
        self.sceneOptions = QtWidgets.QGroupBox(shotpub_camera_Dialog)
        self.sceneOptions.setObjectName(_fromUtf8("sceneOptions"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sceneOptions)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sceneOptions_layout = QtWidgets.QGridLayout()
        self.sceneOptions_layout.setObjectName(_fromUtf8("sceneOptions_layout"))
        spacerItem4 = QtWidgets.QSpacerItem(40, 20,
                                        QtWidgets.QSizePolicy.Expanding,
                                        QtWidgets.QSizePolicy.Minimum)
        self.sceneOptions_layout.addItem(spacerItem4, 0, 3, 3, 1)
        self.endFrameUI = QtWidgets.QLineEdit(self.sceneOptions)
        self.endFrameUI.setMinimumSize(QtCore.QSize(70, 0))
        self.endFrameUI.setMaximumSize(QtCore.QSize(70, 16777215))
        self.endFrameUI.setObjectName(_fromUtf8("endFrameUI"))
        self.sceneOptions_layout.addWidget(self.endFrameUI, 0, 2, 2, 1)
        self.startFrameUI = QtWidgets.QLineEdit(self.sceneOptions)
        self.startFrameUI.setMinimumSize(QtCore.QSize(70, 0))
        self.startFrameUI.setMaximumSize(QtCore.QSize(70, 16777215))
        self.startFrameUI.setObjectName(_fromUtf8("startFrameUI"))
        self.sceneOptions_layout.addWidget(self.startFrameUI, 0, 1, 2, 1)
        self.frame = QtWidgets.QLabel(self.sceneOptions)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.sceneOptions_layout.addWidget(self.frame, 0, 0, 2, 1)
        self.renderRes = QtWidgets.QLabel(self.sceneOptions)
        self.renderRes.setObjectName(_fromUtf8("renderRes"))
        self.sceneOptions_layout.addWidget(self.renderRes, 2, 0, 1, 1)
        self.renderWidthUI = QtWidgets.QLineEdit(self.sceneOptions)
        self.renderWidthUI.setMinimumSize(QtCore.QSize(70, 0))
        self.renderWidthUI.setMaximumSize(QtCore.QSize(70, 16777215))
        self.renderWidthUI.setObjectName(_fromUtf8("renderWidthUI"))
        self.sceneOptions_layout.addWidget(self.renderWidthUI, 2, 1, 1, 1)
        self.renderHeightUI = QtWidgets.QLineEdit(self.sceneOptions)
        self.renderHeightUI.setMinimumSize(QtCore.QSize(70, 0))
        self.renderHeightUI.setMaximumSize(QtCore.QSize(70, 16777215))
        self.renderHeightUI.setObjectName(_fromUtf8("renderHeightUI"))
        self.sceneOptions_layout.addWidget(self.renderHeightUI, 2, 2, 1, 1)
        self.fullCGUI = QtWidgets.QCheckBox(self.sceneOptions)
        self.fullCGUI.setEnabled(True)
        self.fullCGUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fullCGUI.setCheckable(True)
        self.fullCGUI.setChecked(False)
        self.fullCGUI.setObjectName(_fromUtf8("fullCGUI"))
        self.sceneOptions_layout.addWidget(self.fullCGUI, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.sceneOptions_layout)
        self.verticalLayout_4.addWidget(self.sceneOptions)
        self.sdbNode_layout = QtWidgets.QGroupBox(shotpub_camera_Dialog)
        self.sdbNode_layout.setObjectName(_fromUtf8("sdbNode_layout"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sdbNode_layout)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.sdbNodeUI = QtWidgets.QListWidget(self.sdbNode_layout)
        self.sdbNodeUI.setObjectName(_fromUtf8("sdbNodeUI"))
        self.verticalLayout_3.addWidget(self.sdbNodeUI)
        self.verticalLayout_4.addWidget(self.sdbNode_layout)
        self.camOptions = QtWidgets.QGroupBox(shotpub_camera_Dialog)
        self.camOptions.setObjectName(_fromUtf8("camOptions"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.camOptions)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.camOptions_layout1 = QtWidgets.QGridLayout()
        self.camOptions_layout1.setObjectName(_fromUtf8("camOptions_layout1"))
        self.leftCamLabel = QtWidgets.QLabel(self.camOptions)
        self.leftCamLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.leftCamLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftCamLabel.setObjectName(_fromUtf8("leftCamLabel"))
        self.camOptions_layout1.addWidget(self.leftCamLabel, 0, 0, 1, 1)
        self.leftCamUI = QtWidgets.QComboBox(self.camOptions)
        self.leftCamUI.setMinimumSize(QtCore.QSize(250, 0))
        self.leftCamUI.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftCamUI.setObjectName(_fromUtf8("leftCamUI"))
        self.camOptions_layout1.addWidget(self.leftCamUI, 0, 1, 1, 1)
        self.reloadUI = QtWidgets.QPushButton(self.camOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reloadUI.sizePolicy().hasHeightForWidth())
        self.reloadUI.setSizePolicy(sizePolicy)
        self.reloadUI.setMinimumSize(QtCore.QSize(60, 0))
        self.reloadUI.setMaximumSize(QtCore.QSize(60, 16777215))
        self.reloadUI.setObjectName(_fromUtf8("reloadUI"))
        self.camOptions_layout1.addWidget(self.reloadUI, 0, 2, 2, 1)
        self.rightCamLabel = QtWidgets.QLabel(self.camOptions)
        self.rightCamLabel.setEnabled(False)
        self.rightCamLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.rightCamLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightCamLabel.setObjectName(_fromUtf8("rightCamLabel"))
        self.camOptions_layout1.addWidget(self.rightCamLabel, 1, 0, 1, 1)
        self.rightCamUI = QtWidgets.QComboBox(self.camOptions)
        self.rightCamUI.setEnabled(False)
        self.rightCamUI.setMinimumSize(QtCore.QSize(250, 0))
        self.rightCamUI.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rightCamUI.setObjectName(_fromUtf8("rightCamUI"))
        self.camOptions_layout1.addWidget(self.rightCamUI, 1, 1, 1, 1)
        self.plate = QtWidgets.QLabel(self.camOptions)
        self.plate.setEnabled(True)
        self.plate.setMinimumSize(QtCore.QSize(0, 0))
        self.plate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plate.setObjectName(_fromUtf8("plate"))
        self.camOptions_layout1.addWidget(self.plate, 3, 0, 1, 1)
        self.plateTypeUI = QtWidgets.QComboBox(self.camOptions)
        self.plateTypeUI.setEnabled(True)
        self.plateTypeUI.setMinimumSize(QtCore.QSize(100, 0))
        self.plateTypeUI.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plateTypeUI.setObjectName(_fromUtf8("plateTypeUI"))
        self.plateTypeUI.addItem(_fromUtf8(""))
        self.camOptions_layout1.addWidget(self.plateTypeUI, 3, 1, 1, 1)
        self.stereoUI = QtWidgets.QCheckBox(self.camOptions)
        self.stereoUI.setObjectName(_fromUtf8("stereoUI"))
        self.camOptions_layout1.addWidget(self.stereoUI, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20,
                                        QtWidgets.QSizePolicy.Expanding,
                                        QtWidgets.QSizePolicy.Minimum)
        self.camOptions_layout1.addItem(spacerItem5, 0, 3, 4, 1)
        self.verticalLayout.addLayout(self.camOptions_layout1)
        self.camOptions_line = QtWidgets.QFrame(self.camOptions)
        self.camOptions_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.camOptions_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.camOptions_line.setObjectName(_fromUtf8("camOptions_line"))
        self.verticalLayout.addWidget(self.camOptions_line)
        self.camOptions_layout3 = QtWidgets.QGridLayout()
        self.camOptions_layout3.setObjectName(_fromUtf8("camOptions_layout3"))
        self.mayaCamUI = QtWidgets.QCheckBox(self.camOptions)
        self.mayaCamUI.setEnabled(False)
        self.mayaCamUI.setMinimumSize(QtCore.QSize(0, 0))
        self.mayaCamUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mayaCamUI.setCheckable(True)
        self.mayaCamUI.setChecked(True)
        self.mayaCamUI.setObjectName(_fromUtf8("mayaCamUI"))
        self.camOptions_layout3.addWidget(self.mayaCamUI, 0, 0, 1, 1)
        self.bakeCamUI = QtWidgets.QCheckBox(self.camOptions)
        self.bakeCamUI.setEnabled(False)
        self.bakeCamUI.setCheckable(True)
        self.bakeCamUI.setChecked(True)
        self.bakeCamUI.setObjectName(_fromUtf8("bakeCamUI"))
        self.camOptions_layout3.addWidget(self.bakeCamUI, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.camOptions_layout3.addItem(spacerItem6, 0, 2, 2, 1)
        self.abcCamUI = QtWidgets.QCheckBox(self.camOptions)
        self.abcCamUI.setEnabled(True)
        self.abcCamUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.abcCamUI.setCheckable(True)
        self.abcCamUI.setChecked(True)
        self.abcCamUI.setObjectName(_fromUtf8("abcCamUI"))
        self.camOptions_layout3.addWidget(self.abcCamUI, 1, 0, 1, 1)
        self.fbxCamUI = QtWidgets.QCheckBox(self.camOptions)
        self.fbxCamUI.setEnabled(True)
        self.fbxCamUI.setCheckable(True)
        self.fbxCamUI.setChecked(True)
        self.fbxCamUI.setObjectName(_fromUtf8("fbxCamUI"))
        self.camOptions_layout3.addWidget(self.fbxCamUI, 1, 1, 1, 1)
        self.renewIPUI = QtWidgets.QCheckBox(self.camOptions)
        self.renewIPUI.setEnabled(True)
        self.renewIPUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.renewIPUI.setCheckable(True)
        self.renewIPUI.setChecked(True)
        self.renewIPUI.setObjectName(_fromUtf8("renewIPUI"))
        self.camOptions_layout3.addWidget(self.renewIPUI, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.camOptions_layout3)
        self.verticalLayout_4.addWidget(self.camOptions)
        self.do_layout = QtWidgets.QHBoxLayout()
        self.do_layout.setObjectName(_fromUtf8("do_layout"))
        spacerItem7 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.do_layout.addItem(spacerItem7)
        self.doUI = QtWidgets.QPushButton(shotpub_camera_Dialog)
        self.doUI.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doUI.setObjectName(_fromUtf8("doUI"))
        self.do_layout.addWidget(self.doUI)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.do_layout.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.do_layout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)

        self.retranslateUi(shotpub_camera_Dialog)
        QtCore.QMetaObject.connectSlotsByName(shotpub_camera_Dialog)

    def retranslateUi(self, shotpub_camera_Dialog):
        shotpub_camera_Dialog.setWindowTitle(_translate("shotpub_camera_Dialog", "ShotPub - anim", None))
        self.header.setText(_translate("shotpub_camera_Dialog", "shotpub - anim", None))
        self.ver.setText(_translate("shotpub_camera_Dialog", "v1.3", None))
        self.pub.setText(_translate("shotpub_camera_Dialog", "Publish to", None))
        self.showUI.setItemText(0, _translate("shotpub_camera_Dialog", "select show", None))
        self.seqUI.setItemText(0, _translate("shotpub_camera_Dialog", "select seq", None))
        self.shotUI.setItemText(0, _translate("shotpub_camera_Dialog", "select shot", None))
        self.user.setText(_translate("shotpub_camera_Dialog", "User", None))
        self.dept.setText(_translate("shotpub_camera_Dialog", "Department", None))
        self.deptUI.setItemText(0, _translate("shotpub_camera_Dialog", "animation", None))
        self.deptUI.setItemText(1, _translate("shotpub_camera_Dialog", "matchmove", None))
        self.sceneOptions.setTitle(_translate("shotpub_camera_Dialog", "Scene Options", None))
        self.frame.setText(_translate("shotpub_camera_Dialog", "Frame Range", None))
        self.renderRes.setText(_translate("shotpub_camera_Dialog", "Render Res", None))
        self.fullCGUI.setText(_translate("shotpub_camera_Dialog", "Full CG", None))
        self.sdbNode_layout.setTitle(_translate("shotpub_camera_Dialog", "SDBNode List", None))
        self.camOptions.setTitle(_translate("shotpub_camera_Dialog", "Camera Options", None))
        self.leftCamLabel.setText(_translate("shotpub_camera_Dialog", "Camera", None))
        self.reloadUI.setText(_translate("shotpub_camera_Dialog", "Reload", None))
        self.rightCamLabel.setText(_translate("shotpub_camera_Dialog", "Only Stereo", None))
        self.plate.setText(_translate("shotpub_camera_Dialog", "Plate Type", None))
        self.plateTypeUI.setItemText(0, _translate("shotpub_camera_Dialog", "select shot", None))
        self.stereoUI.setText(_translate("shotpub_camera_Dialog", "Stereo Camera", None))
        self.mayaCamUI.setText(_translate("shotpub_camera_Dialog", "Maya Camera", None))
        self.bakeCamUI.setText(_translate("shotpub_camera_Dialog", "Bake Camera", None))
        self.abcCamUI.setText(_translate("shotpub_camera_Dialog", "Alembic Camera", None))
        self.fbxCamUI.setText(_translate("shotpub_camera_Dialog", "FBX Camera", None))
        self.renewIPUI.setText(_translate("shotpub_camera_Dialog", "Renew ImagePlane", None))
        self.doUI.setText(_translate("shotpub_camera_Dialog", "Publish", None))

