

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxAssetUI.ui'
#
# Created: Tue Mar  7 17:20:06 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

# import Qt
# import Qt.QtWidgets as QtGui
# from Qt import QtCore
from PySide2 import QtWidgets
from PySide2 import QtCore
from PySide2 import QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_assetCheckup_window(object):
    def setupUi(self, assetCheckup_window):
        assetCheckup_window.setObjectName(_fromUtf8("assetCheckup_window"))
        assetCheckup_window.resize(733, 818)
        self.centralwidget = QtWidgets.QWidget(assetCheckup_window)
        self.centralwidget.setMinimumSize(QtCore.QSize(358, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.assetname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.assetname_lineEdit.setMaximumSize(QtCore.QSize(16777215, 24))
        self.assetname_lineEdit.setObjectName(_fromUtf8("assetname_lineEdit"))
        self.assetname_lineEdit.setText('asset/assetName/texture')
        self.horizontalLayout_2.addWidget(self.assetname_lineEdit)
        self.fileDialog_pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.reloadAssetName_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileDialog_pushButton.sizePolicy().hasHeightForWidth())
        self.fileDialog_pushButton.setSizePolicy(sizePolicy)
        self.fileDialog_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.fileDialog_pushButton.setMaximumSize(QtCore.QSize(24, 16777215))
        self.fileDialog_pushButton.setObjectName(_fromUtf8("fileDialog_pushButton"))
        self.horizontalLayout_2.addWidget(self.fileDialog_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(-1, -1, 4, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.holed_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.holed_checkBox.setChecked(True)
        self.holed_checkBox.setObjectName(_fromUtf8("holed_checkBox"))
        self.gridLayout.addWidget(self.holed_checkBox, 0, 3, 1, 1)
        self.concave_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.concave_checkBox.setChecked(True)
        self.concave_checkBox.setObjectName(_fromUtf8("concave_checkBox"))
        self.gridLayout.addWidget(self.concave_checkBox, 0, 2, 1, 1)
        self.nside_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.nside_checkBox.setChecked(True)
        self.nside_checkBox.setObjectName(_fromUtf8("nside_checkBox"))
        self.gridLayout.addWidget(self.nside_checkBox, 0, 1, 1, 1)
        self.threeside_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.threeside_checkBox.setChecked(True)
        self.threeside_checkBox.setObjectName(_fromUtf8("threeside_checkBox"))
        self.gridLayout.addWidget(self.threeside_checkBox, 0, 0, 1, 1)
        self.nonmanifold_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.nonmanifold_checkBox.setChecked(True)
        self.nonmanifold_checkBox.setObjectName(_fromUtf8("nonmanifold_checkBox"))
        self.gridLayout.addWidget(self.nonmanifold_checkBox, 3, 2, 1, 1)
        self.twoedgevtx_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.twoedgevtx_checkBox.setChecked(True)
        self.twoedgevtx_checkBox.setObjectName(_fromUtf8("twoedgevtx_checkBox"))
        self.gridLayout.addWidget(self.twoedgevtx_checkBox, 3, 1, 1, 1)
        self.zeroedge_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.zeroedge_checkBox.setChecked(True)
        self.zeroedge_checkBox.setObjectName(_fromUtf8("zeroedge_checkBox"))
        self.gridLayout.addWidget(self.zeroedge_checkBox, 3, 0, 1, 1)
        self.multiuvset_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.multiuvset_checkBox.setChecked(True)
        self.multiuvset_checkBox.setObjectName(_fromUtf8("multiuvset_checkBox"))
        self.gridLayout.addWidget(self.multiuvset_checkBox, 2, 3, 1, 1)
        self.outsideuv_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.outsideuv_checkBox.setChecked(True)
        self.outsideuv_checkBox.setObjectName(_fromUtf8("outsideuv_checkBox"))
        self.gridLayout.addWidget(self.outsideuv_checkBox, 2, 2, 1, 1)
        self.zerouv_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.zerouv_checkBox.setChecked(True)
        self.zerouv_checkBox.setObjectName(_fromUtf8("zerouv_checkBox"))
        self.gridLayout.addWidget(self.zerouv_checkBox, 2, 1, 1, 1)
        self.zeroface_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.zeroface_checkBox.setChecked(True)
        self.zeroface_checkBox.setObjectName(_fromUtf8("zeroface_checkBox"))
        self.gridLayout.addWidget(self.zeroface_checkBox, 2, 0, 1, 1)
        self.twisted_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.twisted_checkBox.setChecked(True)
        self.twisted_checkBox.setObjectName(_fromUtf8("twisted_checkBox"))
        self.gridLayout.addWidget(self.twisted_checkBox, 1, 0, 1, 1)
        self.lamina_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.lamina_checkBox.setChecked(True)
        self.lamina_checkBox.setObjectName(_fromUtf8("lamina_checkBox"))
        self.gridLayout.addWidget(self.lamina_checkBox, 1, 1, 1, 1)
        self.overlapface_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.overlapface_checkBox.setChecked(False)
        self.overlapface_checkBox.setObjectName(_fromUtf8("overlapface_checkBox"))
        self.gridLayout.addWidget(self.overlapface_checkBox, 1, 2, 1, 1)
        self.overlapmesh_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.overlapmesh_checkBox.setObjectName(_fromUtf8("overlapmesh_checkBox"))
        self.gridLayout.addWidget(self.overlapmesh_checkBox, 1, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.geocheckup_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geocheckup_pushButton.sizePolicy().hasHeightForWidth())
        self.geocheckup_pushButton.setSizePolicy(sizePolicy)
        self.geocheckup_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.geocheckup_pushButton.setObjectName(_fromUtf8("geocheckup_pushButton"))
        self.horizontalLayout_4.addWidget(self.geocheckup_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, -1, 4, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.zeropivot_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.zeropivot_checkBox.setChecked(True)
        self.zeropivot_checkBox.setObjectName(_fromUtf8("zeropivot_checkBox"))
        self.gridLayout_2.addWidget(self.zeropivot_checkBox, 0, 2, 1, 1)
        self.zeromovevertex_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.zeromovevertex_checkBox.setChecked(True)
        self.zeromovevertex_checkBox.setObjectName(_fromUtf8("zeromovevertex_checkBox"))
        self.gridLayout_2.addWidget(self.zeromovevertex_checkBox, 0, 0, 1, 1)
        self.freezetransform_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.freezetransform_checkBox.setChecked(True)
        self.freezetransform_checkBox.setObjectName(_fromUtf8("freezetransform_checkBox"))
        self.gridLayout_2.addWidget(self.freezetransform_checkBox, 0, 1, 1, 1)
        self.deletehistory_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.deletehistory_checkBox.setChecked(True)
        self.deletehistory_checkBox.setObjectName(_fromUtf8("deletehistory_checkBox"))
        self.gridLayout_2.addWidget(self.deletehistory_checkBox, 0, 3, 1, 1)
        self.mergevertex_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.mergevertex_checkBox.setChecked(True)
        self.mergevertex_checkBox.setObjectName(_fromUtf8("mergevertex_checkBox"))
        self.gridLayout_2.addWidget(self.mergevertex_checkBox, 1, 0, 1, 1)
        self.normaifoldgeometry_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.normaifoldgeometry_checkBox.setChecked(False)
        self.normaifoldgeometry_checkBox.setObjectName(_fromUtf8("normaifoldgeometry_checkBox"))
        self.gridLayout_2.addWidget(self.normaifoldgeometry_checkBox, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.geosetup_pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geosetup_pushButton.sizePolicy().hasHeightForWidth())
        self.geosetup_pushButton.setSizePolicy(sizePolicy)
        self.geosetup_pushButton.setObjectName(_fromUtf8("geosetup_pushButton"))
        self.horizontalLayout_5.addWidget(self.geosetup_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.groupBox)
        self.attributes_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.attributes_groupBox.setCheckable(False)
        self.attributes_groupBox.setObjectName(_fromUtf8("attributes_groupBox"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.attributes_groupBox)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setContentsMargins(-1, 9, 4, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.objectname_checkBox = QtWidgets.QCheckBox(self.attributes_groupBox)
        self.objectname_checkBox.setChecked(True)
        self.objectname_checkBox.setObjectName(_fromUtf8("objectname_checkBox"))
        self.gridLayout_3.addWidget(self.objectname_checkBox, 0, 0, 1, 1)
        self.texture_checkBox = QtWidgets.QCheckBox(self.attributes_groupBox)
        self.texture_checkBox.setChecked(True)
        self.texture_checkBox.setObjectName(_fromUtf8("texture_checkBox"))
        self.gridLayout_3.addWidget(self.texture_checkBox, 0, 1, 1, 1)
        self.multiuv_checkBox = QtWidgets.QCheckBox(self.attributes_groupBox)
        self.multiuv_checkBox.setChecked(True)
        self.multiuv_checkBox.setObjectName(_fromUtf8("multiuv_checkBox"))
        self.gridLayout_3.addWidget(self.multiuv_checkBox, 0, 2, 1, 1)
        self.materialSet_checkBox = QtWidgets.QCheckBox(self.attributes_groupBox)
        self.materialSet_checkBox.setObjectName(_fromUtf8("materialSet_checkBox"))
        self.gridLayout_3.addWidget(self.materialSet_checkBox, 0, 3, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.geoattr_pushButton = QtWidgets.QPushButton(self.attributes_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geoattr_pushButton.sizePolicy().hasHeightForWidth())
        self.geoattr_pushButton.setSizePolicy(sizePolicy)
        self.geoattr_pushButton.setObjectName(_fromUtf8("geoattr_pushButton"))
        self.horizontalLayout_6.addWidget(self.geoattr_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.frame_3 = QtWidgets.QFrame(self.attributes_groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.attributes_groupBox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.objects_frame = QtWidgets.QFrame(self.splitter)
        self.objects_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objects_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objects_frame.setObjectName(_fromUtf8("objects_frame"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.objects_frame)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.processLog_listWidget = QtWidgets.QListWidget(self.objects_frame)
        self.processLog_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.processLog_listWidget.setObjectName(_fromUtf8("processLog_listWidget"))
        self.gridLayout_4.addWidget(self.processLog_listWidget, 0, 0, 1, 1)
        self.material_frame = QtWidgets.QFrame(self.splitter)
        self.material_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.material_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.material_frame.setObjectName(_fromUtf8("material_frame"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.material_frame)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.messageLog_listWidget = QtWidgets.QListWidget(self.material_frame)
        self.messageLog_listWidget.setAlternatingRowColors(True)
        self.messageLog_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.messageLog_listWidget.setObjectName(_fromUtf8("messageLog_listWidget"))
        self.gridLayout_5.addWidget(self.messageLog_listWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkupAll_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkupAll_pushButton.setObjectName(_fromUtf8("checkupAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.checkupAll_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        # self.export_pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.export_pushButton.setObjectName(_fromUtf8("export_pushButton"))
        # self.horizontalLayout_3.addWidget(self.export_pushButton)
        # self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        # self.horizontalLayout_3.addWidget(self.close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        assetCheckup_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(assetCheckup_window)
        QtCore.QMetaObject.connectSlotsByName(assetCheckup_window)

    def retranslateUi(self, assetCheckup_window):
        assetCheckup_window.setWindowTitle(_translate("assetCheckup_window", "MainWindow", None))
        self.label_3.setText(_translate("assetCheckup_window", "Base Path :", None))
        self.fileDialog_pushButton.setText(_translate("assetCheckup_window", "...", None))
        self.groupBox_2.setTitle(_translate("assetCheckup_window", "Geometry CheckUp", None))
        self.holed_checkBox.setText(_translate("assetCheckup_window", "Holed", None))
        self.concave_checkBox.setText(_translate("assetCheckup_window", "Concave", None))
        self.nside_checkBox.setText(_translate("assetCheckup_window", "more than 4 Sides", None))
        self.threeside_checkBox.setText(_translate("assetCheckup_window", "3 Sides", None))
        self.nonmanifold_checkBox.setText(_translate("assetCheckup_window", "Non-Manifold", None))
        self.twoedgevtx_checkBox.setText(_translate("assetCheckup_window", "2Edge Vertex", None))
        self.zeroedge_checkBox.setText(_translate("assetCheckup_window", "Zero length Edge", None))
        self.multiuvset_checkBox.setText(_translate("assetCheckup_window", "multi UVSet", None))
        self.outsideuv_checkBox.setText(_translate("assetCheckup_window", "Outside UV", None))
        self.zerouv_checkBox.setText(_translate("assetCheckup_window", "Zero UV", None))
        self.zeroface_checkBox.setText(_translate("assetCheckup_window", "Zero Area Face", None))
        self.twisted_checkBox.setText(_translate("assetCheckup_window", "Twisted", None))
        self.lamina_checkBox.setText(_translate("assetCheckup_window", "Lamina", None))
        self.overlapface_checkBox.setText(_translate("assetCheckup_window", "Overlap Face", None))
        self.overlapmesh_checkBox.setText(_translate("assetCheckup_window", "Overlap Mesh", None))
        self.geocheckup_pushButton.setText(_translate("assetCheckup_window", "CheckUp", None))
        self.groupBox.setTitle(_translate("assetCheckup_window", "Geometry SetUp", None))
        self.zeropivot_checkBox.setText(_translate("assetCheckup_window", "Zero Pivot", None))
        self.zeromovevertex_checkBox.setText(_translate("assetCheckup_window", "Zero Move Vertex", None))
        self.freezetransform_checkBox.setText(_translate("assetCheckup_window", "Freeze Transform", None))
        self.deletehistory_checkBox.setText(_translate("assetCheckup_window", "Delete History", None))
        self.normaifoldgeometry_checkBox.setText(_translate("assetCheckup_window", "Nonmanifold geometry", None))
        self.mergevertex_checkBox.setText(_translate("assetCheckup_window", "Merge Vertex", None))
        self.geosetup_pushButton.setText(_translate("assetCheckup_window", "CheckUp", None))
        self.attributes_groupBox.setTitle(_translate("assetCheckup_window", "Geometry Attributes", None))
        self.objectname_checkBox.setText(_translate("assetCheckup_window", "objectName", None))
        self.texture_checkBox.setText(_translate("assetCheckup_window", "Display Layer", None))
        self.multiuv_checkBox.setText(_translate("assetCheckup_window", "Multi UV", None))
        self.materialSet_checkBox.setText(_translate("assetCheckup_window", "MaterialSet", None))
        self.geoattr_pushButton.setText(_translate("assetCheckup_window", "CheckUp", None))
        self.checkupAll_pushButton.setText(_translate("assetCheckup_window", "Checkup All", None))
        # self.export_pushButton.setText(_translate("assetCheckup_window", "Export", None))
        # self.close_pushButton.setText(_translate("assetCheckup_window", "Close", None))
        self.label_2.setText(_translate("assetCheckup_window", "Asset Pipe-line scripts for Dexter", None))