# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxAttributeEditUI.ui'
#
# Created: Tue Jan 28 17:36:13 2020
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore
from PySide2 import QtWidgets as QtGui
import PySide2 as Qt

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(394, 532)
        self.gridLayoutWidget_2 = QtGui.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 511))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 6, 0, 1, 1)
        self.lineEdit_txLayerName = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_txLayerName.setObjectName(_fromUtf8("lineEdit_txLayerName"))
        self.gridLayout_4.addWidget(self.lineEdit_txLayerName, 3, 0, 1, 1)
        self.pushButton_txmultiUV = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_txmultiUV.setObjectName(_fromUtf8("pushButton_txmultiUV"))
        self.gridLayout_4.addWidget(self.pushButton_txmultiUV, 5, 1, 1, 1)

        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_txBasePath = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_txBasePath.setObjectName(_fromUtf8("pushButton_txBasePath"))
        self.horizontalLayout_2.addWidget(self.pushButton_txBasePath)
        self.pushButton_GRP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_GRP.setObjectName(_fromUtf8("pushButton_GRP"))
        self.horizontalLayout_2.addWidget(self.pushButton_GRP)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        # self.gridLayout_2.addLayout(self.gridLayout_4, 7, 0, 1, 1)

        # self.pushButton_txBasePath = QtGui.QPushButton(self.gridLayoutWidget_2)
        # self.pushButton_txBasePath.setObjectName(_fromUtf8("pushButton_txBasePath"))
        # self.gridLayout_4.addWidget(self.pushButton_txBasePath, 1, 1, 1, 1)


        self.pushButton_txLayerName = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_txLayerName.setObjectName(_fromUtf8("pushButton_txLayerName"))
        self.gridLayout_4.addWidget(self.pushButton_txLayerName, 3, 1, 1, 1)
        self.lineEdit_txmultiUV = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_txmultiUV.setObjectName(_fromUtf8("lineEdit_txmultiUV"))
        self.gridLayout_4.addWidget(self.lineEdit_txmultiUV, 5, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox, 7, 0, 1, 1)
        self.lineEdit_txBasePath = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_txBasePath.setObjectName(_fromUtf8("lineEdit_txBasePath"))
        self.gridLayout_4.addWidget(self.lineEdit_txBasePath, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.pushButton_subdivision = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_subdivision.setObjectName(_fromUtf8("pushButton_subdivision"))
        self.gridLayout_4.addWidget(self.pushButton_subdivision, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))

        self.horizontalLayout.addWidget(self.label_12)
        self.lineEdit_MaterialSet = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_MaterialSet.setObjectName(_fromUtf8("lineEdit_MaterialSet"))
        self.horizontalLayout.addWidget(self.lineEdit_MaterialSet)
        self.pushButton_M = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_M.setObjectName(_fromUtf8("pushButton_M"))
        self.horizontalLayout.addWidget(self.pushButton_M)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)


        #self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_gold = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_gold.setObjectName(_fromUtf8("pushButton_gold"))
        self.gridLayout.addWidget(self.pushButton_gold, 0, 3, 1, 1)

        self.pushButton_layer = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_layer.setObjectName(_fromUtf8("pushButton_layer"))
        self.gridLayout.addWidget(self.pushButton_layer, 3, 4, 1, 1)

        self.pushButton_layerB = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_layerB.setObjectName(_fromUtf8("pushButton_layerB"))
        self.gridLayout.addWidget(self.pushButton_layerB, 4, 4, 1, 1)

        self.pushButton_ice = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ice.setObjectName(_fromUtf8("pushButton_ice"))
        self.gridLayout.addWidget(self.pushButton_ice, 4, 2, 1, 1)
        self.pushButton_paint = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_paint.setObjectName(_fromUtf8("pushButton_paint"))
        self.gridLayout.addWidget(self.pushButton_paint, 1, 4, 1, 1)
        self.pushButton_bronze = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_bronze.setObjectName(_fromUtf8("pushButton_bronze"))
        self.gridLayout.addWidget(self.pushButton_bronze, 0, 2, 1, 1)
        self.pushButton_rubber = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_rubber.setObjectName(_fromUtf8("pushButton_rubber"))
        self.gridLayout.addWidget(self.pushButton_rubber, 1, 3, 1, 1)
        self.pushButton_plastic = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_plastic.setObjectName(_fromUtf8("pushButton_plastic"))
        self.gridLayout.addWidget(self.pushButton_plastic, 1, 0, 1, 1)
        self.pushButton_leather = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_leather.setObjectName(_fromUtf8("pushButton_leather"))
        self.gridLayout.addWidget(self.pushButton_leather, 2, 4, 1, 1)
        self.pushButton_snow = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_snow.setObjectName(_fromUtf8("pushButton_snow"))
        self.gridLayout.addWidget(self.pushButton_snow, 4, 1, 1, 1)
        self.pushButton_rock = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_rock.setObjectName(_fromUtf8("pushButton_rock"))
        self.gridLayout.addWidget(self.pushButton_rock, 3, 2, 1, 1)
        self.pushButton_mineral = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_mineral.setObjectName(_fromUtf8("pushButton_mineral"))
        self.gridLayout.addWidget(self.pushButton_mineral, 3, 3, 1, 1)
        self.pushButton_wood = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_wood.setObjectName(_fromUtf8("pushButton_wood"))
        self.gridLayout.addWidget(self.pushButton_wood, 3, 1, 1, 1)
        self.pushButton_eye = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_eye.setObjectName(_fromUtf8("pushButton_eye"))
        self.gridLayout.addWidget(self.pushButton_eye, 2, 1, 1, 1)
        self.pushButton_ocean = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ocean.setObjectName(_fromUtf8("pushButton_ocean"))
        self.gridLayout.addWidget(self.pushButton_ocean, 4, 0, 1, 1)
        self.pushButton_skin = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_skin.setObjectName(_fromUtf8("pushButton_skin"))
        self.gridLayout.addWidget(self.pushButton_skin, 2, 0, 1, 1)
        self.pushButton_chrome = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_chrome.setObjectName(_fromUtf8("pushButton_chrome"))
        self.gridLayout.addWidget(self.pushButton_chrome, 0, 1, 1, 1)
        self.pushButton_silver = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_silver.setObjectName(_fromUtf8("pushButton_silver"))
        self.gridLayout.addWidget(self.pushButton_silver, 0, 4, 1, 1)
        self.pushButton_fur = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_fur.setObjectName(_fromUtf8("pushButton_fur"))
        self.gridLayout.addWidget(self.pushButton_fur, 2, 3, 1, 1)
        self.pushButton_glass = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_glass.setObjectName(_fromUtf8("pushButton_glass"))
        self.gridLayout.addWidget(self.pushButton_glass, 1, 1, 1, 1)
        self.pushButton_fabric = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_fabric.setObjectName(_fromUtf8("pushButton_fabric"))
        self.gridLayout.addWidget(self.pushButton_fabric, 1, 2, 1, 1)
        self.pushButton_metal = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_metal.setObjectName(_fromUtf8("pushButton_metal"))
        self.gridLayout.addWidget(self.pushButton_metal, 0, 0, 1, 1)
        self.pushButton_leaf = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_leaf.setObjectName(_fromUtf8("pushButton_leaf"))
        self.gridLayout.addWidget(self.pushButton_leaf, 3, 0, 1, 1)
        self.pushButton_light = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_light.setObjectName(_fromUtf8("pushButton_light"))
        self.gridLayout.addWidget(self.pushButton_light, 4, 3, 1, 1)
        self.pushButton_feather = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_feather.setObjectName(_fromUtf8("pushButton_feather"))
        self.gridLayout.addWidget(self.pushButton_feather, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_set = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_set.setObjectName(_fromUtf8("pushButton_set"))
        self.gridLayout_3.addWidget(self.pushButton_set, 1, 3, 1, 1)
        self.lineEdit_valueY = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_valueY.setObjectName(_fromUtf8("lineEdit_valueY"))
        self.gridLayout_3.addWidget(self.lineEdit_valueY, 1, 2, 1, 1)
        self.lineEdit_valueX = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_valueX.setObjectName(_fromUtf8("lineEdit_valueX"))
        self.gridLayout_3.addWidget(self.lineEdit_valueX, 1, 1, 1, 1)
        self.comboBox_scaleX = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_scaleX.setObjectName(_fromUtf8("comboBox_scaleX"))
        self.comboBox_scaleX.addItem(_fromUtf8(""))
        self.comboBox_scaleX.addItem(_fromUtf8(""))
        self.comboBox_scaleX.addItem(_fromUtf8(""))
        self.comboBox_scaleX.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_scaleX, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 7, 0, 1, 1)
        self.pushButton_assign = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_assign.setObjectName(_fromUtf8("pushButton_assign"))
        self.gridLayout_2.addWidget(self.pushButton_assign, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = Qt.QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "USD Attibute Edit Tool", None))
        self.pushButton_M.setText(_translate("Form", "M", None))
        self.label_15.setText(_translate("Form", "txLayerName ( 0: Delete )", None))
        self.label_17.setText(_translate("Form", "subdivision", None))
        self.pushButton_txmultiUV.setText(_translate("Form", "txmultiUV", None))
        self.pushButton_txBasePath.setText(_translate("Form", "txBasePath", None))
        self.pushButton_GRP.setText(_translate("Form", "GRP", None))
        self.pushButton_txLayerName.setText(_translate("Form", "txLayerName", None))
        self.comboBox.setItemText(0, _translate("Form", "none", None))
        self.comboBox.setItemText(1, _translate("Form", "catmullClark", None))
        self.comboBox.setItemText(2, _translate("Form", "loop", None))
        self.comboBox.setItemText(3, _translate("Form", "delete", None))
        self.label_14.setText(_translate("Form", "txBasePath  ( 0: Delete )", None))
        self.label_16.setText(_translate("Form", "txmultiUV ( 1:On, 0: Delete )", None))
        self.pushButton_subdivision.setText(_translate("Form", "subdivision", None))
        self.label_12.setText(_translate("Form", "MaterialSet                                                                   ", None))
        self.pushButton_gold.setText(_translate("Form", "gold", None))
        self.pushButton_layer.setText(_translate("Form", "layer", None))
        self.pushButton_layerB.setText(_translate("Form", "layerB", None))
        self.pushButton_ice.setText(_translate("Form", "ice", None))
        self.pushButton_paint.setText(_translate("Form", "paint", None))
        self.pushButton_bronze.setText(_translate("Form", "bronze", None))
        self.pushButton_rubber.setText(_translate("Form", "rubber", None))
        self.pushButton_plastic.setText(_translate("Form", "plastic", None))
        self.pushButton_leather.setText(_translate("Form", "leather", None))
        self.pushButton_snow.setText(_translate("Form", "snow", None))
        self.pushButton_rock.setText(_translate("Form", "rock", None))
        self.pushButton_mineral.setText(_translate("Form", "mineral", None))
        self.pushButton_wood.setText(_translate("Form", "wood", None))
        self.pushButton_eye.setText(_translate("Form", "eye", None))
        self.pushButton_ocean.setText(_translate("Form", "ocean", None))
        self.pushButton_skin.setText(_translate("Form", "skin", None))
        self.pushButton_chrome.setText(_translate("Form", "chrome", None))
        self.pushButton_silver.setText(_translate("Form", "silver", None))
        self.pushButton_fur.setText(_translate("Form", "fur", None))
        self.pushButton_glass.setText(_translate("Form", "glass", None))
        self.pushButton_fabric.setText(_translate("Form", "fabric", None))
        self.pushButton_metal.setText(_translate("Form", "metal", None))
        self.pushButton_leaf.setText(_translate("Form", "leaf", None))
        self.pushButton_light.setText(_translate("Form", "light", None))
        self.pushButton_feather.setText(_translate("Form", "feather", None))
        self.pushButton_set.setText(_translate("Form", "set", None))
        self.comboBox_scaleX.setItemText(0, _translate("Form", "scaleST", None))
        self.comboBox_scaleX.setItemText(1, _translate("Form", "scaleST1", None))
        self.comboBox_scaleX.setItemText(2, _translate("Form", "scaleST2", None))
        self.comboBox_scaleX.setItemText(3, _translate("Form", "scaleST3", None))
        self.label_18.setText(_translate("Form", "Texture Manifold ( 0: Delete )", None))
        self.pushButton_assign.setText(_translate("Form", "Outliner Sets", None))
        self.label_13.setText(_translate("Form", "Create Sets By MaterialSet", None))
