# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created: Wed Jan  9 00:19:59 2019
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore
from PySide2 import QtWidgets
from PySide2 import QtGui

import os
currentDir = os.path.dirname(__file__)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(447, 385)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.testCommandEdit = QtWidgets.QLineEdit(Form)
        self.testCommandEdit.setObjectName(_fromUtf8("testCommandEdit"))
        self.gridLayout_3.addWidget(self.testCommandEdit, 7, 0, 1, 1)
        self.testSendBtn = QtWidgets.QPushButton(Form)
        self.testSendBtn.setObjectName(_fromUtf8("testSendBtn"))
        self.gridLayout_3.addWidget(self.testSendBtn, 7, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtWidgets.QLabel(Form)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/company_logoB.png" % currentDir)))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/hsMaya.png" % currentDir)))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/A57-Arrow-Yellow-Left.png" % currentDir)))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/katana.png" % currentDir)))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setMaximumSize(QtCore.QSize(30, 30))
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setPixmap(QtGui.QPixmap(_fromUtf8("%s/resources/Circle04-DarkRed.png" % currentDir)))
        self.statusLabel.setScaledContents(True)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.horizontalLayout_4.addWidget(self.statusLabel)
        self.connectBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.horizontalLayout_4.addWidget(self.connectBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(2, -1, 2, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dirPathEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dirPathEdit.setText(_fromUtf8(""))
        self.dirPathEdit.setObjectName(_fromUtf8("dirPathEdit"))
        self.horizontalLayout_2.addWidget(self.dirPathEdit)
        self.clearCacheBtn = QtWidgets.QPushButton(self.groupBox)
        self.clearCacheBtn.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.clearCacheBtn.setFont(font)
        self.clearCacheBtn.setObjectName(_fromUtf8("clearCacheBtn"))
        self.horizontalLayout_2.addWidget(self.clearCacheBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.exportTempCacheBtn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.exportTempCacheBtn.setFont(font)
        self.exportTempCacheBtn.setObjectName(_fromUtf8("exportTempCacheBtn"))
        self.gridLayout.addWidget(self.exportTempCacheBtn, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 3, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 6, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(2, -1, 2, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.previewRenderBtn = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.previewRenderBtn.setFont(font)
        self.previewRenderBtn.setObjectName(_fromUtf8("previewRenderBtn"))
        self.horizontalLayout_3.addWidget(self.previewRenderBtn)
        self.liveRenderBtn = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.liveRenderBtn.setFont(font)
        self.liveRenderBtn.setObjectName(_fromUtf8("liveRenderBtn"))
        self.horizontalLayout_3.addWidget(self.liveRenderBtn)
        self.cancelRenderBtn = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cancelRenderBtn.setFont(font)
        self.cancelRenderBtn.setObjectName(_fromUtf8("cancelRenderBtn"))
        self.horizontalLayout_3.addWidget(self.cancelRenderBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 5, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.showDirEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.showDirEdit.setObjectName(_fromUtf8("showDirEdit"))
        self.horizontalLayout.addWidget(self.showDirEdit)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.testSendBtn.setText(_translate("Form", "&SEND", None))
        self.connectBtn.setText(_translate("Form", "Connect", None))
        self.groupBox.setTitle(_translate("Form", "Temp Cache", None))
        self.label_2.setText(_translate("Form", "Temp Path", None))
        self.clearCacheBtn.setText(_translate("Form", "Del", None))
        self.exportTempCacheBtn.setText(_translate("Form", "Export Temp Cache (USD)", None))
        self.groupBox_2.setTitle(_translate("Form", "Render Command", None))
        self.previewRenderBtn.setText(_translate("Form", "Preview Render", None))
        self.liveRenderBtn.setText(_translate("Form", "LiveRender", None))
        self.cancelRenderBtn.setText(_translate("Form", "Cancel Render", None))
        self.groupBox_3.setTitle(_translate("Form", "Show Dir", None))

