# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plcAsset.ui'
#
# Created: Wed Jun 14 15:25:24 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtWidgets
from PySide2 import QtGui
from PySide2 import QtCore
import plcAsset2

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_plcAsset(object):
    def setupUi(self, plcAsset):
        plcAsset.setObjectName(_fromUtf8("plcAsset"))
        plcAsset.resize(353, 570)
        plcAsset.setMinimumSize(QtCore.QSize(353, 419))
        plcAsset.setMaximumSize(QtCore.QSize(353, 800))
        plcAsset.setAcceptDrops(True)
        self.targetGeo = QtWidgets.QLineEdit(plcAsset)
        self.targetGeo.setGeometry(QtCore.QRect(130, 10, 102, 24))
        self.targetGeo.setMinimumSize(QtCore.QSize(54, 24))
        self.targetGeo.setMaximumSize(QtCore.QSize(150, 24))
        self.targetGeo.setAcceptDrops(True)
        self.targetGeo.setObjectName(_fromUtf8("targetGeo"))
        self.selGeoBtn = QtWidgets.QPushButton(plcAsset)
        self.selGeoBtn.setGeometry(QtCore.QRect(272, 11, 72, 21))
        self.selGeoBtn.setObjectName(_fromUtf8("selGeoBtn"))
        self.label_6 = QtWidgets.QLabel(plcAsset)
        self.label_6.setGeometry(QtCore.QRect(32, 11, 105, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.numOri = QtWidgets.QSpinBox(plcAsset)
        self.numOri.setGeometry(QtCore.QRect(279, 159, 65, 24))
        self.numOri.setAlignment(QtCore.Qt.AlignCenter)
        self.numOri.setObjectName(_fromUtf8("numOri"))
        self.crBtn = QtWidgets.QPushButton(plcAsset)
        self.crBtn.setGeometry(QtCore.QRect(272, 49, 73, 21))
        self.crBtn.setObjectName(_fromUtf8("crBtn"))
        self.label_4 = QtWidgets.QLabel(plcAsset)
        self.label_4.setGeometry(QtCore.QRect(34, 49, 103, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.numCh = QtWidgets.QLineEdit(plcAsset)
        self.numCh.setGeometry(QtCore.QRect(130, 48, 54, 24))
        self.numCh.setMinimumSize(QtCore.QSize(54, 24))
        self.numCh.setMaximumSize(QtCore.QSize(150, 24))
        self.numCh.setAcceptDrops(False)
        self.numCh.setAlignment(QtCore.Qt.AlignCenter)
        self.numCh.setObjectName(_fromUtf8("numCh"))
        self.Rot = QtWidgets.QLabel(plcAsset)
        self.Rot.setGeometry(QtCore.QRect(30, 159, 112, 21))
        self.Rot.setObjectName(_fromUtf8("Rot"))
        self.slOri = QtWidgets.QSlider(plcAsset)
        self.slOri.setGeometry(QtCore.QRect(126, 161, 141, 20))
        self.slOri.setOrientation(QtCore.Qt.Horizontal)
        self.slOri.setObjectName(_fromUtf8("slOri"))
        self.geoConBtn = QtWidgets.QPushButton(plcAsset)
        self.geoConBtn.setGeometry(QtCore.QRect(133, 121, 123, 21))
        self.geoConBtn.setObjectName(_fromUtf8("geoConBtn"))
        self.aimTarget = QtWidgets.QLineEdit(plcAsset)
        self.aimTarget.setGeometry(QtCore.QRect(130, 195, 140, 24))
        self.aimTarget.setMinimumSize(QtCore.QSize(54, 24))
        self.aimTarget.setMaximumSize(QtCore.QSize(150, 24))
        self.aimTarget.setAcceptDrops(False)
        self.aimTarget.setObjectName(_fromUtf8("aimTarget"))
        self.aimBtn = QtWidgets.QPushButton(plcAsset)
        self.aimBtn.setGeometry(QtCore.QRect(280, 195, 64, 22))
        self.aimBtn.setObjectName(_fromUtf8("aimBtn"))
        self.label_7 = QtWidgets.QLabel(plcAsset)
        self.label_7.setGeometry(QtCore.QRect(56, 195, 84, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.loadBtn = QtWidgets.QPushButton(plcAsset)
        self.loadBtn.setGeometry(QtCore.QRect(8, 487, 335, 43))
        self.loadBtn.setObjectName(_fromUtf8("loadBtn"))
        self.impBtn = QtWidgets.QPushButton(plcAsset)
        self.impBtn.setGeometry(QtCore.QRect(280, 370, 63, 32))
        self.impBtn.setObjectName(_fromUtf8("impBtn"))
        self.delBtn = QtWidgets.QPushButton(plcAsset)
        self.delBtn.setGeometry(QtCore.QRect(280, 409, 63, 32))
        self.delBtn.setObjectName(_fromUtf8("delBtn"))
        self.locScaleLabel = QtWidgets.QLabel(plcAsset)
        self.locScaleLabel.setGeometry(QtCore.QRect(78, 81, 53, 21))
        self.locScaleLabel.setObjectName(_fromUtf8("locScaleLabel"))
        self.scsl = QtWidgets.QSlider(plcAsset)
        self.scsl.setGeometry(QtCore.QRect(125, 83, 139, 20))
        self.scsl.setOrientation(QtCore.Qt.Horizontal)
        self.scsl.setObjectName(_fromUtf8("scsl"))
        self.scnum = QtWidgets.QSpinBox(plcAsset)
        self.scnum.setGeometry(QtCore.QRect(273, 80, 73, 24))
        self.scnum.setAlignment(QtCore.Qt.AlignCenter)
        self.scnum.setObjectName(_fromUtf8("scnum"))
        self.getrBtn = QtWidgets.QPushButton(plcAsset)
        self.getrBtn.setGeometry(QtCore.QRect(10, 121, 119, 21))
        self.getrBtn.setObjectName(_fromUtf8("getrBtn"))
        self.scattBtn = QtWidgets.QPushButton(plcAsset)
        self.scattBtn.setGeometry(QtCore.QRect(261, 121, 84, 21))
        self.scattBtn.setObjectName(_fromUtf8("scattBtn"))
        self.dmBtn = QtWidgets.QPushButton(plcAsset)
        self.dmBtn.setGeometry(QtCore.QRect(280, 230, 64, 22))
        self.dmBtn.setObjectName(_fromUtf8("dmBtn"))
        self.label_8 = QtWidgets.QLabel(plcAsset)
        self.label_8.setGeometry(QtCore.QRect(120, 230, 59, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dummy = QtWidgets.QLineEdit(plcAsset)
        self.dummy.setGeometry(QtCore.QRect(168, 230, 102, 24))
        self.dummy.setMinimumSize(QtCore.QSize(54, 24))
        self.dummy.setMaximumSize(QtCore.QSize(150, 24))
        self.dummy.setAcceptDrops(False)
        self.dummy.setObjectName(_fromUtf8("dummy"))
        self.chkfc = QtWidgets.QCheckBox(plcAsset)
        self.chkfc.setGeometry(QtCore.QRect(13, 228, 88, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.chkfc.setFont(font)
        self.chkfc.setObjectName(_fromUtf8("chkfc"))
        self.import_Label = QtWidgets.QLabel(plcAsset)
        self.import_Label.setGeometry(QtCore.QRect(18, 451, 98, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.import_Label.setFont(font)
        self.import_Label.setObjectName(_fromUtf8("import_Label"))
        self.CacheLb = QtWidgets.QLabel(plcAsset)
        self.CacheLb.setGeometry(QtCore.QRect(40, 329, 111, 21))
        self.CacheLb.setObjectName(_fromUtf8("CacheLb"))
        self.layoutWidget = QtWidgets.QWidget(plcAsset)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 329, 149, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rdDir = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rdDir.setFont(font)
        self.rdDir.setChecked(True)
        self.rdDir.setObjectName(_fromUtf8("rdDir"))
        self.horizontalLayout.addWidget(self.rdDir)
        self.rdFile = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rdFile.setFont(font)
        self.rdFile.setObjectName(_fromUtf8("rdFile"))
        self.horizontalLayout.addWidget(self.rdFile)
        self.layoutWidget1 = QtWidgets.QWidget(plcAsset)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 450, 237, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rdRan = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rdRan.setMaximumSize(QtCore.QSize(72, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rdRan.setFont(font)
        self.rdRan.setChecked(True)
        self.rdRan.setObjectName(_fromUtf8("rdRan"))
        self.horizontalLayout_2.addWidget(self.rdRan)
        self.rdSel = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rdSel.setMaximumSize(QtCore.QSize(90, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rdSel.setFont(font)
        self.rdSel.setObjectName(_fromUtf8("rdSel"))
        self.horizontalLayout_2.addWidget(self.rdSel)
        self.rdCus = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rdCus.setMaximumSize(QtCore.QSize(90, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rdCus.setFont(font)
        self.rdCus.setObjectName(_fromUtf8("rdCus"))
        self.horizontalLayout_2.addWidget(self.rdCus)
        self.layoutWidget2 = QtWidgets.QWidget(plcAsset)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 260, 326, 57))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setMaximumSize(QtCore.QSize(90, 24))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.scaleMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.scaleMin.setMaximumSize(QtCore.QSize(40, 24))
        self.scaleMin.setAcceptDrops(False)
        self.scaleMin.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleMin.setObjectName(_fromUtf8("scaleMin"))
        self.horizontalLayout_3.addWidget(self.scaleMin)
        self.spdText_Label = QtWidgets.QLabel(self.layoutWidget2)
        self.spdText_Label.setMaximumSize(QtCore.QSize(10, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.spdText_Label.setFont(font)
        self.spdText_Label.setObjectName(_fromUtf8("spdText_Label"))
        self.horizontalLayout_3.addWidget(self.spdText_Label)
        self.scaleMax = QtWidgets.QLineEdit(self.layoutWidget2)
        self.scaleMax.setMaximumSize(QtCore.QSize(40, 24))
        self.scaleMax.setAcceptDrops(False)
        self.scaleMax.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleMax.setObjectName(_fromUtf8("scaleMax"))
        self.horizontalLayout_3.addWidget(self.scaleMax)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setMaximumSize(QtCore.QSize(110, 24))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.offMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.offMin.setMaximumSize(QtCore.QSize(40, 24))
        self.offMin.setAcceptDrops(False)
        self.offMin.setAlignment(QtCore.Qt.AlignCenter)
        self.offMin.setObjectName(_fromUtf8("offMin"))
        self.horizontalLayout_4.addWidget(self.offMin)
        self.offText_Label = QtWidgets.QLabel(self.layoutWidget2)
        self.offText_Label.setMaximumSize(QtCore.QSize(10, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.offText_Label.setFont(font)
        self.offText_Label.setObjectName(_fromUtf8("offText_Label"))
        self.horizontalLayout_4.addWidget(self.offText_Label)
        self.offMax = QtWidgets.QLineEdit(self.layoutWidget2)
        self.offMax.setMaximumSize(QtCore.QSize(40, 24))
        self.offMax.setAcceptDrops(False)
        self.offMax.setAlignment(QtCore.Qt.AlignCenter)
        self.offMax.setObjectName(_fromUtf8("offMax"))
        self.horizontalLayout_4.addWidget(self.offMax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Scale_Label = QtWidgets.QLabel(self.layoutWidget2)
        self.Scale_Label.setMaximumSize(QtCore.QSize(110, 24))
        self.Scale_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Scale_Label.setObjectName(_fromUtf8("Scale_Label"))
        self.verticalLayout_3.addWidget(self.Scale_Label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sclMin = QtWidgets.QLineEdit(self.layoutWidget2)
        self.sclMin.setMaximumSize(QtCore.QSize(40, 24))
        self.sclMin.setAcceptDrops(False)
        self.sclMin.setAlignment(QtCore.Qt.AlignCenter)
        self.sclMin.setObjectName(_fromUtf8("sclMin"))
        self.horizontalLayout_5.addWidget(self.sclMin)
        self.sclText_Label = QtWidgets.QLabel(self.layoutWidget2)
        self.sclText_Label.setMaximumSize(QtCore.QSize(10, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sclText_Label.setFont(font)
        self.sclText_Label.setObjectName(_fromUtf8("sclText_Label"))
        self.horizontalLayout_5.addWidget(self.sclText_Label)
        self.sclMax = QtWidgets.QLineEdit(self.layoutWidget2)
        self.sclMax.setMaximumSize(QtCore.QSize(40, 24))
        self.sclMax.setAcceptDrops(False)
        self.sclMax.setAlignment(QtCore.Qt.AlignCenter)
        self.sclMax.setObjectName(_fromUtf8("sclMax"))
        self.horizontalLayout_5.addWidget(self.sclMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.listWidget = plcAsset2.DragDropTest(plcAsset)
        self.listWidget.setGeometry(QtCore.QRect(10, 359, 264, 83))
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.repBtn = QtWidgets.QPushButton(plcAsset)
        self.repBtn.setGeometry(QtCore.QRect(8, 536, 335, 26))
        self.repBtn.setObjectName(_fromUtf8("repBtn"))

        self.retranslateUi(plcAsset)
        QtCore.QObject.connect(self.slOri, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.numOri.setValue)
        QtCore.QObject.connect(self.numOri, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slOri.setValue)
        QtCore.QObject.connect(self.scnum, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scsl.setValue)
        QtCore.QObject.connect(self.scsl, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.scnum.setValue)
        QtCore.QMetaObject.connectSlotsByName(plcAsset)

    def retranslateUi(self, plcAsset):
        plcAsset.setWindowTitle(_translate("plcAsset", "Asset Placement", None))
        self.selGeoBtn.setText(_translate("plcAsset", "Select", None))
        self.label_6.setText(_translate("plcAsset", "Target Surface :", None))
        self.crBtn.setText(_translate("plcAsset", "Create", None))
        self.label_4.setText(_translate("plcAsset", "Num of Assets :", None))
        self.Rot.setText(_translate("plcAsset", "Rotate_Random :", None))
        self.geoConBtn.setText(_translate("plcAsset", "Geo-Constrain On", None))
        self.aimBtn.setText(_translate("plcAsset", "Select", None))
        self.label_7.setText(_translate("plcAsset", "Target Aim :", None))
        self.loadBtn.setText(_translate("plcAsset", "Convert", None))
        self.impBtn.setText(_translate("plcAsset", "Import", None))
        self.delBtn.setText(_translate("plcAsset", "Delete", None))
        self.locScaleLabel.setText(_translate("plcAsset", "Scale :", None))
        self.getrBtn.setText(_translate("plcAsset", "Range Plane On", None))
        self.scattBtn.setText(_translate("plcAsset", "Scattering", None))
        self.dmBtn.setText(_translate("plcAsset", "Select", None))
        self.label_8.setText(_translate("plcAsset", "Dummy :", None))
        self.chkfc.setText(_translate("plcAsset", "From cache", None))
        self.import_Label.setText(_translate("plcAsset", "Cache Convert :", None))
        self.CacheLb.setText(_translate("plcAsset", "Alembic Type :", None))
        self.rdDir.setText(_translate("plcAsset", "Directory", None))
        self.rdFile.setText(_translate("plcAsset", "File", None))
        self.rdRan.setText(_translate("plcAsset", "Auto", None))
        self.rdSel.setText(_translate("plcAsset", "Manual", None))
        self.rdCus.setText(_translate("plcAsset", "Custom", None))
        self.label.setText(_translate("plcAsset", ":: Speed ::", None))
        self.spdText_Label.setText(_translate("plcAsset", "-", None))
        self.label_5.setText(_translate("plcAsset", ":: Offset ::", None))
        self.offText_Label.setText(_translate("plcAsset", "-", None))
        self.Scale_Label.setText(_translate("plcAsset", ":: Scale ::", None))
        self.sclText_Label.setText(_translate("plcAsset", "-", None))
        self.repBtn.setText(_translate("plcAsset", "Replace Caches", None))

