# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/DXEditorialUI.ui',
# licensing of 'Resources/DXEditorialUI.ui' applies.
#
# Created: Wed Jan 13 12:40:08 2021
#      by: pyside2-uic  running on PySide2 5.12.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1166, 703)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.xmlEdit = QtWidgets.QLineEdit(Form)
        self.xmlEdit.setObjectName("xmlEdit")
        self.horizontalLayout.addWidget(self.xmlEdit)
        self.xmlBrowseBtn = QtWidgets.QPushButton(Form)
        self.xmlBrowseBtn.setObjectName("xmlBrowseBtn")
        self.horizontalLayout.addWidget(self.xmlBrowseBtn)
        self.xmlOpenDirBtn = QtWidgets.QPushButton(Form)
        self.xmlOpenDirBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.xmlOpenDirBtn.setText("")
        self.xmlOpenDirBtn.setObjectName("xmlOpenDirBtn")
        self.horizontalLayout.addWidget(self.xmlOpenDirBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.scanEdit = QtWidgets.QLineEdit(Form)
        self.scanEdit.setObjectName("scanEdit")
        self.horizontalLayout_2.addWidget(self.scanEdit)
        self.scanBrowseBtn = QtWidgets.QPushButton(Form)
        self.scanBrowseBtn.setObjectName("scanBrowseBtn")
        self.horizontalLayout_2.addWidget(self.scanBrowseBtn)
        self.scanOpenDirBtn = QtWidgets.QPushButton(Form)
        self.scanOpenDirBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.scanOpenDirBtn.setText("")
        self.scanOpenDirBtn.setObjectName("scanOpenDirBtn")
        self.horizontalLayout_2.addWidget(self.scanOpenDirBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.exportExcelBtn = QtWidgets.QPushButton(Form)
        self.exportExcelBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.exportExcelBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.exportExcelBtn.setObjectName("exportExcelBtn")
        self.horizontalLayout_3.addWidget(self.exportExcelBtn)
        self.importExcelBtn = QtWidgets.QPushButton(Form)
        self.importExcelBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.importExcelBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.importExcelBtn.setObjectName("importExcelBtn")
        self.horizontalLayout_3.addWidget(self.importExcelBtn)
        self.rvPlayerBtn = QtWidgets.QPushButton(Form)
        self.rvPlayerBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.rvPlayerBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rvPlayerBtn.setObjectName("rvPlayerBtn")
        self.horizontalLayout_3.addWidget(self.rvPlayerBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.differenceCheckBox = QtWidgets.QCheckBox(Form)
        self.differenceCheckBox.setMinimumSize(QtCore.QSize(100, 0))
        self.differenceCheckBox.setObjectName("differenceCheckBox")
        self.horizontalLayout_4.addWidget(self.differenceCheckBox)
        self.hideShotCheckBox = QtWidgets.QCheckBox(Form)
        self.hideShotCheckBox.setMinimumSize(QtCore.QSize(100, 0))
        self.hideShotCheckBox.setObjectName("hideShotCheckBox")
        self.horizontalLayout_4.addWidget(self.hideShotCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lockCheckBox = QtWidgets.QCheckBox(Form)
        self.lockCheckBox.setMinimumSize(QtCore.QSize(30, 30))
        self.lockCheckBox.setText("")
        self.lockCheckBox.setObjectName("lockCheckBox")
        self.horizontalLayout_4.addWidget(self.lockCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.excelTable = QtWidgets.QTableWidget(Form)
        self.excelTable.setObjectName("excelTable")
        self.excelTable.setColumnCount(0)
        self.excelTable.setRowCount(0)
        self.verticalLayout.addWidget(self.excelTable)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.shotSettingBtn = QtWidgets.QPushButton(Form)
        self.shotSettingBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.shotSettingBtn.setObjectName("shotSettingBtn")
        self.horizontalLayout_5.addWidget(self.shotSettingBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.exportPlateMovBtn = QtWidgets.QPushButton(Form)
        self.exportPlateMovBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.exportPlateMovBtn.setObjectName("exportPlateMovBtn")
        self.horizontalLayout_5.addWidget(self.exportPlateMovBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_5.addWidget(self.saveBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "XML", None, -1))
        self.xmlBrowseBtn.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "SCAN", None, -1))
        self.scanBrowseBtn.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.exportExcelBtn.setText(QtWidgets.QApplication.translate("Form", "Export Excel", None, -1))
        self.importExcelBtn.setText(QtWidgets.QApplication.translate("Form", "Import Excel", None, -1))
        self.rvPlayerBtn.setText(QtWidgets.QApplication.translate("Form", "RV Player", None, -1))
        self.differenceCheckBox.setText(QtWidgets.QApplication.translate("Form", "Difference", None, -1))
        self.hideShotCheckBox.setText(QtWidgets.QApplication.translate("Form", "Hide Shot", None, -1))
        self.shotSettingBtn.setText(QtWidgets.QApplication.translate("Form", "Shot Setting", None, -1))
        self.exportPlateMovBtn.setText(QtWidgets.QApplication.translate("Form", "Export Plate and MOV", None, -1))
        self.saveBtn.setText(QtWidgets.QApplication.translate("Form", "Save", None, -1))

