# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/HIKDialog.ui'
#
# Created: Mon Feb  5 10:41:52 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from pymodule.Qt import QtWidgets as QtGui
from pymodule.Qt import QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(423, 305)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.aniRadioBtn = QtGui.QRadioButton(Form)
        self.aniRadioBtn.setChecked(True)
        self.aniRadioBtn.setObjectName(_fromUtf8("aniRadioBtn"))
        self.horizontalLayout_2.addWidget(self.aniRadioBtn)
        self.mcpRadioBtn = QtGui.QRadioButton(Form)
        self.mcpRadioBtn.setObjectName(_fromUtf8("mcpRadioBtn"))
        self.horizontalLayout_2.addWidget(self.mcpRadioBtn)
        self.crdRadioBtn = QtGui.QRadioButton(Form)
        self.crdRadioBtn.setObjectName(_fromUtf8("crdRadioBtn"))
        self.horizontalLayout_2.addWidget(self.crdRadioBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.animPathEdit = QtGui.QLineEdit(Form)
        self.animPathEdit.setReadOnly(True)
        self.animPathEdit.setObjectName(_fromUtf8("animPathEdit"))
        self.gridLayout.addWidget(self.animPathEdit, 4, 1, 1, 2)
        self.loadAnimFileBtn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadAnimFileBtn.sizePolicy().hasHeightForWidth())
        self.loadAnimFileBtn.setSizePolicy(sizePolicy)
        self.loadAnimFileBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.loadAnimFileBtn.setObjectName(_fromUtf8("loadAnimFileBtn"))
        self.gridLayout.addWidget(self.loadAnimFileBtn, 4, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.jsonPathEdit = QtGui.QLineEdit(Form)
        self.jsonPathEdit.setReadOnly(True)
        self.jsonPathEdit.setObjectName(_fromUtf8("jsonPathEdit"))
        self.gridLayout.addWidget(self.jsonPathEdit, 5, 1, 1, 2)
        self.loadJsonFileBtn = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadJsonFileBtn.sizePolicy().hasHeightForWidth())
        self.loadJsonFileBtn.setSizePolicy(sizePolicy)
        self.loadJsonFileBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.loadJsonFileBtn.setObjectName(_fromUtf8("loadJsonFileBtn"))
        self.gridLayout.addWidget(self.loadJsonFileBtn, 5, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.startFrameLineEdit = QtGui.QLineEdit(Form)
        self.startFrameLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startFrameLineEdit.setReadOnly(False)
        self.startFrameLineEdit.setObjectName(_fromUtf8("startFrameLineEdit"))
        self.gridLayout.addWidget(self.startFrameLineEdit, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 2, 1, 1)
        self.endFrameLineEdit = QtGui.QLineEdit(Form)
        self.endFrameLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endFrameLineEdit.setReadOnly(False)
        self.endFrameLineEdit.setObjectName(_fromUtf8("endFrameLineEdit"))
        self.gridLayout.addWidget(self.endFrameLineEdit, 6, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tractorCheckBox = QtGui.QCheckBox(Form)
        self.tractorCheckBox.setChecked(True)
        self.tractorCheckBox.setObjectName(_fromUtf8("tractorCheckBox"))
        self.horizontalLayout.addWidget(self.tractorCheckBox)
        spacerItem = QtGui.QSpacerItem(118, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okBtn = QtGui.QPushButton(Form)
        self.okBtn.setObjectName(_fromUtf8("okBtn"))
        self.horizontalLayout.addWidget(self.okBtn)
        self.cancelBtn = QtGui.QPushButton(Form)
        self.cancelBtn.setObjectName(_fromUtf8("cancelBtn"))
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 4)
        self.Title2ComboBox = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title2ComboBox.sizePolicy().hasHeightForWidth())
        self.Title2ComboBox.setSizePolicy(sizePolicy)
        self.Title2ComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.Title2ComboBox.setObjectName(_fromUtf8("Title2ComboBox"))
        self.gridLayout.addWidget(self.Title2ComboBox, 2, 1, 1, 3)
        self.Title3ComboBox = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title3ComboBox.sizePolicy().hasHeightForWidth())
        self.Title3ComboBox.setSizePolicy(sizePolicy)
        self.Title3ComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.Title3ComboBox.setObjectName(_fromUtf8("Title3ComboBox"))
        self.gridLayout.addWidget(self.Title3ComboBox, 3, 1, 1, 3)
        self.Title1ComboBox = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title1ComboBox.sizePolicy().hasHeightForWidth())
        self.Title1ComboBox.setSizePolicy(sizePolicy)
        self.Title1ComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.Title1ComboBox.setObjectName(_fromUtf8("Title1ComboBox"))
        self.gridLayout.addWidget(self.Title1ComboBox, 1, 1, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "HIK ImportDialog", None))
        self.aniRadioBtn.setText(_translate("Form", "Animation", None))
        self.mcpRadioBtn.setText(_translate("Form", "MotionCapture", None))
        self.crdRadioBtn.setText(_translate("Form", "Crowd", None))
        self.label.setText(_translate("Form", "Title", None))
        self.label_2.setText(_translate("Form", "Sub Title", None))
        self.label_3.setText(_translate("Form", "Part SubTitle", None))
        self.label_5.setText(_translate("Form", "Anim File Path", None))
        self.loadAnimFileBtn.setText(_translate("Form", "...", None))
        self.label_4.setText(_translate("Form", "Json File Path", None))
        self.loadJsonFileBtn.setText(_translate("Form", "...", None))
        self.label_6.setText(_translate("Form", "Start Frame", None))
        self.startFrameLineEdit.setText(_translate("Form", "1001", None))
        self.label_7.setText(_translate("Form", "End Frame", None))
        self.endFrameLineEdit.setText(_translate("Form", "1001", None))
        self.tractorCheckBox.setText(_translate("Form", "Tractor", None))
        self.okBtn.setText(_translate("Form", "Import", None))
        self.cancelBtn.setText(_translate("Form", "Cancel", None))

