# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportSourceDialogUI.ui'
#
# Created: Wed May  2 17:02:23 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from pymodule.Qt import QtWidgets as QtGui
from pymodule.Qt import QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(733, 908)
        Form.setMinimumSize(QtCore.QSize(547, 678))
        self.gridLayout_6 = QtGui.QGridLayout(Form)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.preset_label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_label.sizePolicy().hasHeightForWidth())
        self.preset_label.setSizePolicy(sizePolicy)
        self.preset_label.setMinimumSize(QtCore.QSize(0, 30))
        self.preset_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.preset_label.setObjectName(_fromUtf8("preset_label"))
        self.gridLayout_4.addWidget(self.preset_label, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.biped_radioButton = QtGui.QRadioButton(Form)
        self.biped_radioButton.setObjectName(_fromUtf8("biped_radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(Form)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.biped_radioButton)
        self.verticalLayout.addWidget(self.biped_radioButton)
        self.quad_radioButton = QtGui.QRadioButton(Form)
        self.quad_radioButton.setObjectName(_fromUtf8("quad_radioButton"))
        self.buttonGroup.addButton(self.quad_radioButton)
        self.verticalLayout.addWidget(self.quad_radioButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.preset_listWidget = QtGui.QListWidget(Form)
        self.preset_listWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.preset_listWidget.setObjectName(_fromUtf8("preset_listWidget"))
        self.gridLayout_4.addWidget(self.preset_listWidget, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.findSource_lineEdit = QtGui.QLineEdit(Form)
        self.findSource_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.findSource_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.findSource_lineEdit.setObjectName(_fromUtf8("findSource_lineEdit"))
        self.gridLayout.addWidget(self.findSource_lineEdit, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.findTarget_lineEdit = QtGui.QLineEdit(Form)
        self.findTarget_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.findTarget_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.findTarget_lineEdit.setObjectName(_fromUtf8("findTarget_lineEdit"))
        self.gridLayout_2.addWidget(self.findTarget_lineEdit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.findTargetNS_lineEdit = QtGui.QLineEdit(Form)
        self.findTargetNS_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.findTargetNS_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.findTargetNS_lineEdit.setObjectName(_fromUtf8("findTargetNS_lineEdit"))
        self.gridLayout_2.addWidget(self.findTargetNS_lineEdit, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.matching_treeWidget = QtGui.QTreeWidget(Form)
        self.matching_treeWidget.setProperty("showDropIndicator", False)
        self.matching_treeWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.matching_treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.matching_treeWidget.setExpandsOnDoubleClick(False)
        self.matching_treeWidget.setColumnCount(5)
        self.matching_treeWidget.setObjectName(_fromUtf8("matching_treeWidget"))
        self.matching_treeWidget.headerItem().setText(1, _fromUtf8("Source"))
        self.matching_treeWidget.headerItem().setText(2, _fromUtf8(">"))
        self.matching_treeWidget.headerItem().setText(3, _fromUtf8("Target"))
        self.matching_treeWidget.header().setCascadingSectionResizes(False)
        self.matching_treeWidget.header().setDefaultSectionSize(200)
        self.matching_treeWidget.header().setHighlightSections(False)
        self.matching_treeWidget.header().setMinimumSectionSize(200)
        self.matching_treeWidget.header().setSortIndicatorShown(False)
        self.matching_treeWidget.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.matching_treeWidget, 1, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(63, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.jointToIK_radioButton = QtGui.QRadioButton(Form)
        self.jointToIK_radioButton.setObjectName(_fromUtf8("jointToIK_radioButton"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.jointToIK_radioButton)
        self.horizontalLayout_2.addWidget(self.jointToIK_radioButton)
        self.jointToFK_radioButton = QtGui.QRadioButton(Form)
        self.jointToFK_radioButton.setObjectName(_fromUtf8("jointToFK_radioButton"))
        self.buttonGroup_2.addButton(self.jointToFK_radioButton)
        self.horizontalLayout_2.addWidget(self.jointToFK_radioButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.ok_pushButton = QtGui.QPushButton(Form)
        self.ok_pushButton.setObjectName(_fromUtf8("ok_pushButton"))
        self.horizontalLayout.addWidget(self.ok_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(Form)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Retarget Import Dialog", None))
        self.preset_label.setText(_translate("Form", "PRESET", None))
        self.biped_radioButton.setText(_translate("Form", "biped", None))
        self.quad_radioButton.setText(_translate("Form", "quadruped", None))
        self.label.setText(_translate("Form", "Source", None))
        self.label_2.setText(_translate("Form", "Target", None))
        self.label_3.setText(_translate("Form", "namespace", None))
        self.matching_treeWidget.headerItem().setText(0, _translate("Form", "no.", None))
        self.matching_treeWidget.headerItem().setText(4, _translate("Form", "exist", None))
        self.jointToIK_radioButton.setText(_translate("Form", "to IK CON", None))
        self.jointToFK_radioButton.setText(_translate("Form", "to FK CON", None))
        self.ok_pushButton.setText(_translate("Form", "apply", None))
        self.cancel_pushButton.setText(_translate("Form", "cancel", None))

